### ISSUE TITLE
How to test this workbench?

### ISSUE THREAD

**Issue by andy-kliman** [realthunder/FreeCAD_assembly3#1]

**Comment by realthunder** [comment]
Thanks for the interest. But, it's not ready yet. I'll post up instructions once it's ready. It only works on my heavily patched FCAD, so you'll need to be able to compile FCAD yourself in order to test it.

**Comment by andy-kliman** [comment]
Where can I find the sources of the patched FCAD?

I tried to run the workbench by copying the contents to the MOD folder, but the console displays the messages "No module named asm3 occurred"

**Comment by realthunder** [comment]
Most likely https://github.com/realthunder/FreeCAD/tree/LinkStage3.8, but may change. This WB also serves as a test ground for my FCAD branch. At the moment, both this and my FCAD repo are under frequent changes (I am doing rebase a lot since they are not published yet). So it is best to just wait for a few weeks before getting your hands dirty.

**Comment by andy-kliman** [comment]
Ok
In the future the workbench can be used with the standard FCAD build or not?

**Comment by realthunder** [comment]
That's my goal, of course. I am trying to get my branch merged into upstream, but it is going to be a long process, because it has quite a few core changes. This WB is also my attempt to accelerate the process, you know, to show them that those core changes are worthy.

**Comment by andy-kliman** [comment]
I wish good luck, I will follow up

**Comment by realthunder** [comment]
Thanks

**Comment by luzpaz** [comment]
Now that the README is live we can ask @yorikvanhavre to put this WB in FreeCAD-Addons so it will be easy for folks to download in to this said forked version of FC that you mention.

**Comment by yorikvanhavre** [comment]
I prefer to wait until @realthunder tells me it's good to go, then I add it to the FreeCAD-Addons.
BTW, Fantatic job @realthunder !!! I really like that incremental approach, building after other, earlier experiments (assembly2), that's the best way we get to build a real assembly workflow IMHO

**Comment by realthunder** [comment]
A Windows pre-built image is now available at https://github.com/sgrogan/FreeCAD/releases/tag/RTA3

**Comment by realthunder** [comment]
Linux AppImage is now available [here](../releases/latest)

**Comment by efferre79** [comment]
@realthunder : which branch of your freecad fork are you usually using these days?

**Comment by realthunder** [comment]
FreeCAD releasing branch is [LinkStage3](https://github.com/realthunder/FreeCAD/tree/LinkStage3).

**Comment by timmwille** [comment]
it is time to test right? at least from the edit here:
https://www.forum.freecadweb.org/viewtopic.php?f=34&t=45349

by the way while looking for a way to get this running I found the very origins how this was mentioned to the FC developers first:
https://gitter.im/probonopd/AppImageKit?at=5a2683ef3a80a84b5bbc228c

thank you so much for all the work @realthunder and all the helping hands around! warms up the open source hardware engineers heart to see this grow

**Comment by luzpaz** [comment]
We can close this ticket as well.
