### ISSUE TITLE
[Spreadsheet] - python mode, accessing array (Help)

### ISSUE THREAD

**Issue by Dtays-meanderings** [realthunder/FreeCAD_assembly3#1003]
Hi,

Arrays from within a spreadsheet appear unable to take an index value as a variable. Perhaps it is security or maybe a bug? Is there a solution I am missing? 

This works:
```
=#@pybegin
arr = [10, 11, 12, 13]
._py.print(arr[1])

```

This gives an error:
```
=#@pybegin
arr = [10, 11, 12, 13]
i = 1
._py.print(arr[i])
```
"PyCXX: Error creating object of type class Py::SeqBase<class Py::Object> from 1
in expression: arr[i]"

Thanks!
Python in a spreadsheets is pretty cool! :)

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.1015.24301 +4280 (Git)
Build type: Release
Branch: LinkDaily
Hash: 556c87868ea46796242156e9f73eae98259794b7
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
This is a bug, and has been fixed by https://github.com/realthunder/FreeCAD/commit/4b6f76e2b6ad8390e9da01160877a5ad13ce12eb
