### ISSUE TITLE
Sync view disable key

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#101]
Sync view is a nice feature, but creates conflicts for some tools that require to select some target object while its own object is opened and then pressing one of its command buttons (like TechDraw Projections). 

It would be nice to have a key (like `Alt` or `Ctrl`) to disable this `Sync view` feature temporarily (while holding that key down) rather than toggling it within `Tree view options`.

**Comment by realthunder** [comment]
I have exposed the sync view option as a toolbar button, with default accelerator keys as "V, C". This means that you can easily toggle this option by simply type V+C in your keyboard.

**Comment by ceremcem** [comment]
![image](https://user-images.githubusercontent.com/6639874/45736511-d46a8d80-bbf3-11e8-8d0b-cff66da00a2b.png)
