### ISSUE TITLE
libopengl0 prerequisite missing from 2022.01.11

### ISSUE THREAD

**Issue by grtyvr** [realthunder/FreeCAD_assembly3#1015]
Not sure if libopengl0 should have been on my system or of the Appimage should have no external dependencies but I need3ed to install libopengl0 before I was able to launch

OS: Ubuntu 20.04.3 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2022.111.28429 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: ec814c42d02f15171f9dbb7f650400c9943abfe0
Python version: 3.9.9
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/Canada (en_CA)

**Comment by bambukouk** [comment]
https://github.com/realthunder/FreeCAD_assembly3/issues/1009#issue-1099105819
