### ISSUE TITLE
Moving objects another way from drag and drop

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#103]
In large trees, dragging&dropping objects (`Elemet`s, regular objects, `Element`s to create links in another document) becomes frustrating. 

### Proposal

Support Cut+Paste and Copy+Paste for 
* Move objects into Assembly containers 
* Create element links between documents

**Comment by realthunder** [comment]
Select the object you want to drag as before, and navigate to the item you want to drop, then use key shortcut `Ctrl+Shift+D` to activate dragging.

**Comment by realthunder** [comment]
I have changed the shortcut of dragging to `T, D`

**Comment by ceremcem** [comment]
Sometime later we may do something about shortcuts, though. Different layouts makes the shortcuts longcuts.

**Comment by realthunder** [comment]
I have exposed all option commands to command manager. You can customize command shortcut by right click in toolbar, and select `Customize`. Go to `Keyboard`. The commands are under category `TreeView`.
