### ISSUE TITLE
Comma is added to the beginning of shortcut

### ISSUE THREAD

**Issue by Rabbit-sk** [realthunder/FreeCAD_assembly3#1033]
Hi RealThunder!

After creating a shortcut, a comma is added to the beginning when creating another shortcut. 

https://user-images.githubusercontent.com/74265320/149553262-b51e76a6-caac-40ba-b2c5-71dd69033244.mp4

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.111.30764 (Git)
Build type: Release
Branch: LinkDaily
Hash: ef3092bcbca5475eff4eb7ff7933eb3e9bbbe4b9
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: Slovak/Slovakia (sk_SK)

**Comment by brandonbeaumia** [comment]
I've just spent the last three days tweaking and rebinding my shortcuts; had the same problem and backspacing every single time a shortcut was entered was a huge nuisance.
