### ISSUE TITLE
weird graphical artifacts when moving sketch geometry around

### ISSUE THREAD

**Issue by kevenwyld** [realthunder/FreeCAD_assembly3#1043]
Sometimes when dragging sketch geometry around extra edges appear and then disappear.  It happens both with and without the experimental rendering engine.

Here's a video:

https://user-images.githubusercontent.com/11936535/149647366-773fc87d-80f2-4848-a6b2-9e602aad812a.mp4

```
OS: Arch Linux (i3/i3)
Word size of FreeCAD: 64-bit
Version: 2022.111.30764 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: ef3092bcbca5475eff4eb7ff7933eb3e9bbbe4b9
Python version: 3.9.9
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)
```

**Comment by Rabbit-sk** [comment]
On Windows too:

https://user-images.githubusercontent.com/74265320/149798710-5eb27784-9993-4c51-8f4c-882040d50399.mp4

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.111.30764 (Git)
Build type: Release
Branch: LinkDaily
Hash: ef3092bcbca5475eff4eb7ff7933eb3e9bbbe4b9
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: Slovak/Slovakia (sk_SK)
