### ISSUE TITLE
The document bar responds to clicks only after switching widgets

### ISSUE THREAD

**Issue by Rabbit-sk** [realthunder/FreeCAD_assembly3#1053]
Hi RealThunder!

The orange area responds to clicks only affter some inactive tab is clicked. In tihs case one in the green area. After that it is possible to switch between opened documents, close them or change their order in the orange area.
![obrázok](https://user-images.githubusercontent.com/74265320/149785739-20f2ba47-8151-4de7-a30d-36c8085220b3.png)
FCParam: [Tabs.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7882465/Tabs.zip)

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.111.30764 (Git)
Build type: Release
Branch: LinkDaily
Hash: ef3092bcbca5475eff4eb7ff7933eb3e9bbbe4b9
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: Slovak/Slovakia (sk_SK)

**Comment by luzpaz** [comment]
Noticed this using VertUI and trying to click the dang report view or python console.
