### ISSUE TITLE
How to compile Linkstage3 Branch master  in Arch/Manjaro Linux ?

### ISSUE THREAD

**Issue by QuakeString** [realthunder/FreeCAD_assembly3#1057]
is it possible to compile FreeCAD LinkStage3 branch master ?
As I was opened a issue, and its been patched, but I have to wait till the new daily release. So if there is a documentation for compile and install then I can follow and try myself the effect of patched code.
here is my system detail:
Operating System: Manjaro Linux
KDE Plasma Version: 5.23.4
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.15.12-1-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-8250U CPU @ 1.60GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by bambukouk** [comment]
https://wiki.freecadweb.org/Compile_on_Linux

not that I know how to use these instructions... (I prefer to wait for the next release)
