### ISSUE TITLE
Changing draw style does not affect objects in an assembly

### ISSUE THREAD

**Issue by ShadowNinja** [realthunder/FreeCAD_assembly3#11]
1. Add a box inside an assembly, and another box outside of it.
2. Switch draw style to wireframe.
3. Only the box outside the assembly will switch to wireframe.

**Comment by realthunder** [comment]
Thanks for reporting, will fix soon.

**Comment by ceremcem** [comment]
I can confirm that this issue has been fixed:

![image](https://user-images.githubusercontent.com/6639874/44623905-a0969380-a8e5-11e8-9a02-ac263d54e193.png)
