### ISSUE TITLE
is there a way to control position of where (pre)selected geometry measure is displayed?

### ISSUE THREAD

**Issue by bambukouk** [realthunder/FreeCAD_assembly3#1102]
At the moment it looks like this (red arrow pointing to display of measurement of pre-selected geometry).
Is there any way I can control the position it is displayed at?

![preselect_measure](https://user-images.githubusercontent.com/50301871/152219298-2d23dd12-8145-467a-9f67-e0db27bedc7c.png)

**Comment by herrgerd** [comment]
![grafik](https://user-images.githubusercontent.com/24494466/152843048-3f311508-ad18-4b1c-bbdb-c83912f8f9c3.png)

**Comment by bambukouk** [comment]
Thank you 👍
will experiment with it when I am back from my travels and back at my PC
