### ISSUE TITLE
[Feature Request] External/defining geometry for whole surfaces

### ISSUE THREAD

**Issue by FEA-eng** [realthunder/FreeCAD_assembly3#1108]
This branch added very useful Defining geometry tool thanks to which it's not necessary to draw on the lines projected by External geometry to use them outside of the sketch. But both these tools require picking edges one by one. It would be really great if they could project all the edges belonging to a face upon clicking on it.

**Comment by realthunder** [comment]
Feature implemented. You can now use `G, G` to pick wire.

https://user-images.githubusercontent.com/1207888/160368193-3b341b30-6189-44e8-8827-4334b10719cc.mp4

**Comment by FEA-eng** [comment]
Great news, thank you very much for implementing this.
