### ISSUE TITLE
Feature information

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#1109]
https://forum.freecadweb.org/viewtopic.php?f=8&t=66038

**Comment by herrgerd** [comment]
This is a issues/bug tracker. What do you want to achieve with this post?
It seems to me that your mission is to ask for each and every feature CATIA has to be included in FreeCAD.

Hint: FreeCAD isn't CATIA, nor is it Inventor, SolidWorks, NX or any other multi million dollar corp CAD suite...
