### ISSUE TITLE
Next Daily/Stable Release tentitive date.

### ISSUE THREAD

**Issue by QuakeString** [realthunder/FreeCAD_assembly3#1114]
Hi Dev,
I was wandering when next release coming up.
My issue fixed here [0ea6855](https://github.com/realthunder/FreeCAD/commit/0ea68559104c3c285fc5076a5909b74343b21992)
But compiling by myself giving me many error while using FreeCAD.
One of my personal project stuck. Eagerly waiting for next release.

**Comment by realthunder** [comment]
If you are using Linux, you can try the [snap build](https://snapcraft.io/freecad-realthunder). If you are on Windows, then you can manually fix the problem by finding the `gui_selectplane.py` file and editing it according to [0ea6855](https://github.com/realthunder/FreeCAD/commit/0ea68559104c3c285fc5076a5909b74343b21992).

**Comment by QuakeString** [comment]
Thank You for super quick reply.
I use Manjaro Linux, I'll try snap build now.

**Comment by luzpaz** [comment]
Closing
