### ISSUE TITLE
Spreadsheet: painfully long recompute times, even just changing unaliased text fields

### ISSUE THREAD

**Issue by brandonbeaumia** [realthunder/FreeCAD_assembly3#1119]
Per this thread in the FreeCAD forums, this bug was sorted out already somewhere in the 0.20 dev branch in early December(ish). Is there any chance we can get the fix merged for next release? On my laptop I'm waiting over 5 seconds between cells just to put some text in, which makes spreadsheets almost unusable.

Unfortunately, I couldn't track down the commit but here's the forum thread where chennes states it is fixed.

https://forum.freecad.org/viewtopic.php?f=8&t=48600&sid=6c48873c06345debe52acdb872e143b8&start=10

OS: Pop!_OS 21.10 (pop:GNOME/pop)
Word size of FreeCAD: 64-bit
Version: 2022.111.30764 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: ef3092bcbca5475eff4eb7ff7933eb3e9bbbe4b9
Python version: 3.9.9
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
Can you please post a file showing the problem? If it's sensitive, maybe you can share through my email realthunder.dev at gmail.

**Comment by brandonbeaumia** [comment]
[mdt2.zip](https://github.com/realthunder/FreeCAD_assembly3/files/8061108/mdt2.zip)

Sorry about that. By the forum post I assumed it was a problem with most/all files. so left it at that. Here's the file (rename .zip to .fcstd)

**Comment by realthunder** [comment]
The problem should be fixed with the above commit. Thanks for reporting. Note that there are additional recompute optimization implemented in my branch. The problem here is not related to the provided link.
