### ISSUE TITLE
py-slvs bindings not available for Apple Silicone MacBook Pro

### ISSUE THREAD

**Issue by shandyba** [realthunder/FreeCAD_assembly3#1123]
It appears there are no apple silicone compatible wheels available for `py-slvs` bindings:

```
pip install py-slvs
...
No matching distribution found for py-slvs
```

while running 
```
pip install py-slvs -vvv
```

produces a list of available wheels none of which are apple silicone compatible (`universal` or `arm`), as is expected by observing `pip debug --verbose` output.

Thus, "no solver found" on a MacBook pro with Apple Silicone.

Will appreciate any hints / workarounds / fixes! :)

**Comment by realthunder** [comment]
I have just updated py-slvs package with the MacOS universal wheel. Please try again.

**Comment by shandyba** [comment]
Hi, thanks a lot, it works now!
