### ISSUE TITLE
Loss of workbenches list

### ISSUE THREAD

**Issue by jpg87Fr** [realthunder/FreeCAD_assembly3#1130]
OS: Ubuntu Core 20 (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 2022.213.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 2022.02.13-edge)
Hash: ce7fe6dc1c51f6074b58d125342fc3615b0a564f
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.1
OCC version: 7.5.2
Locale: French/France (fr_FR)

Hello I am currently testing the snap version of February 13 and I have a small problem :
At startup, I have my list
![Capt01](https://user-images.githubusercontent.com/80101333/154857181-a35119ca-cbaf-49f1-a577-4a8bbcfb703a.png)

if I want to customize my list, I get this
![Capt02](https://user-images.githubusercontent.com/80101333/154857209-c404544d-830b-44c9-af96-a8693b454d79.png)

when I close the window, no more workbench
![capt3](https://user-images.githubusercontent.com/80101333/154856446-70ae61f7-70e1-4f96-8b45-f0414683d299.png)

I have to re-enter them manually in the settings editor (or in link.user.cfg).
![capt4](https://user-images.githubusercontent.com/80101333/154856452-8e01d6da-6606-4b63-ac8f-bd82c0bad31f.png)

**Comment by luzpaz** [comment]
@jpg87Fr still an issue?

**Comment by jpg87Fr** [comment]
Hello and thank you very much.
Works fine in the March 07 Snap release.
