### ISSUE TITLE
What's the green eye in treeview ? 

### ISSUE THREAD

**Issue by girow** [realthunder/FreeCAD_assembly3#1136]
OS: ManjaroLinux
Word size of FreeCAD: 64-bit
Version: FreeCAD-asm3-Stable-Conda-Py3-Qt5-20211015-glibc2.12-x86_64.AppImage
Build type: Stable
Branch: LinkDaily
Locale: Japanse/japan (ja_JP)

![スクリーンショット_2022-02-24_22-22-50](https://user-images.githubusercontent.com/36090956/155535325-e3748df6-641a-431b-98d5-68dd9c253e47.jpg)
Thank you for your develop.I fully enjoy linkstage Ver.

What is the green eye icon in treeview ? The green eye icon item can't be controlled visibility.

When FreeCAD restarts, the part and the sketcher remain visible.

Is there a good solution?

**Comment by realthunder** [comment]
Yes, it is a known bug, and has already been fixed. The green eye marks the `Show on top` object. You can work around it for now by pressing `Ctrl + Shift + Space` when there is no selection. This clears all `Show on top` objects.

**Comment by girow** [comment]
I'm sorry, I didn't see the bug information. 

And thank you for suggesting a solution ! I will try it !

**Comment by luzpaz** [comment]
Closing ticket
