### ISSUE TITLE
New link creation proposal

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#114]
# Proposal 

1. New links should be created within the same Assembly container if there is no purpose to send it to the root. 
2. New links are created `Link${nnn}_${sourceLabel}` format. It would be useful to have them source label prefixed, like `${sourceLabel}_${nnn}` (without the `Link` part).

**Comment by realthunder** [comment]
> 1. New links should be created within the same Assembly container if there is no purpose to send it to the root.

Well, util I introduce the active assembly concept, there is no easy way to guess user's intention. There is pretty good reason to have linked object in root level, as mentioned [here](86#issuecomment-420598146).

> 2. New links are created `Link${nnn}_${sourceLabel}` format. It would be useful to have them source label prefixed, like `${sourceLabel}_${nnn}` (without the `Link` part).

You mean you prefer the link with the same label plus prefix as the linked object?
