### ISSUE TITLE
question - "show item checkbox" what is it for?

### ISSUE THREAD

**Issue by bambukouk** [realthunder/FreeCAD_assembly3#1141]
I know you can turn it on or off in preferences, but what is it for?
Why would I want to use it?
Please

**Comment by realthunder** [comment]
This is a feature from upstream. It allows multi-selecting items in tree view without keyboard.

**Comment by bambukouk** [comment]
Thank you, 
so no real use in Link branch?

**Comment by bambukouk** [comment]
Mystery solved :+1: 
thank you
