### ISSUE TITLE
question - "mystery" icon

### ISSUE THREAD

**Issue by bambukouk** [realthunder/FreeCAD_assembly3#1142]
https://forum.freecadweb.org/viewtopic.php?f=20&t=66690 
can anybody help, please?

**Comment by kevenwyld** [comment]
I linked to the forum post about that feature.  Hope that helps.

**Comment by bambukouk** [comment]
found the answer:
https://forum.freecadweb.org/viewtopic.php?f=19&t=52221&start=100#p448653

Thank you.
