### ISSUE TITLE
external geometry problems

### ISSUE THREAD

**Issue by bambukouk** [realthunder/FreeCAD_assembly3#1154]
I have two sketches in an (active) body.
In one sketch have no problems picking external geometry,
but another sketch refuses to allow me to pick external geometry?
Here an example of first sketch - no problem
![pocket](https://user-images.githubusercontent.com/50301871/158580485-3c2dff7c-7b5a-42b7-b20f-4e12aecda339.png)
and yet the same active body in another sketch doesn't work:
![passages](https://user-images.githubusercontent.com/50301871/158580683-cb1536a0-8e98-4925-83d6-9201d0f1a941.png)

I have had temperamental issues with external geometry before but somehow always managed to coax FreeCAD into obeying me :+1: 
but this time for some reason it is NO GO :-1: 
I have tested in earlier releases of Link branch and the issue is exactly the same - sounds like some problem with my model?

**_I have copied and paste offending body into another file and problem has disappeared, so it seems to be only causing problems when used in assembly..._**

**_LATER EDIT:
Just to explain situation:
Body in question is used in LH assembly and linked (with scale=-1) to create mirror image used in RH assembly.
Both LH and RH assemblies are in turn externally linked to a top level assembly.
In an attempt to try to find a solution I have made RH assembly visible and suddenly for no logical reason external geometry works fine and I have no problem (although I doubt whether it was this that actually did anything - next time on another sketch in the same body it didn't make any difference)....
Most puzzled._**

Anybody else with similar experience or any ideas?
Please

```
OS: elementary OS 6.1 JAlnir (Pantheon/pantheon)
Word size of FreeCAD: 64-bit
Version: 2022.111.30764 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: ef3092bcbca5475eff4eb7ff7933eb3e9bbbe4b9
Python version: 3.9.9
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United Kingdom (en_GB)

```

**Comment by realthunder** [comment]
Is it possible to share your file here?

**Comment by bambukouk** [comment]
Thank you @realthunder 
I have tried to simplify it and still repeat the problem but haven't made much progress yet.
Happy to email you download link to the whole assembly? if you are willing to have a look at it?

**Comment by bambukouk** [comment]
Hi @realthunder 
I have deleted everything un-connected to the issue leaving just a very simple assembly.
Problem is repeatable, here is where you can try it.
(`cylinder_body_LH` active, modifying `sketch_077` and unable to add external geometry from the active body?)
![external_geo_issue](https://user-images.githubusercontent.com/50301871/159156340-51adef46-7561-420c-bf0b-03b476a4c6c7.png)

File:
[ext_geo_issue.zip](https://github.com/realthunder/FreeCAD_assembly3/files/8310933/ext_geo_issue.zip)

**Comment by realthunder** [comment]
The image shows you bound on another sketch. Are you trying to pick the geometry from that sketch? I am asking because it looks like you are trying to pick geometry from another feature late in the history, which will cause dependency loop. For some reason, you have disabled auto hiding sketch dependency option. If it's enabled, then those features late in history will be hidden, and for a good reason, because the sketch are not allowed to depend on a feature that depends on it in the first place.

PS. if you want to enable that option, make sure to click `Apply to existing sketch` because those options are saved into the sketch object.

![image](https://user-images.githubusercontent.com/1207888/161752984-0e669c36-2c18-49f3-beb7-33fcdc2fac43.png)

**Comment by bambukouk** [comment]
No, I am trying to modify `Pad108` and working on `Sketch249`
and picking external edge from an earlier feature (in the same body)
It is possible that I am doing something wrong - this problem only occurs when "repairing" old designs
so you might be right about dependency loop?
I will change Sketcher Display settings as per your recommendation and report result
Thank you, as usual for your help :+1:

**Comment by bambukouk** [comment]
Sounds like a problem solved, thank you
