### ISSUE TITLE
Drag & drop fail... Access violation

### ISSUE THREAD

**Issue by bntarc** [realthunder/FreeCAD_assembly3#1170]
Issue description

I am using the workbench Assembly 3.
When I try to Drag & drop a part to an assembly (the assembly and part are 2 different file) I have the following message:
AS3 Drag & drop fail... Access violation

However when I import a part to an assembly (the assembly and part are in the same file) is is working.

Forums discussion: [](https://forum.freecadweb.org/viewtopic.php?f=20&t=67331&start=10)

![image](https://user-images.githubusercontent.com/54326163/160739811-1eba061f-270f-4b58-aebd-8094f34a4950.png)

0.20-27809

11:58:02 Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Roaming\FreeCAD\Mod\Assembly3\.\freecad\asm3\assembly.py", line 469, in dropObjectEx
me.setLink({-1:obj})
<class 'Base.FreeCADError'>: Access violation

0.20-27422

11:53:44 Unknown command 'Part_SectionCut'
11:55:04 Illegal storage access...
11:55:04 Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Roaming\FreeCAD\Mod\Assembly3\.\freecad\asm3\assembly.py", line 469, in dropObjectEx
me.setLink({-1:obj})
<class 'Base.FreeCADError'>: Illegal storage access! Please save your work under a new file name and restart the application!

0.20-28193

12:00:04 Recent macros : shortcut 1 disabled because conflicting with Std_ViewFront
12:00:04 Recent macros : shortcut 2 disabled because conflicting with Std_ViewTop
12:00:51 Traceback (most recent call last):
File "C:\Users\Administrator\AppData\Roaming\FreeCAD\Mod\Assembly3\.\freecad\asm3\assembly.py", line 469, in dropObjectEx
me.setLink({-1:obj})
<class 'OSError'>: Access violation

**Comment by bambukouk** [comment]
forum thread:
https://forum.freecadweb.org/viewtopic.php?f=20&t=67331

it only happens when uding assembly 3 in latest 20 version of master branch.
There is no problem with either earlier 19 versions of master or Link branch.

Sounds like a regression in master branch, and report being closed there and @bntarc  being told to post it here instead is strange?
