### ISSUE TITLE
Path Array-related Issues

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#1174]
The transform option is missing. 
  
![5](https://user-images.githubusercontent.com/92737149/161376018-99c378fb-f1c9-4a77-890f-cf57b610642e.jpg) 

There is another problem. When an object created in part design is tried to run on the path, it does not move on the path. I tried to run revolution on a path. The result did not turn out as expected.  

![3](https://user-images.githubusercontent.com/92737149/161376059-dc1e844a-4ce6-4d6c-966d-cccc5652c929.jpg) 

file               

[Revolution.zip](https://github.com/realthunder/FreeCAD_assembly3/files/8402203/Revolution.zip) 

But when I tried to run the cone on the path, the result was as expected. 

![4](https://user-images.githubusercontent.com/92737149/161376116-9d9a930c-f9b2-4135-94dd-da3c00cc66ad.jpg) 

file 

[Cone.zip](https://github.com/realthunder/FreeCAD_assembly3/files/8402205/Cone.zip)

**Comment by realthunder** [comment]
The context menu is fixed with the above commit.

The offset problem is not really a bug.  Because the way your sketch is created, the wire is internal offset to the origin. Draw your sketch around the origin shall fix the problem.

**Comment by hamza00789** [comment]
> 

I don't understand what you mean. Can you explain further?
