### ISSUE TITLE
Dependent objects to selection

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#1178]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.402.26244 +4679 (Git)
Build type: Release
Branch: LinkDaily
Hash: 2ed36c0a234b3871a790ac8437f496f29e025ded
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: English/United States (en_US)

This option is not available in Link Branch. Can I request this at Link Branch? I need it often. Could this feature be available within Link Branch in the future? 

![1](https://user-images.githubusercontent.com/92737149/161545450-259a61a1-ead3-42bf-b63a-2699d1c029af.jpg)

**Comment by hamza00789** [comment]
> 
This option is used if I want to see or hold the children of a parent. This feature was not previously available in freecad. Which was quite annoying for me. It is most commonly used when the file is large enough. For example, I used the fill command. Now Fill is a father and has many children. the children may be up and down in a tree. It's hard to find these children in a large tree.

**Comment by realthunder** [comment]
But that command will select all children and their children as well. Do you find that useful? I saw this function is added in upstream recently, but having doubt how useful would that be. What you require is to select only the direct children I guess. BTW, for your example, the Fill object, it has a property listing all the objects used, just click that property in the property view will select all those objects.

**Comment by hamza00789** [comment]
This command is very useful. I tried It only selected object children, not their children. You are talking about fill property listing. Fill property listing is useful but this command is more useful. I wanted to give you some advice in this regard. If some options are added to the property listing, it will be better than this order. One eye icon.filter object-dependent feature.  

![01](https://user-images.githubusercontent.com/92737149/161727756-f50c0935-e20c-4510-b529-0d9e68c372db.jpg)

**Comment by hamza00789** [comment]
This command is very useful. I tried It only selected object children, not their children.

**Comment by hamza00789** [comment]
Is this problem solved? Should I close it?

**Comment by realthunder** [comment]
Oops, wrong commit message, which is supposed to close this issue automatically. The new commands are added to 'Context menu -> Selection -> Select direct dependent objects'
