### ISSUE TITLE
solid features grouping - right click menu problems...

### ISSUE THREAD

**Issue by bambukouk** [realthunder/FreeCAD_assembly3#1186]
How did I manage to get from this:
![before](https://user-images.githubusercontent.com/50301871/162008858-a1617889-8b8b-4bcf-a0de-c13f9473038d.png)

to that:
![final](https://user-images.githubusercontent.com/50301871/162008935-469fa1c2-71e7-43c9-aa49-d02c5bd1ced9.png)

I am fuffing around with an old model making some modifications and for some reason I have managed to change tree of the body I am working on...
Haven't got a clue what I might have done.
It's not really a problem but I would prefer to know, please

What is the significance of double green "tip of the body" tags? (in the final version for Pocket054)

I have extracted bodies affected in separate file (just in case someone cares to have a look at it...) :
[tag_test.FCStd.zip](https://github.com/realthunder/FreeCAD_assembly3/files/8429190/tag_test.FCStd.zip)

Looking at dependency graph there is some puzzling `x2` feature ???? 
![dependency_graph](https://user-images.githubusercontent.com/50301871/162049257-ffce21c2-a19a-4453-b602-3205f1b9ed64.png)

**Comment by realthunder** [comment]
This is done through solid grouping. It is useful in case you have multiple solids in a body. This allows you to group features (i.e. histories) of a solid. Right click a feature (usually the last feature of a solid), and select `Group solid features` action. And there is also the `Ungroup` action.

**Comment by bambukouk** [comment]
Yes, I have been trying `right click on feature` long before I posted here 🙂
and I have never seen any `group/ungroup` option....
Tried again after your reply (thank you very much 👍 ) and once briefly seen this option, but can repeat it again 🤢
I will keep trying to see what I am (possibly) doing wrong

**Comment by bambukouk** [comment]
I would be extremely grateful if someone could try opening the file attached in the first message and confirm (or dismiss) solid features grouping appearing in the right click menu of the grouped `Pocket054`
I really want to know if there is a problem with this file or is it me going round the bend...

**Comment by realthunder** [comment]
You had `Auto solid group` enabled for the body, which is why you can't ungroup manually. Right click the body and `Disable auto solid group` and then you can ungroup manually.

**Comment by bambukouk** [comment]
OK, thank you!
I now understand what I was doing wrong (looking for right click options only in grouped feature, without thinking to check body right click options as well...)

All is well that ends well and sorry for bothering you with such trivia :+1: 

Perhaps I should volunteer to start wiki collecting all these nice features?
