### ISSUE TITLE
Problem with <<Create "{}">> 

### ISSUE THREAD

**Issue by Kuzma30** [realthunder/FreeCAD_assembly3#1192]
In translated version messages with <<Create "{}">> pattern show without last <<">>. Is it translating problem?

**Comment by luzpaz** [comment]
Screenshot? About info?
Link to the translation string?

**Comment by Kuzma30** [comment]
OS: Ubuntu Jammy Jellyfish (development branch) (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.20.30937 (Git)
Build type: Release
Branch: LinkDaily
Hash: 9610830a8fd492b3b3d96f8328507c80f1437cda
Python version: 3.10.4
Qt version: 5.15.3
Coin version: 4.0.0
OCC version: 7.7.0.dev
Locale: Ukrainian/Ukraine (uk_UA)

![Знімок екрана з 2022-04-07 20-08-54](https://user-images.githubusercontent.com/1382812/162259386-b145b678-7b29-4d7a-9dcd-0f302e077fcc.png)

**Comment by luzpaz** [comment]
Can you link to the translation string in the source?

**Comment by Kuzma30** [comment]
https://github.com/realthunder/FreeCAD_assembly3/blob/1d05e13540ac4cdedf3a382a6189bbf460150c3b/freecad/asm3/constraint.py#L917
