### ISSUE TITLE
Chamfer

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#1197]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.406.26244 +4692 (Git)
Build type: Release
Branch: LinkDaily
Hash: 0c8e437ef38cdc5dd087529ce6825c6a2a130868
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: English/United States (en_US)
 
The chamfer is not working on this edge. The result is very bad.  

![1](https://user-images.githubusercontent.com/92737149/162564101-60352e4d-4802-4a84-a70c-04cd0cbc95d3.jpg) 

![2](https://user-images.githubusercontent.com/92737149/162564110-2ff425ff-e250-4b31-b55b-10831b72963f.jpg) 

![3](https://user-images.githubusercontent.com/92737149/162564119-3a8c6659-e233-4322-bea5-310ba8a4c25f.jpg)  

You can see the problem in the file. 

[Chamfer.zip](https://github.com/realthunder/FreeCAD_assembly3/files/8456567/Chamfer.zip)

**Comment by herrgerd** [comment]
Maybe use the traditional way with the Groove-Tool instead of sectioning/slicing, hiding one part and...
![grafik](https://user-images.githubusercontent.com/24494466/162569054-abfcd096-81fe-4571-8aba-db6fab27ea28.png)

**Comment by bambukouk** [comment]
Simple - the issue is coincident edges
Rotate/Offset Sketch001 attachment around Y axis away from the edge and all is well:
![Screenshot from 2022-04-09 12 16 05](https://user-images.githubusercontent.com/50301871/162569537-01dd6516-775c-4a11-a893-0af7b5b9d7e4.png)

**Comment by hamza00789** [comment]
Can you post this file? 

![5](https://user-images.githubusercontent.com/92737149/162573765-133021b2-a6c7-4559-bfc6-30b0357c0cb5.jpg)
