### ISSUE TITLE
The problem of freecad crashing using sublink

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#1214]
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.407.26244 +4693 (Git)
Build type: Release
Branch: LinkDaily
Hash: 9610830a8fd492b3b3d96f8328507c80f1437cda
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: English/United States (en_US) 

Freecad crashes when I use the sublink command in the lattice workbench. As you can see in the video free cad crashes when I try to sublink a face.   

https://user-images.githubusercontent.com/92737149/163738889-06eb33bb-f4c4-4642-8c22-1169032a724b.mp4

**Comment by realthunder** [comment]
Normally, if there is a hard crash, it almost always indicates something wrong with the FreeCAD itself, instead of some external workbench. So [#359](realthunder/FreeCAD#359) is more appropriate.
