### ISSUE TITLE
 'utf-8' codec can't decode byte 0xfc in position 301: invalid start byte

### ISSUE THREAD

**Issue by ElPatoNoEsTu** [realthunder/FreeCAD_assembly3#1221]
Hi all, 

after replacing a former version (mid summer 2021)  by the current 2022.04.07  i get the above message. 

doinge a search - i found it might have to do with th "locale" setting -  but I cant  "export"  encodiung-setting due to using windows as os .   

Also it looks like the startup-scrip isn't read correctely as i get a blank "freecad-window" without the used possibilitiys in selecting a last used file ... 

any Idea ? 

Regards, Stefan

PS Unfortunately I even can't tell more about the file - where this happens.   ( are there any "debug" switches to tell freecad to be more verbose regarding its startup ? )  

PPS: could the startup ... ?!  file be broken ?

**Comment by luzpaz** [comment]
Where do you get the message? Do you have an example file?
If you can load FreeCAD, please post your full [About](https://wiki.freecad.org) info

**Comment by ElPatoNoEsTu** [comment]
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2022.407.28576 (Git)
Build type: Release
Branch: LinkStage3
Hash: 599f7663af69d3dbd77063e834b12f26da513b2d
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: German/Germany (de_DE)
<img width="691" alt="2022-04-23 14_59_30-FreeCAD Link Branch" src="https://user-images.githubusercontent.com/95450815/164895625-9522211b-2bcc-41d4-aac3-c839fe81d342.png">

**Comment by luzpaz** [comment]
Do you see this in LinkDaily as well?

**Comment by realthunder** [comment]
Can you please send me your user configuration file, `Tools -> Edit parameters -> Export`.

**Comment by ElPatoNoEsTu** [comment]
[user_config_file.zip](https://github.com/realthunder/FreeCAD_assembly3/files/8550449/user_config_file.zip)

**Comment by realthunder** [comment]
Can you please zip the following directory and post it here? Also please try [daily branch](https://github.com/realthunder/FreeCAD_assembly3/releases/download/0.11/FreeCAD-asm3-Daily-Win64-Py3-Qt5-20220407.7z) and see if works.

```
C:\Users\<your_username>\AppData\Local\Temp\FreeCADStartThumbnails
```

**Comment by ElPatoNoEsTu** [comment]
By the way - I also noticed a blank Start-Screen. 

[FreeCADStartThumbnails.zip](https://github.com/realthunder/FreeCAD_assembly3/files/8555786/FreeCADStartThumbnails.zip)
