### ISSUE TITLE
Message to install Command Line Developer Tools

### ISSUE THREAD

**Issue by cadmarx** [realthunder/FreeCAD_assembly3#1232]
Every time I open FreeCAD I get this message - to install command line developer tools. Screenshot attached. Should I install it? 
<img width="483" alt="Screen Shot 2022-05-14 at 12 31 31 AM" src="https://user-images.githubusercontent.com/92646037/168410805-38ff3fa1-e1c2-46cf-8e20-b9f0a336ae4e.png">

**Comment by luzpaz** [comment]
The [Addon Manager](https://wiki.freecad.org/AddonManager) uses `git` so it makes sense to do so.  All the addons you can install are on github in this repo: https://github.com/FreeCAD/FreeCAD-addons/
