### ISSUE TITLE
FreeCAD cannot access directories outside HOME

### ISSUE THREAD

**Issue by mjollnir14** [realthunder/FreeCAD_assembly3#1241]
Issue:
FreeCAD cannot access directories outside HOME

Not directly related to FreeCAD but to the current snap packaging

Workaround:
`sudo snap connect freecad-realthunder:removable-media`

Suggested solution:
Modify snap to allow usage of removable-media by default
https://askubuntu.com/a/964403

**Comment by luzpaz** [comment]
CC @ppd
