### ISSUE TITLE
openning externally linked assembly documents in a containg folder

### ISSUE THREAD

**Issue by bambukouk** [realthunder/FreeCAD_assembly3#1245]
In the past I could open any document in the folder of externally linked assemblies and all of them would open.

Now, for some reason? when I open sub_ass  document (externally linked to top level assembly document) only it opens and I have to open top level assembly document for all of them to open.

I have tested both with snap and appimage - same behaviour.
Is it an issue? or has something simply changed? 

```
OS: Ubuntu Core 20 (Pantheon/pantheon)
Word size of FreeCAD: 64-bit
Version: 2022.612.14555 (Git shallow)
Build type: Release
Branch: (HEAD detached at 2022.06.12-edge)
Hash: 74806743ec660ce5ad3351c163a7e51db8b717d2
Python version: 3.8.10
Qt version: 5.15.3
Coin version: 4.0.1
OCC version: 7.6.2
Locale: English/United Kingdom (en_GB)
```

```
OS: elementary OS 6.1 JÃ³lnir (Pantheon/pantheon)
Word size of FreeCAD: 64-bit
Version: 2022.430.26244 +4758 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: b024b876480a533018fdc702145e9e38f8c54ba6
Python version: 3.9.12
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United Kingdom (en_GB)
```
 an example of simple assembly demonstrating this issue:
[display_test.zip](https://github.com/realthunder/FreeCAD_assembly3/files/8907112/display_test.zip)

**Comment by realthunder** [comment]
App::Link is directional. A document that contains an App::Link that links to an object in the external document will open the external document together with the main document. It does not work the other way round, meaning that the sub-assembly file is not supposed to open the main document. Unless, you have a malformed document structure that contains dependency loop, e.g. both document contain a Link to each other.

**Comment by bambukouk** [comment]
Thank you for the explanation.
I will have to check why it was different sometime in the past :+1: 
(guess my error...)

**Comment by luzpaz** [comment]
@bambukouk where can we mention this in the documentation?
