### ISSUE TITLE
Missing advanced TechDraw tools

### ISSUE THREAD

**Issue by LukaszMajchrzyk** [realthunder/FreeCAD_assembly3#1255]
I'm using latest LinkDaily version (09072022) and advanced tools in TechDraw workbench (like hole table, ordinate dimensions etc) which have been recenty deployed in official branch are still missing. Is there any chance to add them to your branch? They are really mandatory in some cases.

**Comment by luzpaz** [comment]
Wrong place to post Link branch related ticket (per #1196)
You're looking for this https://github.com/realthunder/FreeCAD/issues/323
