### ISSUE TITLE
Additive helix deforms shapes

### ISSUE THREAD

**Issue by marcx95** [realthunder/FreeCAD_assembly3#1306]
![image](https://user-images.githubusercontent.com/28322892/233761119-0165a745-4a05-41da-88df-1211d5c980c4.png)
![image](https://user-images.githubusercontent.com/28322892/233761138-346ffb1e-28df-49b9-a4af-880ebc7c1530.png)
![image](https://user-images.githubusercontent.com/28322892/233761741-9155ed84-2177-4a7e-8d46-54727c72d2ce.png)
![image](https://user-images.githubusercontent.com/28322892/233761753-89f61213-f9a0-46a5-b342-f5770bc51064.png)
![image](https://user-images.githubusercontent.com/28322892/233762142-304c0ba5-2821-49a8-b6e2-c12c4f844461.png)

Hello comunity, thanks for making this greate software, I have solidworks background and I am learning FreeCAD now. I am trying to make an additive helix in part design workbench, It deforms the shape as I show in the images. These are the error messages:
 
23:29:05  0 <App> Document.cpp(4327): Failed to recompute Sin_nombre#Helix: gp_Dir() - input vector has zero norm
23:29:05  Recompute failed! Please check report view.
23:36:44  458.663 <App> Document.cpp(4327): Failed to recompute Sin_nombre1#Helix: gp_Dir() - input vector has zero norm
23:36:44  Recompute failed! Please check report view.
23:43:52  887.199 <App> Document.cpp(4327): Failed to recompute Sin_nombre1#Pocket: Null shape
23:43:52  Recompute failed! Please check report view.
23:44:01  896.398 <App> Document.cpp(4327): Failed to recompute Sin_nombre1#Pocket: Null shape
23:44:01  Recompute failed! Please check report view.
23:46:04  1018.35 <App> Document.cpp(4327): Failed to recompute Sin_nombre2#Helix: gp_Dir() - input vector has zero norm
23:46:04  Recompute failed! Please check report view.

I am using 2023.131 version in Windows 11.

**Comment by realthunder** [comment]
Welcome. This most likely a CAD kernel problem. Try to make the helix radius a bit smaller so that is firmly touches the base shape.

**Comment by marcx95** [comment]
thanks, It works!
