### ISSUE TITLE
Tab close impairs the workflow

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#136]
This is possibly a conflict between an "upstream feature" and "assembly3 requirement", stated here: https://forum.freecadweb.org/viewtopic.php?f=3&t=31085

When we close opened tabs which belongs to dependencies, the links to the dependencies are broken because closing tabs also closes the documents. 

Problems: 

1. There seems no easy way to re-open the dependencies. 
2. Why closing tabs also closes the document? I guess this behavior should be overridden by LinkStage3. 
3. Why do all the documents open in tabs **automatically**, which makes tabs unusable? Tabs are meant to be session-specific "bookmarks". If they are popped up unintentionally, the "feature" becomes useless.

**Comment by realthunder** [comment]
I have just implemented this feature. Please test it.

**Comment by ceremcem** [comment]
Thanks, I'm testing.
