### ISSUE TITLE
Shortcut proposal for fixing broken elements 

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#140]
Sometimes it's hard (or even impossible in terms of practicality) to give some name to an element if the object is not so important. I'm performing broken elements repairing (due to geometry or component change) in the following way: 

1. Clicking the broken element 
2. It's supposedly geometry is highlighted 
3. I can easily guess which geometry of new object will be linked to this element 
4. Memorize the selected element name (eg. `Element217`) (consider a **large/long** tree)
5. Click that geometry (eg. face of the rectangular prism) 
6. Hold the highlighted row in tree view, drag and drop on `Element217`

# Proposal 

This process might be much faster if we could: 

1. Click the broken link 
2. Guess the related geometry 
3. Hold Ctrl and click that geometry 
4. Click "Re-assign Element" button (or its shortcut)

# Advantages 

1. Much much much faster, easier and non-distracting than drag and drop in a *large* tree. 
2. More declarative way for newcomers.

**Comment by realthunder** [comment]
I have expanded the `Sync View` toolbar button, and exposed all tree view options through that button, including document mode, and drag command.

To fix a broken element,

1. Scroll to the broken element tree item
2. Guess the related geometry
3. Click treeview action button `Sync selection`, or with shortcut key `T, 2` to disable sync selection
4. Select the geometry
5.  Click treeview action button `Initiate dragging`, or with shortcut key `T, D` to initiate dragging, and drop the selection to the broken element
6. Optionally,  click treeview action button `Sync selection` or with shortcut key `T, 2` to re-enable sync selection
