### ISSUE TITLE
Adding translation infrastructure to Assembly3

### ISSUE THREAD

**Issue by luzpaz** [realthunder/FreeCAD_assembly3#142]
@realthunder is it too premature to implement the framework to have assembly3 translated to other languages? I'd be happy to help with this (as far as my technical know-how lets me)

Ref: https://forum.freecadweb.org/viewtopic.php?f=3&t=25180#p197884

**Comment by realthunder** [comment]
Maybe after the next release (hopefully early next month). I'll ask for your help then. Thanks in advance.

**Comment by luzpaz** [comment]
https://wiki.freecadweb.org/Translating_an_external_workbench
