### ISSUE TITLE
Issue on solving when count element are used

### ISSUE THREAD

**Issue by Nemesis81** [realthunder/FreeCAD_assembly3#145]
see forum thread about this issue.

it looks like it is not possible to solve the assembly constraints when constraints are apply to parts of the "elemenetcount" array after the use of multiply function.
element are "moved" 
not sur my explanation is clear... (sorry for my english) it's clearer in the file

file available there
https://forum.freecadweb.org/viewtopic.php?f=20&t=31324&p=260101#p260101

**Comment by luzpaz** [comment]
@Nemesis81 is this issue still valid. The forum thread is labeled `[Solved]`

**Comment by luzpaz** [comment]
confirmed by OP. closing
