### ISSUE TITLE
PointsOnCircle doesn't accept multiple points

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#150]
While evaluating [the issue on freecad forum](https://forum.freecadweb.org/viewtopic.php?f=20&t=32587&start=10#p272087) we came across with this problem: 

1. When more than two vertices clicked, "PointsOnCircle" grays out
2. The PointsOnCircle can't be used for cylinder surface and an edge. 

Do we miss something?

# Attachments 
[bar.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2642033/bar.zip)

**Comment by realthunder** [comment]
You need to first select a point (any element can be considered as a point, using its base coordinate), and then a circle. More points selection can be added later either during constraint creation time, or later through drag and drop into an existing constraint. 

In another word, the order of selection is important.

**Comment by ceremcem** [comment]
Selecting Point, Circle, Points... works. However, results differ between creating two "PointsOnCircle" constraints and one "PointsOnCircle" constraint with multiple points: 

# Multiple Points:

![points-on-circle-wrong](https://user-images.githubusercontent.com/6639874/49419090-72530a80-f796-11e8-89ee-df714b6d9080.gif)

# Two distinct constraints:

![points-on-circle-correct](https://user-images.githubusercontent.com/6639874/49419109-80089000-f796-11e8-86dd-7b352de6b8b1.gif)

**Comment by realthunder** [comment]
Nice catch. Fixed.

**Comment by ceremcem** [comment]
Bug hunting season open! :)
