### ISSUE TITLE
cannot lock assembly

### ISSUE THREAD

**Issue by J-Dunn** [realthunder/FreeCAD_assembly3#159]
In the collection of asm3 objects I uploaded here I am unable to lock the position of the drilled block assy. 
https://forum.freecadweb.org/viewtopic.php?f=20&t=32587&view=unread&sid=43e87ab990e40d082edd85711204fde1#p273131

I select "bearing-blk-assy" in the treeview and it shows up selected in green. The "lock" icon is enabled but when I click the icon it get an error box. The report panel shows the following:

```
70432.642483 <asm3.gui> constraint.py(670): constraint "Locked" command exception
Traceback (most recent call last):
  File "<string>", line 595, in report
  File "/svn/FreeCAD-LinkStage3/linkstage3_build/Ext/freecad/asm3/assembly.py", line 1902, in make
    constraints = sel.Assembly.Proxy.getConstraintGroup()
AttributeError: 'App.DocumentObject' object has no attribute 'Proxy'
```

**Comment by realthunder** [comment]
I have included more details on Lock constraint behavior in tooltip. Please check out.
