### ISSUE TITLE
feature request: Constraint toggle 

### ISSUE THREAD

**Issue by J-Dunn** [realthunder/FreeCAD_assembly3#162]
Hi , I just brought this up on the forum but this may be a better place since it amounts to a feature request. 

![scribble](https://user-images.githubusercontent.com/9969512/49783338-6c6aa580-fd11-11e8-9eed-b1f01ae264eb.png)

as you can see in a complex piece the red lines marking the constraints are preventing a clear view of the model. This is obviously important info but at some stage I need to see the model , not all the construction detail.  It would be nice to have a means to toggle visibility of the constraints so as to see the model  itself in cold, grey steel.

**Comment by J-Dunn** [comment]
It appears that the eyeball icon "auto element visibility" may hide this but I don't seem to be able to turn it back on again.

**Comment by realthunder** [comment]
Yes, the eyeball icon automates the visibility. When it is activated, you can use mouse hovering on the constraint icon in treeview to show the constraining element. When the mouse leaves, the element will be hidden. When the eyeball is deactivated, you can manually toggle the element visibility use treeview just like other shape, by using the `space` key.

![element-autovis](https://user-images.githubusercontent.com/1207888/49784174-55e73d00-fd57-11e8-87e6-5732c5f7038c.gif)

**Comment by J-Dunn** [comment]
Thanks but I think this is a bit different from element visibility.  It is the visiblility of the constraints ( red lines ) which I am trying to manage. 

The first time I hit they eyeball they disappear but I don't seem to be able to make them visible again without closing the program and restarting.  

Maybe that just me not knowing how to drive this yet, so maybe you can tell me if I'm missing a trick. 

thx

**Comment by realthunder** [comment]
When the eyeball is activated, it automatically hides all visible constraining elements. _However_, once the eyeball is deactivated, it _does not_ automatically reveal all constraining elements. The user have to manually go through the tree view and toggle the element visibility one by one. The rational is similar to what you have mentioned, that is, the user usually does not want to be shown _all_ constrain elements, just the one they needed.

**Comment by J-Dunn** [comment]
OK, I just found it odd there was not way to recover the initial situation other than closing FreeCAD. 

I guess that has most practical needs covered, so I'll close this. Thanks for explaining the logic.
