### ISSUE TITLE
elements breaking after rename.

### ISSUE THREAD

**Issue by J-Dunn** [realthunder/FreeCAD_assembly3#166]
Hi, I will have to try to reduce this to a simpler test case but I've noticed this a few times now. 

Remaning elements to meaningful names as suggested in some of the tutorials is a good idea, however, it seems that FreeCAD can lose its way as a result if changes are made which remove some elements. 

Here is the block which I've uploaded before. I wanted to change a rad constraint to a diameter on the sketch called mtg-face. I selected the rad from the side panel ( to avoid the crash issue ) and pressed delete. Instead of removing the rad, it removed the circle.  

OK, I thought cntl-z, but that threw an **array out of bounds** error and refused to undo the mess. I think at that stage I had to exit ( and it crashed ). After some fiddling I managed to reconstruct the sketch as I had it with two circles. But now there are half a dozen errors with a missing element. 
`
They all look like this with different Face elements on Body.Chamfer004.
<type 'exceptions.RuntimeError'>: cannot get geometry element from Body.Chamfer004.Face10`

Body.Chamfer004 has been lost internally but I seems to be the outer facets of the pad element. IIRC when I put the 1mm chamfer on one edge everything else started getting called a chamfer. A bit confusing and maybe that's a small bug in itself. 

Since all the holes are build on sketches on the various facets , I end up with a bunch of the broken refs. The object still show fine, it's just when recomputing that it throws errors. 

Is there a way to fix this and alleviate its confusion? 

OS: Linux
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16292 (Git)
Build type: Release
Branch: LinkStage3
Hash: e57f3461cb7a944a6d0cc4000dd72786d6813c62
Python version: 2.7.15
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedKingdom (en_GB)

[that is what I'm running now, I think the problem was created on build 16286]

[block45-3.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2697180/block45-3.zip)
rename as usual.

**Comment by J-Dunn** [comment]
In resume I see several likely bugs here. 

delete rad constraint seems to have deleted circle ( may be a false move on my part, but I don't think so). 
reverting this failed with index error. 
FreeCAD losing track of elements if they are renamed. 

I think the latter is due to using ordinal derived names instead of the user supplied names then expecting the default , ordinal names to be there after deleting an item. Rets get lost in an unrecoverable way.

**Comment by J-Dunn** [comment]
OK, I think I have a test case. 

Open this assy and go into sketch editor; select and delete left-hand circle ( which has a fillet in the 3d object ) .  This shows an error in the report window ( fair enough, we broke a ref ). Now cntl-z produce the array-bounds error. 

[array-bounds-bug.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2698531/array-bounds-bug.zip)

I have not found a way to fix this error condition on the part and the array bounds looks like a bug.

**Comment by J-Dunn** [comment]
```
Exception (Thu Dec 20 16:11:27 2018): Array out of bound: 5, 4 
In size_t App::ObjectIdentifier::Component::getIndex(size_t) const 
in src/App/ObjectIdentifier.cpp:595 
<PropertyLinks> PropertyLinks.cpp(347): array_bounds_bug_noasm#Chamfer.Base missing element reference array_bounds_bug_noasm#Pad ;#13;:U;XTR;:T502:3:E.Edge9
<PartDesign> FeatureDressUp.cpp(109): array_bounds_bug_noasm#Chamfer: invalid edge link ';#13;:U;XTR;:T502:3:E.Edge9'
Exception (Thu Dec 20 16:11:46 2018): Invalid edge link  
```
I have stripped out the asm3 wrapper. This file works on FreeCAD.

[array-bounds-bug-noasm.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2699382/array-bounds-bug-noasm.zip)

**Comment by realthunder** [comment]
Thanks for narrow it down. I got side tracked after checking out your demo file. I'll fix the problem soon.

**Comment by J-Dunn** [comment]
Thanks, I did git pull and make this morning it did seem to build one c++ file but I don't see any change to datastamp on src or changelog and when I run  I still get 16292.  The executable has yesterday''s date. Not today. 

Probably not doing the right thing. Can you help?

**Comment by realthunder** [comment]
I don't know, maybe `git pull` again? You can `git log` and compare the latest commit hash to [here](https://github.com/realthunder/FreeCAD/commits/LinkStage3).

**Comment by J-Dunn** [comment]
Oh well, I did a new git clone, a full rebuild and now I have 16294. Thanks.

**Comment by J-Dunn** [comment]
OK, I have managed to reconstruct the bearing block from an earlier version ( not able to recover file with broken refs ). 

I was also unable to use the previous assy file which relied on block45-2.fcstd, so I made another asm3 file, added the block and the bearing+spacer+axis assembly. I made two counts of the latter item. 

in asm3 workshop I was able to move the bearing assy but not rotate it. Orientation seems to be locked by something. I then tried to align the axis with one of the cylindrical holes in the block and CRASH. 
```

186.546338 <asm3.main> assembly.py(2863): solver exception when auto recompute Traceback (most recent call last):
  File "<string>", line 503, in _catch
  File "~/linkstage3_build/Ext/freecad/asm3/solver.py", line 400, in solve    return _solve(*args,**kargs)
  File "~/linkstage3_build/Ext/freecad/asm3/solver.py", line 370, in _solve    Solver(assembly,reportFailed,dragPart,recompute,rollback)
  File "~/linkstage3_build/Ext/freecad/asm3/solver.py", line 101, in __init__    objName(assembly),str(e)))
RuntimeError: Failed to solve "guide_block_assy2#Assembly(gude-block-assy-obj)": inconsistent constraints

Program received signal SIGSEGV, Segmentation fault.
#0  /lib64/libc.so.6(+0x385c0) [0x7fab61a915c0]
#1  0x7fab66e15150 in App::Transaction::getID() const from ~/linkstage3_build/lib/libFreeCADApp.so+0
#2  0x7fab66d263ab in App::Document::abortTransaction() from ~/linkstage3_build/lib/libFreeCADApp.so+0x4b
#3  0x7fab66eac7fd in App::Application::closeActiveTransaction(bool, int) from ~/linkstage3_build/lib/libFreeCADApp.so+0x5d
#4  0x7fab66d26425 in App::Document::abortTransaction() from ~/linkstage3_build/lib/libFreeCADApp.so+0xc5
#5  0x7fab66eac7fd in App::Application::closeActiveTransaction(bool, int) from ~/linkstage3_build/lib/libFreeCADApp.so+0x5d
#6  0x7fab66ec8c33 in App::Application::sCloseActiveTransaction(_object*, _object*) from ~/linkstage3_build/lib/libFreeCADApp.so+0x63
#7  /lib64/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8f3b) [0x7fab6682214b]
#8  /lib64/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x712) [0x7fab66822902]
#9  /lib64/libpython2.7.so.1.0(+0xab972) [0x7fab6675d972]
#10  /lib64/libpython2.7.so.1.0(PyObject_Call+0x47) [0x7fab66744aa7]
#11  /lib64/libpython2.7.so.1.0(+0x9e47e) [0x7fab6675047e]
#12  /lib64/libpython2.7.so.1.0(PyObject_Call+0x47) [0x7fab66744aa7]
#13  /lib64/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x47) [0x7fab66818cc7]
#14  0x7fab61f68b0b in PySide::SignalManager::callPythonMetaMethod(QMetaMethod const&, void**, _object*, bool) from /lib64/libpyside-python2.7.so.1.2+0x7b
#15  /lib64/libpyside-python2.7.so.1.2(+0x15d3f) [0x7fab61f6dd3f]
#16  0x7fab622ca839 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) from /lib64/libQtCore.so.4+0x369
#17  /usr/lib64/python2.7/site-packages/PySide/QtCore.so(+0x1b020b) [0x7fab503a920b]
#18  0x7fab622cf4d3 in QObject::event(QEvent*) from /lib64/libQtCore.so.4+0xb3
#19  /usr/lib64/python2.7/site-packages/PySide/QtCore.so(+0x1afdc3) [0x7fab503a8dc3]
#20  0x7fab628856c0 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib64/libQtGui.so.4+0x80
#21  0x7fab6288c122 in QApplication::notify(QObject*, QEvent*) from /lib64/libQtGui.so.4+0x1a2
#22  0x7fab674d22e8 in Gui::GUIApplication::notify(QObject*, QEvent*) from ~/linkstage3_build/lib/libFreeCADGui.so+0x68
#23  0x7fab622b636f in QCoreApplication::notifyInternal(QObject*, QEvent*) from /lib64/libQtCore.so.4+0x6f
#24  /lib64/libQtCore.so.4(+0x1eac08) [0x7fab622e6c08]
#25  /lib64/libQtCore.so.4(+0x1e7bcc) [0x7fab622e3bcc]
#26  /lib64/libglib-2.0.so.0(g_main_context_dispatch+0x15d) [0x7fab5ef3426d]
#27  /lib64/libglib-2.0.so.0(+0x4e638) [0x7fab5ef34638]
#28  /lib64/libglib-2.0.so.0(g_main_context_iteration+0x30) [0x7fab5ef346d0]
#29  0x7fab622e4589 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQtCore.so.4+0x79
#30  /lib64/libQtGui.so.4(+0x33b68b) [0x7fab6292868b]
#31  0x7fab622b4b23 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQtCore.so.4+0x43
#32  0x7fab622b4dfe in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQtCore.so.4+0x11e
#33  0x7fab622ba33e in QCoreApplication::exec() from /lib64/libQtCore.so.4+0x9e
#34  0x7fab6746d558 in Gui::Application::runApplication() from ~/linkstage3_build/lib/libFreeCADGui.so+0x1698
#35  ./FreeCAD(main+0x6fe) [0x404d8e]
#36  /lib64/libc.so.6(__libc_start_main+0xf3) [0x7fab61a7d413]
#37  ./FreeCAD(_start+0x2e) [0x40505e]

```

[guide-block2-crash-collection.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2704401/guide-block2-crash-collection.zip)
rename to *tar.gz

**Comment by J-Dunn** [comment]
![bearing-blk-mkii](https://user-images.githubusercontent.com/9969512/50365786-06cab480-056e-11e9-891b-331468669427.png)
Here's what I'm trying to model.

**Comment by realthunder** [comment]
> I then tried to align the axis with one of the cylindrical holes in the block and CRASH.

Can you recall what exactly have your done to cause the crash? Are you using the mover tool? If so, which mover?

**Comment by realthunder** [comment]
Here is a little tutorial using your block asm. In most cases, the first step after creating a new assembly is to choose a base part by locking. Since you are using PartDesign body, it is very important to carefully choose which geometry element to constrain. The rule of thumb is to choose a feature as early as possible so that it has less chance to be affected by later model changes. For locking a body, the most stable feature is the origin plane.
![block_asm1](https://user-images.githubusercontent.com/1207888/50368779-57bac700-05c7-11e9-9a40-7463d99fd7a5.gif)

Next we'll put the axis thing into the hole. Again, choosing the right geometry element is crucial. The earliest feature for hole is the sketch, and the earliest feature of the mating element is also a sketch of the washer body, which is the deepest part of the axis assembly. 

![block_asm2](https://user-images.githubusercontent.com/1207888/50368884-4d4cfd00-05c8-11e9-96b1-56614d51de97.gif)

You may probably noticed by now that the sketch is usually the first choice for constraining element. They have the most stable elements. Be careful when you editing a sketch, it has compounding effect to all features follow it.

**Comment by J-Dunn** [comment]
Thanks very much for the tuto. I had no trouble doing this with the previous assembly. But obviously an messy crash when I apply the axial alignment is a bit of a show stopper when trying to do this.

> > I then tried to align the axis with one of the cylindrical holes in the block and CRASH.
> 
> Can you recall what exactly have your done to cause the crash? Are you using the mover tool? If so, which mover?

I had used the mover tool to position the two axis assemblies as uploaded. That was fine except that it seemed that I could only move them in x,y,z ; not change the orientation. Are they locked to each other when I increase the "count" ?  I was sure that last time this tool enabled me to turn them in space. 

The crash occurred when I selected an axis surface and a hole inner surface and clicked the axial alignment tool. With the objects in the state I uploaded going straight to select these two surfaces should produce a crash as soon as you click the axial alignment tool. 

Just for reference, this was when using b 16294.

**Comment by J-Dunn** [comment]
OK, having locked the block by its XYplane and turned the axis assy using the axial move tool , I can do the axial alignment without problems. 

So what caused the crash? Either that the cylinders where nearly of may be exactly perpendicular leading to a dot product of zero which is possibly not tested and leads to a divide zero type error; or is it that nothing had a lock? 

In either case it indicates the need for some extra checking to prevent a crash if initial conditions are not right.

**Comment by J-Dunn** [comment]
Oops. More crashing. 

Having aligned the two axis assys to their respective holes ( but not entered them in ) , I wanted to back up to see which of the above changes was the cause of the earlier crash. I did _cntl-z_ and nothing happened. So after a second or two I clicked on _Edit_ to see whether _Undo_ was greyed out or whether I could do an undo op. from there. Before I got the edit menu, I got another crash. I think this was from my _cntl-z_ interaction.
```

Program received signal SIGSEGV, Segmentation fault.
#0  /lib64/libc.so.6(+0x385c0) [0x7f44c59585c0]
#1  0x7f44cacdc150 in App::Transaction::getID() const from ~/linkstage3_build/lib/libFreeCADApp.so+0
#2  0x7f44cabece2c in App::Document::undo(int) from ~/linkstage3_build/lib/libFreeCADApp.so+0x18c
#3  0x7f44cb365caa in Gui::Document::undo(int) from ~/linkstage3_build/lib/libFreeCADGui.so+0x4a
#4  0x7f44cb5e5e4d in Gui::View3DInventor::onMsg(char const*, char const**) from ~/linkstage3_build/lib/libFreeCADGui.so+0x6fd
#5  0x7f44cb3bfc0b in Gui::Command::invoke(int) from ~linkstage3_build/lib/libFreeCADGui.so+0x2fb
#6  0x7f44c6191b80 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) from /lib64/libQtCore.so.4+0x6b0
#7  0x7f44c67468b6 in QAction::triggered(bool) from /lib64/libQtGui.so.4+0x46
#8  0x7f44c6747c6f in QAction::activate(QAction::ActionEvent) from /lib64/libQtGui.so.4+0xbf
#9  0x7f44c6748194 in QAction::event(QEvent*) from /lib64/libQtGui.so.4+0xb4
#10  0x7f44c674c6c0 in QApplicationPrivate::notify_helper(QObject*, QEvent*) from /lib64/libQtGui.so.4+0x80
#11  0x7f44c6753122 in QApplication::notify(QObject*, QEvent*) from /lib64/libQtGui.so.4+0x1a2
#12  0x7f44cb3992e8 in Gui::GUIApplication::notify(QObject*, QEvent*) from ~/linkstage3_build/lib/libFreeCADGui.so+0x68
#13  0x7f44c617d36f in QCoreApplication::notifyInternal(QObject*, QEvent*) from /lib64/libQtCore.so.4+0x6f
#14  /lib64/libQtGui.so.4(+0x2ce789) [0x7f44c6782789]
#15  /lib64/libQtGui.so.4(+0x2ce99c) [0x7f44c678299c]
#16  0x7f44c6754bb4 in QApplication::notify(QObject*, QEvent*) from /lib64/libQtGui.so.4+0x1c34
#17  0x7f44cb3992e8 in Gui::GUIApplication::notify(QObject*, QEvent*) from ~/linkstage3_build/lib/libFreeCADGui.so+0x68
#18  0x7f44c617d36f in QCoreApplication::notifyInternal(QObject*, QEvent*) from /lib64/libQtCore.so.4+0x6f
#19  /lib64/libQtGui.so.4(+0x338c31) [0x7f44c67ecc31]
#20  /lib64/libQtGui.so.4(+0x338fb6) [0x7f44c67ecfb6]
#21  0x7f44c67c7e5f in QApplication::x11ProcessEvent(_XEvent*) from /lib64/libQtGui.so.4+0x9af
#22  /lib64/libQtGui.so.4(+0x33b4fe) [0x7f44c67ef4fe]
#23  /lib64/libglib-2.0.so.0(g_main_context_dispatch+0x15d) [0x7f44c2dfb26d]
#24  /lib64/libglib-2.0.so.0(+0x4e638) [0x7f44c2dfb638]
#25  /lib64/libglib-2.0.so.0(g_main_context_iteration+0x30) [0x7f44c2dfb6d0]
#26  0x7f44c61ab589 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQtCore.so.4+0x79
#27  /lib64/libQtGui.so.4(+0x33b68b) [0x7f44c67ef68b]
#28  0x7f44c617bb23 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQtCore.so.4+0x43
#29  0x7f44c617bdfe in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) from /lib64/libQtCore.so.4+0x11e
#30  0x7f44c618133e in QCoreApplication::exec() from /lib64/libQtCore.so.4+0x9e
#31  0x7f44cb334558 in Gui::Application::runApplication() from ~/linkstage3_build/lib/libFreeCADGui.so+0x1698
#32  ./FreeCAD(main+0x6fe) [0x404d8e]
#33  /lib64/libc.so.6(__libc_start_main+0xf3) [0x7f44c5944413]
#34  ./FreeCAD(_start+0x2e) [0x40505e]

```
