### ISSUE TITLE
Disabling scroll-to-change on numerical inputs 

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#170]
As a continuation of https://github.com/realthunder/FreeCAD_assembly3/issues/84, Path Workbench still needs this improvement: 

![scroll-to-change-issue](https://user-images.githubusercontent.com/6639874/50514839-eb9dfe80-0ab1-11e9-9915-bdfe7b47c108.gif)

```
OS: Debian GNU/Linux 9.5 (stretch)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16307 (Git)
Build type: Release
Branch: LinkStage3
Hash: 0f2d4bf2f756a6dfdce49581617d2187d5f0ed22
Python version: 2.7.13
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: English/UnitedStates (en_US)

```

**Comment by realthunder** [comment]
Path GUI is mostly done in Python. I am not sure if this can be fixed like the C++. I'll take a look when I got time.

**Comment by ceremcem** [comment]
Currently we have to click to the dialog first and only then scrolling works as normal. Resolved.
