### ISSUE TITLE
Spreadsheet: Circular dependency after insterting a row

### ISSUE THREAD

**Issue by yrabbit** [realthunder/FreeCAD_assembly3#171]
Branch LinkStage3 at 954c2e93e9d14f421b3731899a78d6ea67928d8e

After inserting a row, the formula below on page breaks.

[dims.ZIP](https://github.com/realthunder/FreeCAD_assembly3/files/2722601/dims.ZIP)
![spreadsheet](https://user-images.githubusercontent.com/6075465/50621283-99952700-0f50-11e9-8b57-a6263059a35f.gif)

**Comment by realthunder** [comment]
Thanks for reporting. Should be fixed now.
