### ISSUE TITLE
"demo" link is empty

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#174]
"See demo" isn't a link in 

```
Constraint element link now always link
```

section of the release note: https://github.com/realthunder/FreeCAD_assembly3/wiki/Release-Notes-0.9

**Comment by realthunder** [comment]
Really? It is working here. Maybe youtube has some delay when publish a video?

Try again maybe? https://youtu.be/uwPXDx-D4nY

What about other video links?

**Comment by ceremcem** [comment]
Ah, I got it now. I meant "`#1` is not a link" but you meant `#2` by saying `See demo`:

![image](https://user-images.githubusercontent.com/6639874/51473933-c9d12800-1d8e-11e9-8354-5125d211e2e9.png)
