### ISSUE TITLE
Techdraw page is "still touched after recompute"

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#182]
A simple Techdraw page is giving "still touched after recompute" error, which I think due to the subshape binder usage in the target part: 

![image](https://user-images.githubusercontent.com/6639874/51800248-9e8e8300-223d-11e9-96a1-be6447ddad07.png)

# Attachments 

[case-20190127T1410-still-touched-after-recompute.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2799973/case-20190127T1410-still-touched-after-recompute.zip)

**Comment by ceremcem** [comment]
I'm nearly certain that the desired target contains no cyclic dependency requirement theoretically. 

Here is what goes on currently: 
* PartA is constrained to PartB
* Independent parts of Bolt1, Bolt2, Bolt3, Bolt4  and a socket from PartB (PartB.Socket) is fused. 
* PartA is cut with Fuse to generate desired PartC

Everything seems logical.

**Comment by realthunder** [comment]
The cycle is caused by a bug in TechDraw. I'll fix it soon.

**Comment by realthunder** [comment]
The problem is fixed. However, for existing files, you'll have to fix it manually.

![peek 2019-01-29 21-18](https://user-images.githubusercontent.com/1207888/51910912-70f73480-240b-11e9-9119-acda40d1ab90.gif)

**Comment by ceremcem** [comment]
> you'll have to fix it manually

No problem. 

Works great, thanks!
