### ISSUE TITLE
How to create an Element from a bounding box face/edge/vertex?

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#190]
I need to create a constraint to make the pins (array of cylinders) perpendicular to the right edge (which is currently ~30°): 
![image](https://user-images.githubusercontent.com/6639874/51904449-bb5ac000-23cf-11e9-9d63-8f3068355136.png)

If I were able to create a `MultiParallel` constraint between the closest face of the PCB (according to the screenshot) and the largest face of bounding box of the pin array, everything would be set in one shot. 
 
# Current Approach

![image](https://user-images.githubusercontent.com/6639874/51905033-3f617780-23d1-11e9-8277-a2dfdf7eedfd.png)

**Comment by realthunder** [comment]
I am not entirely sure about your intention here. When you add an array directly to an assembly, each individual array element is treated as a separate part and can be constrained independently. If you want to constrain the entire array as a single part, just wrap it inside a sub-assembly, and add that into the assembly instead.

**Comment by ceremcem** [comment]
> If you want to constrain the entire array as a single part

Yes, that was the intention. However, I don't quite get how encapsulating the model inside an assembly container would help creating that simpler constraint. 

# Problem

The problem arises whenever a geometry (a model) has no suitable planar surface that you could create a constraint with. 

# Example 

Think that you have an ellipsoid which you want to create a constraint to make its longest cord line parallel to a some simple surface: 

![image](https://user-images.githubusercontent.com/6639874/52528053-e0f79b80-2ce4-11e9-923a-00c34fd2b9de.png)

If we could use the bounding box (the dashed virtual box) faces as if they were actual geometries, we could perform the task with some simple PointToPlaneDistance and MultiParallel constraints:

![image](https://user-images.githubusercontent.com/6639874/52528047-b7d70b00-2ce4-11e9-9f7f-1612d35dfc0e.png)

# Problem

**However**, the bounding box is a dynamic concept that we have almost no control over it. It would be changed unintentionally when some other geometry is added to the assembly. So please ignore the proposal.
