### ISSUE TITLE
Mass updating sub-shape binders

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#191]
According to `Fixing broken binder` section in [my notes](https://github.com/ceremcem/freecad-notes), we need to select the binder and the bound object, then click "Sub-shape binder" button to update the binder. 

The problem is that, in a large tree, it's very hard to find the bound object manually. Right-clicking the binder "Select bound object" doesn't work for me at the moment. Even if it worked correctly, it's still hard to check every binder in a large tree because there is no notification system available for the binders that are out of sync. 

Isn't it possible to have a utility that just updates all out-of-sync binders one by one while asking with "yes-no" prompt?

**Comment by ceremcem** [comment]
(Previous attempt: https://github.com/realthunder/FreeCAD_assembly3/issues/89)

**Comment by ceremcem** [comment]
@realthunder I think this is already implemented, right?

**Comment by realthunder** [comment]
Kind of, as the `SubShapeBinder` will be marked as error if it fails to get any bound object.
