### ISSUE TITLE
Problem with measurement constraints

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#195]
What is done: 

1. I drew the parts, assembled them. At the beginning, the wheels are on the outside of the bow-like-part. 
2. I replaced the elements with appropriate ones to get the wheels inside of bow-like-part. 

Here is erroneous file: [mechanical-20190213T0023-with-error.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2857716/mechanical-20190213T0023-with-error.zip)

![image](https://user-images.githubusercontent.com/6639874/52669079-4d151200-2f26-11e9-9f67-b54e2cc3e3d2.png)

**Comment by realthunder** [comment]
Bug fixed. Please sync asm3 repo, and manually recompute the measurement object.

**Comment by ceremcem** [comment]
Unfortunately I'm getting the same results. How can I provide any further debug information?

**Comment by realthunder** [comment]
Make sure your asm3 repo has the latest [commit](https://github.com/realthunder/FreeCAD_assembly3/commits/master). Then do manual recompute like below,

![measure-bug](https://user-images.githubusercontent.com/1207888/52762265-dd03aa80-3051-11e9-8bd2-b061810a3b92.gif)

**Comment by ceremcem** [comment]
OK, solved. The problem was that I had synced the repo already and did "Recompute object" but mistakenly I tried to recompute the whole assembly container and then recompute the Cylinder; not the "measurement object".
