### ISSUE TITLE
Link Array / Multiply is broken

### ISSUE THREAD

**Issue by CyberDeck** [realthunder/FreeCAD_assembly3#197]
If I follow your wiki example to create a link array it fails with

`Traceback (most recent call last):
  File "<string>", line 595, in report
  File "/tmp/.mount_FreeCA6ZT54o/usr/lib/freecad-daily/Ext/freecad/asm3/assembly.py", line 2124, in makeMultiply
    cstr.Multiply = True
AttributeError: Attribute (Name: Multiply) error: 'object of type 'NoneType' has no len()' 
`

Even by doing it manually (setting "multiply" to true in the constraint it fails basically with the same error). 
I am using the latest linux appimage FreeCAD-asm3-20190202-9a4632f4-4664316.glibc2.17-x86_64.AppImage

**Comment by realthunder** [comment]
Can you please attach a file showing the problem. Thanks

**Comment by luzpaz** [comment]
@realthunder can this ticket and #341 be closed?
