### ISSUE TITLE
Offset option for PointsOnCircle constraint

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#205]
It would be useful to have an optional offset option (zero by default, like PlaneAlignment constraint)  for bolt placement operations. 

Following image shows what can be achieved by using PointsOnCircle: 

![image](https://user-images.githubusercontent.com/6639874/54673616-a8c95100-4b0b-11e9-99e3-39c4ce2707e7.png)

Following image demonstrates the desired result: 

![image](https://user-images.githubusercontent.com/6639874/54673784-0cec1500-4b0c-11e9-9bfa-459bcc77ea26.png)

Problem is that the distance (shown with red arrow) varies according to the bolt's head's outer radius. In other words, this distance must be updated accordingly when the bolt size is changed. 

However, if we had an option to set the offset for PointsOnCircle, we could define a constant value across model that declares bolt-edge-to-cover-edge-distance.

**Comment by realthunder** [comment]
The `Offset` property in `PlaneAlignment` is obsolete. You can now have distance/angle offset on any constraint by moving the constraining element. If you change the `Offset` property of an element link under the constraint, then only that constraint is affected. If you change the `Offset` property of the linked element under the `Elements` group, than all constraints using that element will be affected.

**Comment by ceremcem** [comment]
Got it: 

![image](https://user-images.githubusercontent.com/6639874/55069854-04f51d80-5096-11e9-9365-da3bb1422da8.png)

This approach adds a little bit complexity but it sounds like a more filexible solution. 

Thanks.
