### ISSUE TITLE
"Discard" button is dangerous

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#207]
Discarding an expression in sketcher constraint is dangerous because it completely removes the expression without a way to undo or cancel: 

![discard-dangerous](https://user-images.githubusercontent.com/6639874/55083474-a3907700-50b4-11e9-876e-e67ebfeced8d.gif)

**Comment by ceremcem** [comment]
Nice! Thanks.

**Comment by ceremcem** [comment]
This issue repeats in current version: 

![Peek 2019-08-06 19-12](https://user-images.githubusercontent.com/6639874/62556784-4ab0c680-b87e-11e9-85f9-a422e3a7bcb7.gif)


# Version 
```
OS: Debian GNU/Linux 9.5 (stretch)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.18681 (Git)
Build type: Release
Branch: LinkStage3
Hash: 6a6302d761ee5db77d5f1042311a5663a42d7798
Python version: 2.7.13
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)
```

**Comment by realthunder** [comment]
It is not that dangerous, because you can undo it. I have just added a commit to auto undo it after canceling. I have added a few patches to improve the undo/redo system. Let know if you find any operation that cannot be undone.

**Comment by ceremcem** [comment]
That's true, I didn't try to undo after observing unexpected behavior of "Cancel" button. Anyway, current behavior is very user friendly. Thanks.
