### ISSUE TITLE
Documents can't survive from consecutive crashes

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#213]
# Reproduction 

1. Create a document
2. Make some trivial changes (v1)
3. Save
4. Make some more trivial changes (v2)
5. Enter an infinite loop in a spreadsheet cell (v3)
6. FreeCAD will start using 100% CPU and freeze. 
7. Kill and restart FreeCAD
8. See the autorecover window pops up
9. Answer as "Recover my document"
10. See the document is recovered at `v2` point, as expected. 
11. Enter an infinite loop again (to make FreeCAD freeze)
12. See FreeCAD freezes
13. Kill and restart FreeCAD
14. See no more document recovery is proposed.
15. See the opened document is at `v1` point.

# Expected 

In step 14, I would expect a document recovery popup as in step 8. When I answered as "Recover my document", it should recover the document at `v2` point, as in step 10.

**Comment by realthunder** [comment]
The bug should be fixed. Please test it with your described use case. I tested fine on my side.
