### ISSUE TITLE
Exporting mesh from assembly produces empty mesh

### ISSUE THREAD

**Issue by bgamari** [realthunder/FreeCAD_assembly3#223]
Exporting a mesh (e.g. an STL via `File -> Export`) from an Assembly or Parts group produces an empty mesh file.

# Reproduction

1. Enter the Part workbench
2. Create a new Part, add some geometry to it.
3. Enter the Assembly3 workbench.
4. Create a new Assembly
5. Drag the Part into the assembly
6. Select the Assembly and export it to a mesh file (e.g. STL) via `File -> Export`.
7. Open the STL file and note that it is empty.

**Comment by realthunder** [comment]
I'll add support for that soon. Meanwhile, you can work around this by setting the `BuildShape` property of the assembly to `Compound`, and then export will work.

**Comment by bgamari** [comment]
Ahh, great. Thanks @realthunder!

**Comment by luzpaz** [comment]
@realthunder was this implemented?

**Comment by realthunder** [comment]
Yes, it is implemented.
