### ISSUE TITLE
Failing to create element from linked document

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#230]
# Priority 

Blocker 

# Description 

I can't create element from a geometry of a linked document. 

# Screencast 

![failing-to-get-element-from-linked-doc](https://user-images.githubusercontent.com/6639874/56066804-9dbbb680-5d81-11e9-8866-a22c5048ff2d.gif)

# Version

```
OS: Debian GNU/Linux 9.5 (stretch)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.16536 (Git)
Build type: Release
Branch: LinkStage3
Hash: e9c60d4d8d72608fe897000c9658950419774b63
Python version: 2.7.13
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)
```

# Attachments

[test.zip](https://github.com/realthunder/FreeCAD_assembly3/files/3075213/test.zip)

**Comment by realthunder** [comment]
Oops! Another careless mistake on recent commits. Shame on me!

**Comment by realthunder** [comment]
You can fix the broken link by manually drag and drop the head_start element on to it.

**Comment by ceremcem** [comment]
Thanks! (We really need that test suite)

realthunder <notifications@github.com>, 13 Nis 2019 Cmt, 03:15 tarihinde
şunu yazdı:
