### ISSUE TITLE
Boolean operators fail to recompute if operands are not visible

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#242]
There is such an issue I came across from time to time, but I can't figure out how to reproduce. Please add a `pending clarification` label to this one and I'll provide more information as soon as possible.

**Comment by realthunder** [comment]
This is actually a feature. The assembly shape is determined by its parts visibility. Maybe in the future, I'll add another group under assembly to allow customizing shape composing.

**Comment by ceremcem** [comment]
I'm going to close this issue in favor of #243

**Comment by ceremcem** [comment]
(Well, I said I would close and I didn't? o_O)
