### ISSUE TITLE
Constraints become a blocked ones, but after reload they look normal.

### ISSUE THREAD

**Issue by yrabbit** [realthunder/FreeCAD_assembly3#244]
And there are some weird error messages about CS.
Branch: master Commit: 4ba221c5bbec43849240f9a496d679cedb051b69

[lock.zip](https://github.com/realthunder/FreeCAD_assembly3/files/3169856/lock.zip)
![lock](https://user-images.githubusercontent.com/6075465/57579563-84716b80-74e1-11e9-9c02-21a10525450f.gif)

**Comment by realthunder** [comment]
Fixed. Thanks for reporting
