### ISSUE TITLE
UI display issue with undo of move part when constrained

### ISSUE THREAD

**Issue by vectronic** [realthunder/FreeCAD_assembly3#248]
Hello, 

Firstly, love the work you're doing!

I wanted to report a UI issue which occurs as follows (on the Preview 0.10, 2019.06.08):

- Create two Parts
- Add a PlaneCoincident constraint
- Move one of the parts using purple translation arrows.
- Press (Cmd-Z) to undo the move
- The parts move back, but the part mover 'ball' doesn't (see screenshot).

When you then move the 'ball' again the parts 'jump' over to the current position of the ball.
![Screenshot 2019-06-10 at 13 27 29](https://user-images.githubusercontent.com/32313864/59195462-f4781d80-8b83-11e9-9d4e-ad4b853aa375.png)

**Comment by realthunder** [comment]
Thanks for reporting. It's been fixed. Please sync my LinkStage3 branch and try again.
