### ISSUE TITLE
getElementCircular and Base.Quantity 

### ISSUE THREAD

**Issue by yrabbit** [realthunder/FreeCAD_assembly3#251]
Hello, 
I think I messed up with a radius, but I can not figure out what.

[panel.zip](https://github.com/realthunder/FreeCAD_assembly3/files/3349793/panel.zip)
![fillet-radius](https://user-images.githubusercontent.com/6075465/60509407-25c1b480-9d10-11e9-9707-9cf441be2c55.png)

FreeCAD branch LinkStage3 at  2335fa74962e169592036e4ea8d23c1fccd1f7b9
assembly3 branch master at  c927d00b4d7080d868ddcf902b85a63ea5dcd5c6

**Comment by realthunder** [comment]
Thanks for reporting. You've discovered a serious problem. I'll fix it soon.

**Comment by yrabbit** [comment]
Thanks. Now all is OK with the radius:)
