### ISSUE TITLE
 'FeaturePython' object has no attribute 'Shape'

### ISSUE THREAD

**Issue by yrabbit** [realthunder/FreeCAD_assembly3#252]
Hello
I can not figure out what kind of shape is missing. Each of the parts separately does not give any error messages, it is only when I assemble them.
![some-shape](https://user-images.githubusercontent.com/6075465/60564545-6e767d80-9da3-11e9-8466-009ccdc63305.png)
[sw-board.zip](https://github.com/realthunder/FreeCAD_assembly3/files/3353343/sw-board.zip)

Freecad branch LinkStage3 at 48230867a5a41a5009835a5fbc40d1775de5aded
Assembly3 branch master at c927d00b4d7080d868ddcf902b85a63ea5dcd5c6

**Comment by realthunder** [comment]
Please sync asm3 repo for the fix.

**Comment by yrabbit** [comment]
Thanks. Now the whole project is loaded completely:)
