### ISSUE TITLE
Can not get geometry element when underlying sketch is modified

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#26]
# Problem

If I modify an underlying sketch, "Can not get geometry element ..." exception arises.

# Solution/workaround

1. Remove the related constraint
2. Re-apply the constraint

# Reproduction

1. Drawing is at [this point](https://github.com/ceremcem/fc-asm3-test/tree/489b46ebf6c5ad1584f1eaf4e1c1d0323d43df3b)
![image](https://user-images.githubusercontent.com/6639874/43884890-022db53e-9bc0-11e8-8972-d3b32f8f81d5.png)

2. Remove the small window from the sketch: 

![image](https://user-images.githubusercontent.com/6639874/43885015-5a3edeb0-9bc0-11e8-941d-94bd69524bcc.png)

3. `Can not get geometry element ...` exception arises: ([here is the drawing at that state](https://github.com/ceremcem/fc-asm3-test/tree/1ac5e057a92bd14119348d4fde3a981e580fcf3b))

![image](https://user-images.githubusercontent.com/6639874/43885081-91e98bb2-9bc0-11e8-866f-f99a39c46c60.png)

4. That element seem to be referenced from previous state: 

![image](https://user-images.githubusercontent.com/6639874/43885224-f1c49130-9bc0-11e8-978a-fa6d1beb043d.png)

**Comment by realthunder** [comment]
This is by design. Because you remove the window, and created another one, the face is consider a different one. To avoid this type of problem, when you use PartDesign body as part, you should choose shape in history as early as possible to avoid lost of element reference.

To fix the error here, select the new face (preferably from early body shape history), and drag and drop to the element in error.

**Comment by ceremcem** [comment]
Is that what you are suggesting:

![fix-element-reference](https://user-images.githubusercontent.com/6639874/43902761-9c906490-9bf3-11e8-9b90-4d1c93cbc5dc.gif)

**Comment by realthunder** [comment]
The face dragging is correct. But you don't need to delete that element. Just drop the face to that element can fix the problem. 

Another thing, I mentioned that to avoid similar problems from happening again, it is better to use early feature. It appears that sketch is the first feature in your body, in which case, you can use the origin plane that your sketch is attached to for constraining.

**Comment by ceremcem** [comment]
I'm slowly getting the hang of the internal working of the event: When we create a constraint between two "elements" and if we point to "that square face of the box", it gets the square face of the box. If we open a pocket in the box, then the face gets another id and naturally the link can not find appropriate face. 

Here we are assembling two objects: 

![image](https://user-images.githubusercontent.com/6639874/44623786-324fd200-a8e1-11e8-94b7-7e3ad35dcb5b.png)

When we create a pocket, the element link says it can not find `...Face6`:

![image](https://user-images.githubusercontent.com/6639874/44623797-8955a700-a8e1-11e8-89ba-f58508c11f5d.png)

Which means at the beginning, that face was enumerated as `Face6`.  To fix the matter, we click the face again, select the highlighted line in the treeview, drag and drop it on the broken element: 

![fix-broken-element](https://user-images.githubusercontent.com/6639874/44623819-06811c00-a8e2-11e8-9dff-8283ba9751e3.gif)

Okay, we are seeking for trouble, so remove the pocket:

![image](https://user-images.githubusercontent.com/6639874/44623828-2d3f5280-a8e2-11e8-8356-3175574059fe.png)

Now element says it can not find `...Face10`, because the windowed face was (apparently) enumerated as `Face10`. The enumeration is kind of deterministic, because when we fix this issue in the same way we did before and re-open the pocket, it can't again find `Face6`. 

But if we flip the gray part and perform the same operations, element link **won't be broken**, because that face is always enumerated *before* pocket faces, so its ID is always the same (like `Face4`). 

# Conclusion 

There is no reliable way to prevent this problem before it happens, because we might have to create two distinct constraints where one of them relies one side of the gray object and the other constraint relies on the other side of the gray object and then we might want to change the underlying sketch. 

# Proposal

If everything is true above, then I think the way to go is leaving already enumerated faces (and edges) intact and giving new IDs for new faces/edges.

**Comment by ceremcem** [comment]
Now I understand what you mean by "...it is better to use early feature.". I just used pocket feature and now I have actual history. 

Thanks!
