### ISSUE TITLE
Erroneous Element Location 

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#264]
Location of bolts and its related constraints' elements are not displayed at the same point: 

![image](https://user-images.githubusercontent.com/6639874/62684931-5dd0ad00-b9ca-11e9-962b-3c9c2a564e31.png)

# Version 

```
OS: Debian GNU/Linux 9.5 (stretch)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.18686 (Git)
Build type: Release
Branch: LinkStage3
Hash: d3a1d324d449c1b30720a7d16a325a046e58c86c
Python version: 2.7.13
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)
```

# Attachments 

Sent via FC forum DM.

**Comment by realthunder** [comment]
I didn't see the offset when opening your document. Can you repeat the steps, and capture a screenshot?

**Comment by ceremcem** [comment]
I couldn't reproduce the case in the above screenshot. However, replacing the constraints with a different type produced a similar result: https://youtu.be/y6rAuxlzfPY

**Comment by ceremcem** [comment]
Currently I can see no errors in the Report View but constraints are not being solved.

**Comment by ceremcem** [comment]
In the current project, solver is not working: 

![image](https://user-images.githubusercontent.com/6639874/62698869-e0676580-b9e6-11e9-9cec-3d54bdcf20e8.png)

# Attachments 

Sent via FC forum DM

**Comment by realthunder** [comment]
Haven't got time to check the solver problem yet, but the element position problem should be fixed

**Comment by ceremcem** [comment]
It seems that the solver problem is solved too. I'll open a separate issue if anything goes wrong. Thanks!
