### ISSUE TITLE
Can not delete the duplicate object

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#27]
In [this model](https://github.com/ceremcem/fc-asm3-cut-window/tree/415ac978d19e422954262936faf50c7aa5e6f8be), attempt to remove the somehow duplicated object causes deletion of the original: 

![image](https://user-images.githubusercontent.com/6639874/44006932-1df4e026-9e95-11e8-9efd-6604ea5b8613.png)

## Edit 
> Tracking [here](https://github.com/ceremcem/fc-asm3-cut-window/issues/1)

**Comment by maidenone** [comment]
`
Traceback (most recent call last):
  File "/home/maiden/projects/FreeCADLINK/build/Ext/freecad/asm3/assembly.py", line 353, in execute
    self.getElementSubname())
  File "/home/maiden/projects/FreeCADLINK/build/Ext/freecad/asm3/assembly.py", line 897, in getElementInfo
    part.Name,subname))
<type 'exceptions.RuntimeError'>: cannot get geometry element from Body001.Pad001.;#245;:G2#247;XTR;:T1736:4:F.Face2
Traceback (most recent call last):
  File "/home/maiden/projects/FreeCADLINK/build/Ext/freecad/asm3/assembly.py", line 353, in execute
    self.getElementSubname())
  File "/home/maiden/projects/FreeCADLINK/build/Ext/freecad/asm3/assembly.py", line 897, in getElementInfo
    part.Name,subname))
<type 'exceptions.RuntimeError'>: cannot get geometry element from Body001.Pad001.;#245;:G3#249;XTR;:T1736:4:F.Face3
`
![screenshot from 2018-08-14 14-39-18](https://user-images.githubusercontent.com/1190224/44092285-48c5b352-9fd0-11e8-9df4-fdb39f48e613.png)

**Comment by ceremcem** [comment]
Elements doesn't seem to be broken on my side:
![screenshot_2018-08-14_22-58-09](https://user-images.githubusercontent.com/6639874/44115049-8a3e1fb4-a015-11e8-80db-751e25008062.png)

Are we using the same commit?

**Comment by ceremcem** [comment]
This issue may or may not be related with asm3 workbench. I'm closing the issue because [I'm not able to reproduce](https://github.com/ceremcem/fc-asm3-cut-window/issues/1#issuecomment-412377408) it.
