### ISSUE TITLE
How to move a part in assembly without taking it out of surrounding assembly?

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#28]
I want to modify an assembly inside another one, but it doesn't work unless I take the assembly out of surrounding assembly container:

![movement-bug](https://user-images.githubusercontent.com/6639874/44007519-d9be11a6-9e9f-11e8-8951-e8007158b308.gif)

**Comment by realthunder** [comment]
Select the part you want to move as normal. Then hold the `CTRL` key, and select the assembly tree item you want move within. and finally hit the mover button.

**Comment by realthunder** [comment]
BTW, it is suggested to create each sub-assembly in its own file. Then if you want to modify the sub-assembly, just go to its file and do every operation as normal.

**Comment by ceremcem** [comment]
> Select the part you want to move as normal. Then hold the CTRL key, and select the assembly tree item you want move within. and finally hit the mover button.

Wow! That's apparently not a bug, but a feature! I loved it.
