### ISSUE TITLE
"Constraint Multiplication" fails with Pyhton3

### ISSUE THREAD

**Issue by numenic** [realthunder/FreeCAD_assembly3#284]
creating array of parts using "constraint multiplication fails on xrange() method.

changing `xrange()` -> 'range()'  in assembly.py solves the issue (keeping compatibility with Pyhton2).

changed are visible there: [https://github.com/numenic/FreeCAD_assembly3/tree/fixXrange](url)

![2020-02-04_09-31](https://user-images.githubusercontent.com/3399933/73727331-8cd59a80-4731-11ea-8ae4-5b9a1cfad659.png)

**Comment by realthunder** [comment]
Fixed. Thanks!
