### ISSUE TITLE
AppImage Crashing on opening 0.18 freecad files

### ISSUE THREAD

**Issue by anirudhnehra** [realthunder/FreeCAD_assembly3#294]
Hello,
I am trying to open designs created with 0.18 version of freecad. The software crashes on opening the files.
I attach a sample document. Interestingly, the file opens without issue in stable 0.19 release of freecad. Please suggest what to do.
[mono_final_2.FCStd.zip](https://github.com/realthunder/FreeCAD_assembly3/files/4746036/mono_final_2.FCStd.zip)

**Comment by realthunder** [comment]
Can you please attach the FreeCAD about information here? I just tried the Linux AppImage and Windows image. Both works fine.

**Comment by anirudhnehra** [comment]
Hi, where do I get freecad Info?
I use your latest AppImage release build 
FreeCAD-asm3-Conda-Py3-Qt5-20200509-glibc2.12-x86_64.AppImage

**Comment by realthunder** [comment]
Please try with the latest [release](https://github.com/realthunder/FreeCAD_assembly3/releases/tag/0.11). I update the image quite frequently.

The `About` information can be obtained at main menu -> Help -> About FreeCAD.

**Comment by anirudhnehra** [comment]
Thank you its working now.
