### ISSUE TITLE
Allow seeing through bottom of ground plane in shadow draw style

### ISSUE THREAD

**Issue by DevyHeavy** [realthunder/FreeCAD_assembly3#296]
Hello, I really like this fork of FreeCAD and have been using it in a few test projects. One problem that continues to hinder the experience of the shadow draw style is that it is not possible to see the bottom of parts through the ground plane.

The ground plane can be made transparent but that gets rid of the ground shadow.

In any case, I don't think just being able to see the shadow of whatever is above the ground plane is useful for anyone. An example of what I am talking about is below.
![Above](https://user-images.githubusercontent.com/28787282/84317259-7c4b8b80-ab3a-11ea-8d87-ce162b17207e.png)
![Below](https://user-images.githubusercontent.com/28787282/84317270-81a8d600-ab3a-11ea-9b9b-f61729829bce.png)

The second 'below' picture just shows the part's shadow. Seeing the part while under the ground would be more useful.

I suggest enabling back-face culling or at least set an option for that and maybe enable it by default.

INFO:
OS: Ubuntu 20.04 LTS (XFCE/xubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21300 +2331 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: accbbded5395cd9fd436a9511d6c7e81c70f7113
Python version: 3.7.6
Qt version: 5.12.1
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
Image updated. I have added GroundBackFaceCull parameter, which is enabled by default. BTW, the last image you downloaded has a bug that effect the ground transparency option. By right, when you set the ground to be completely transparent, it will hide the ground but still showing a semi-transparent shadow on the ground.

**Comment by DevyHeavy** [comment]
Tested new image and it works. Thanks realthunder.

Closing issue.
