### ISSUE TITLE
Part design: "BaseFeature link is not set" when creating body from existing shape

### ISSUE THREAD

**Issue by DevyHeavy** [realthunder/FreeCAD_assembly3#297]
Attached is a video/animation showing the process to recreate the bug referenced in the title of this issue.

![ezgif-3-bdafc7339ba4](https://user-images.githubusercontent.com/28787282/84483867-ef065500-ac67-11ea-8655-8bd7015ed687.gif)

This error occurs for any shape I try. Either from creating it from Part, importing from STEP file, or even making another PartDesign body from another PartDesign shape. 

INFO:
OS: Ubuntu 20.04 LTS (XFCE/xubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21300 +2345 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: 095c5168a5a4767aa673293efe3df4b0347f37ae
Python version: 3.7.6
Qt version: 5.12.1
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
Thanks for reporting. As a temporary fix. You can manually set the `BaseFeature` property for the `BaseFeature` object.
