### ISSUE TITLE
Cosmetic objects not inserted into TechDraw sheet

### ISSUE THREAD

**Issue by DevyHeavy** [realthunder/FreeCAD_assembly3#303]
In the latest version of official FreeCAD cosmetic objects like midpoint vertices, midpoint lines on faces, etc, work in the TechDraw workbench. However, in the latest assembly3 build no cosmetic objects are able to be inserted into TechDraw sheets/views.

I have not tested earlier versions of this fork and tested for this issue.

**INFO**
OS: Ubuntu 20.04 LTS (XFCE/xubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21300 +2367 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: daf93f78cc3809ec0b63f8da8ee9002750f5f169
Python version: 3.7.6
Qt version: 5.12.1
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
Thanks for reporting. It's fixed. Before the new release, a temporary work around is to right click the view item in the tree view and select `Recompute object` to see the newly created cosmetic object.
