### ISSUE TITLE
Editing a Sketch Breaks Constraints

### ISSUE THREAD

**Issue by BassMatiFreecad** [realthunder/FreeCAD_assembly3#311]
I added a name to a previously unnamed (and unused) constraint in a sketch. After closing the sketch, references to (previously existing) constraints in that sketch are broken - the sketch name disappears in the affected expressions. This can cause lots of work to recover the document.

Other changes, like renaming a constraint or changing the geometry also seem to trigger the problem. Interestingly, the constraint name has been correctly renamed in expressions, just the Sketch name (<<label>> or internal name) is lost.

![2020-07-17 001](https://user-images.githubusercontent.com/57710630/87767195-9142cb00-c81a-11ea-9821-a0e9a6222853.png)

Worse: The affected elements are not flagged with an error indicator in the Model Tree. To reveal them, mark the document for re-computation and refresh (worked in previous releases for sure). Additionally: Close and re-open the document, inspect the report view for errors.  

Its difficult to say when the effect appears, but after a while (hard to say when) the document becomes "brittle". 

Workaround: Use Binders wherever possible instead of formulas to mitigate the effect.

Appeared in all previous releases.

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21300 +2418 (Git)
Build type: Release
Branch: LinkStage3
Hash: 1bf376e6abb6824991a2f8f6da1f7eefd1df9ce4
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
Just released a new update. Not sure if covers all problems you stated here. Please check.
