### ISSUE TITLE
VirtualGL friendly AppImage?

### ISSUE THREAD

**Issue by yrabbit** [realthunder/FreeCAD_assembly3#314]
I am using FreeCAD, which runs on another powerful machine and uses all the GPU acceleration mechanisms using VirtualGL. However, to do this, I have to unpack AppImage and make one tiny fix to the AppRun file:
`export LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH`

Is it worth to make it standard?

**Comment by realthunder** [comment]
Yes, I'll do that in next release.

**Comment by yrabbit** [comment]
Thank you! :)
