### ISSUE TITLE
unable to view assembly strucure/components during step import

### ISSUE THREAD

**Issue by anirudhnehra** [realthunder/FreeCAD_assembly3#318]
Hi,
I cant seem to see all the parts that make up step file during its import. What to do?

Thanks
![no_tree](https://user-images.githubusercontent.com/42260300/93668249-e0baa700-faa8-11ea-878b-a8cc2260d49f.png)

**Comment by realthunder** [comment]
First, make sure you switch to `Part` workbench at least once. Then go to Preference -> Import/Export, and do the following settings. The most important one is to **NOT** enable STEP compound merge. Also note that, not all STEP contains assembly.

![Screenshot from 2020-09-19 21-34-17](https://user-images.githubusercontent.com/1207888/93668649-55e5a680-fac0-11ea-8adc-30520ae4bcc8.png)

**Comment by anirudhnehra** [comment]
Thank you, Working good after unchecking compound merge option.

Regards 
Anirudh
