### ISSUE TITLE
appimage has not been updated for more than a month.

### ISSUE THREAD

**Issue by tiket18** [realthunder/FreeCAD_assembly3#319]
During this time, something useful always happens in the main branch. Please make a new build further and preferably at least once every two weeks. I'm especially worried about the path workbench, which is developed only in the main branch.

**Comment by FlailAway** [comment]
Seriously? Such ingratitude, not even thanking the Dev for spending the 1000s of hours spent building this Branch.

Why not learn C++ and Python and help with it.

Just when I thought I had seen it all in life, I see this shameful request.

**Comment by tiket18** [comment]
Не могу себе представить, что в моем сообщении могло быть воспринято как повод для обиды. Единственная версия - дефект перевода, языковой барьер. Увы, я использую depl.com.
I can't imagine that my message could have been taken as a reason for offence. The only version is a translation defect, a language barrier. Alas, I use depl.com.

**Comment by ceremcem** [comment]
@tiket18 There is nothing wrong with your comment. Anyone might also get frustrated because of a problem while trying to get a job done, that's even okay.

**Comment by ceremcem** [comment]
Regarding to the title, this issue is resolved and should be closed.
