### ISSUE TITLE
Can not change/delete sketch constraint

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#32]
### Problem 

Can not change height of the enclosure (currently 77.44mm)

![image](https://user-images.githubusercontent.com/6639874/44309164-01e0d300-a3cb-11e8-9127-afd3cac23265.png)

### Reproduction 

1. Drawing is [here](https://github.com/ceremcem/fc-asm3-test/blob/ec0d43f25cd6065a38d7f8897faa167039d688a6/assembly.fcstd)

2. Navigate to the panel/pad/sketch

3. Try to delete the `|--| 77.44mm` constraint

4. Exception arises as `Property not found`

**Comment by realthunder** [comment]
This an upstream bug. I have submitted a [PR](https://github.com/FreeCAD/FreeCAD/pull/1619). I'll include the fix in my next release.

**Comment by ceremcem** [comment]
Confirm fixed since https://github.com/realthunder/FreeCAD_assembly3/releases/tag/0.8.5
