### ISSUE TITLE
External Reference or ShapeBinder External Geometry

### ISSUE THREAD

**Issue by DaAwesomeP** [realthunder/FreeCAD_assembly3#320]
Hello!

It does not yet seem possible to transfer, reference, or bind geometry from parts in different files onto each other.

One use-case for this is an object with mounting holes. You might constrain the object to fit next to your part, and then you want to cut out matching holes from your part.

Here is an example:
![trace2](https://user-images.githubusercontent.com/4472083/94345086-801ff280-fff1-11ea-8bee-874c2dddf06c.png)

I have tried:

 - Shapebinding
 - Creating an external reference circle in the part sketch
 - Copying the sketch with the mounting holes using the "Copy Geometry of other sketch" tool

Nearly all of these tools say, "this object is in another document" and don't work.

Or maybe there is a way to do this and I don't know what it is. The holes don't necessarily need to be permanently linked/referenced, so any way to copy the geometry would work in this situation.

Relevant forum post: https://forum.freecadweb.org/viewtopic.php?f=20&t=50541

**Comment by ceremcem** [comment]
Waiting user response due to https://forum.freecadweb.org/viewtopic.php?f=20&t=50541#p434444

**Comment by luzpaz** [comment]
@DaAwesomeP ping

**Comment by luzpaz** [comment]
Closing ticket as no response from @DaAwesomeP
