### ISSUE TITLE
No support of knot operation

### ISSUE THREAD

**Issue by schmimat** [realthunder/FreeCAD_assembly3#321]
Hello,

thanks for the greate work you do for FreeCAD.

While testing your latest build _FreeCAD-asm3-Win64-Py3-Qt5-20200818_

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21911 +2545 (Git)
Build type: Release
Branch: LinkStage3
Hash: 04c80c99eee0f7d2f761bdc7d8b32c077adefdec
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Germany (de_DE)

I ran into a problem while changing the multiplicity of B-Splines.

"This version of OCE/OCC does not support knot operation. You need 6.9.0 or higher."

![2020-10-01 09_37_47-FreeCAD 0 19](https://user-images.githubusercontent.com/14329731/94781216-d0200000-03c9-11eb-886f-9c5e706722a6.png)

Best regards 

mfG Matthias

**Comment by realthunder** [comment]
Should be fixed now. Thanks for reporting
