### ISSUE TITLE
Shadow & transparency not appearing correclty

### ISSUE THREAD

**Issue by jaisekjames** [realthunder/FreeCAD_assembly3#322]
My shadow look like this
![Shadow](https://user-images.githubusercontent.com/44542605/95954824-8992c280-0e19-11eb-981c-bf6708e87707.png)

My dock window become transparent. But object also become transparent. See three cubes are there. If select cube, it will appear [cubes same as top image]. 
![Dock transparancy](https://user-images.githubusercontent.com/44542605/95954963-c19a0580-0e19-11eb-87bb-12de767b363e.png)

Freecad:
OS: Manjaro Linux (GNOME/gnome)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2020.10.13.14555 (Git shallow) AppImage
Build type: Release
Branch: (HEAD detached at FETCH_HEAD)
Hash: bb9ae8c4442badbfeb5ad4e13908472287604c7d
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/India (en_IN)

Graphics - ATI RV515

**Comment by realthunder** [comment]
It's most likely a graphics driver issue. Any chance to update your graphics driver? Also, please try spot light in shadow. Is everything fine outside of shadow display mode?

**Comment by jaisekjames** [comment]
Thank for quick responds. may be graphics driver issue. Graphics driver come with default linux driver set. It is an old card  ATI Mobility Radeon X2300 [Compaq 6910p]. Is there any OpenGL min version requirement for this to work?

**Comment by realthunder** [comment]
Not sure about the min version. I did get some complains about ATI cards. Maybe you can try update your driver and see.

**Comment by luzpaz** [comment]
@jaisekjames any progress ?

**Comment by jaisekjames** [comment]
I am using manjaro Linux with gnome. & It is not possible to update driver since only available driver is come with Linux default one. I will close this issue.

**Comment by luzpaz** [comment]
bummer
