### ISSUE TITLE
Copy of Part Design Body creates a stray feature reference

### ISSUE THREAD

**Issue by BassMatiFreecad** [realthunder/FreeCAD_assembly3#326]
I'm sorry to bog again, but I'm pretty sure that this worked before:

I created a copy of a Body with a Pad feature (either via copy & paste, or with menu Edit > Duplicate selected. In the element selection dialog, I did not have to deselect anything, because the document has only this one single Body. The result is a new Body001 with a Pad001 and a Sketch001, which is fine so far. But the original Body has now two features, Pad and Pad001, where Pad001 seems to be incorrect. Both instances of Pad001 seem to reference the same object in memory, because they have the same internal name, and if I delete one, both are gone in the model tree.

![fig-001](https://user-images.githubusercontent.com/57710630/96588052-6e292b00-12e3-11eb-8ea1-780b1df4d5aa.png)

Attachment: Project files (copy-of-body.zip), before & after.
[copy-of-body.zip](https://github.com/realthunder/FreeCAD_assembly3/files/5408766/copy-of-body.zip)

Best Regards
Ulrich

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2020.10.19.22739 +2669 (Git)
Build type: Release
Branch: LinkStage3
Hash: 413465d933e94061fb29486f3a322220e2604492
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/United States (en_US)

**Comment by luzpaz** [comment]
@BassMatiFreecad please retest on latest Daily build

**Comment by Shkolik** [comment]
Tested on:

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.614.24301 +3747 (Git)
Build type: Release
Branch: LinkDaily
Hash: ecbfba008c481db4cb17bf8bd514b2d12690a8e5
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

![image](https://user-images.githubusercontent.com/26121979/125526007-d851e727-ed13-40de-999a-2afaad548589.png)

Looks like everything works as expected.

**Comment by luzpaz** [comment]
Thanks. Closing ticket
