### ISSUE TITLE
error in asm3 but not in upstream freecad

### ISSUE THREAD

**Issue by anirudhnehra** [realthunder/FreeCAD_assembly3#331]
Hi, 
this file works well in stable and dev upstream but has problems with asm3 appimage. It shows error whenever i open in your branch.
Pls see whats wrong.

Regards
Anirudh
[block.zip](https://github.com/realthunder/FreeCAD_assembly3/files/5462201/block.zip)

**Comment by realthunder** [comment]
Fixed. I'll make release soon. Thanks for reporting.
