### ISSUE TITLE
Multi transform 

### ISSUE THREAD

**Issue by macdroid53** [realthunder/FreeCAD_assembly3#333]
Just attempted a multi transform in the 10.26 appimage and if one feature is selected it says select only one.

If none is selected it crashes.

[BasePlate.zip](https://github.com/realthunder/FreeCAD_assembly3/files/5469597/BasePlate.zip)

renamed FCStd to zip to attach here

**Comment by realthunder** [comment]
Should be fixed now. I'll make a new release soon. Thanks for reporting.
