### ISSUE TITLE
Sub-object(s) shape binder - Failed to obtain shape

### ISSUE THREAD

**Issue by Rabbit-sk** [realthunder/FreeCAD_assembly3#337]
Dear Realthunder, 

Today I tried your branch of FreeCAD for first time, because of solved topo naming problem, which is great timesaver. Thank you for that! I use sub-object(s) shape binders a lot. Please look at this error. It does not occur in official pre-release version. 

Best regards
Ján

How to recreate issue:
1. Open FreeCAD
2. Create new document
3. Switch to the Part workbench
4. Create new body and make it active
5. In that body create sketch containning rectangle
6. Create another body and make it active
6. Select all edges of rectangle
7. Create a sub-object(s) shape binder
8. "Failed to obtain shape" error shows up

![obrázok](https://user-images.githubusercontent.com/74265320/98724843-9a8d1000-2394-11eb-9a95-b695fdf87dab.png)

19:29:28  <Exception> FreeCAD Exception
19:29:28  <PartDesign> ShapeBinder.cpp(604): Nepomenovan__#Binder failed to obtain shape from Nepomenovan__#Body.Sketch.;g1;SKT.Edge1
19:29:28  <Exception> FreeCAD Exception
19:29:28  <PartDesign> ShapeBinder.cpp(604): Nepomenovan__#Binder failed to obtain shape from Nepomenovan__#Body.Sketch.;g2;SKT.Edge2
19:29:28  <Exception> FreeCAD Exception
19:29:28  <PartDesign> ShapeBinder.cpp(604): Nepomenovan__#Binder failed to obtain shape from Nepomenovan__#Body.Sketch.;g3;SKT.Edge3
19:29:28  <Exception> FreeCAD Exception
19:29:28  <PartDesign> ShapeBinder.cpp(604): Nepomenovan__#Binder failed to obtain shape from Nepomenovan__#Body.Sketch.;g4;SKT.Edge4
19:29:28  <Exception> FreeCAD Exception
19:29:28  <PartDesign> ShapeBinder.cpp(604): Nepomenovan__#Binder failed to obtain shape from Nepomenovan__#Body.Sketch.;g1;SKT.Edge1
19:29:28  <Exception> FreeCAD Exception
19:29:28  <PartDesign> ShapeBinder.cpp(604): Nepomenovan__#Binder failed to obtain shape from Nepomenovan__#Body.Sketch.;g2;SKT.Edge2
19:29:28  <Exception> FreeCAD Exception
19:29:28  <PartDesign> ShapeBinder.cpp(604): Nepomenovan__#Binder failed to obtain shape from Nepomenovan__#Body.Sketch.;g3;SKT.Edge3
19:29:28  <Exception> FreeCAD Exception
19:29:28  <PartDesign> ShapeBinder.cpp(604): Nepomenovan__#Binder failed to obtain shape from Nepomenovan__#Body.Sketch.;g4;SKT.Edge4
19:29:28  <Exception> ShapeBinder.cpp(632): Failed to obtain shape Nepomenovan__#Body.Sketch.Edge1
19:29:28  <Exception> ShapeBinder.cpp(632): Failed to obtain shape Nepomenovan__#Body.Sketch.Edge1

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2020.11.09.22739 +2743 (Git)
Build type: Release
Branch: LinkStage3
Hash: d34d2bd0674dfd55549f4a051c746564a850474b
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: Slovak/Slovakia (sk_SK)

**Comment by realthunder** [comment]
Thanks for reporting. I'll make a new release soon.
