### ISSUE TITLE
 Constraint multiplication error

### ISSUE THREAD

**Issue by lilaL** [realthunder/FreeCAD_assembly3#341]
I'm trying to multiply a constrain and get the following message:
```
Traceback (most recent call last):
  File "/tmp/.mount_FreeCAWMgmw7/usr/Mod/asm3/freecad/asm3/assembly.py", line 2433, in execute
    self.checkMultiply()
  File "/tmp/.mount_FreeCAWMgmw7/usr/Mod/asm3/freecad/asm3/assembly.py", line 2321, in checkMultiply
    pos0 = info0.Placement.multVec(
<class 'AttributeError'>: 'NoneType' object has no attribute 'Placement'
```
![image](https://user-images.githubusercontent.com/12436228/99158258-3d18fc00-26d1-11eb-9fa1-987288755faa.png)

You find the project file [here](https://office.deltaempower.org/s/qQE5b6PYakMk5zk). It's in the `SubAssembly.WindVane`, you see the important elements in the following screenshot:
![image](https://user-images.githubusercontent.com/12436228/99158372-59696880-26d2-11eb-880b-e92fd1f121cc.png)

I wonder if it's also related to #197 ?

OS: Manjaro Linux (GNOME/gnome)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.21911 +2545 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: 04c80c99eee0f7d2f761bdc7d8b32c077adefdec
Python version: 3.7.8
Qt version: 5.12.1
Coin version: 4.0.0
OCC version: 7.4.0

**Comment by realthunder** [comment]
I have just made a new release containing some fix of the problem in this and the other issue you reported. Not sure if it is a complete fix, so I didn't close the issues yet. Multiplication requires the base part (i.e. the non-multiplied part) to be unfreezed. The multiplied part can be frozen. My fix now have proper error message if you try to do it with frozen base part. 

BTW, one of your holes in the base has a unique radius. Multiplication can only auto expand to circular edges of equal radius. You can of course drag in more circular edges to the constraint for manual expansion.

![Screenshot from 2020-11-17 07-36-54](https://user-images.githubusercontent.com/1207888/99321370-a010bb80-28a8-11eb-89f5-b8fba34650cd.png)

**Comment by lilaL** [comment]
Thanks for fixing it!
And yeah I forgot to set the proper radius!
