### ISSUE TITLE
loss of thread size after closing and reopening the file

### ISSUE THREAD

**Issue by Grubuntu** [realthunder/FreeCAD_assembly3#345]
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2020.11.16.22739 +2766 (Git)
Build type: Release
Branch: LinkStage3
Hash: 6730ad3b3bd841c2745ec98bf953c523dea86913
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: French/France (fr_FR)

Hello 

When I create threaded holes in Part Design (ISOmetric thread) the value of thread size still return at M1.6 after saving , closing and reopening the file.

Before closing the file 👍 
![Avant](https://user-images.githubusercontent.com/56045316/99654591-d7bf6500-2a5a-11eb-9c5f-dfd21f4a830d.JPG)

After reopening the file
![Après](https://user-images.githubusercontent.com/56045316/99654091-23bdda00-2a5a-11eb-9341-abce1488350b.JPG)

[test.zip](https://github.com/realthunder/FreeCAD_assembly3/files/5566094/test.zip)

When the part is recalculated, the holes will appear with size M1.6 instead of the original size selected.

**Comment by realthunder** [comment]
I've done a merge with upstream. The problem seems fixed already. Please check.

**Comment by Grubuntu** [comment]
Thank you realthunder, its solved.
