### ISSUE TITLE
Cyclic Dependency exception while creating sub-shape binder

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#35]
When I'm trying to follow the [Part Workbench section of Modeling using Assembly](https://github.com/realthunder/FreeCAD_assembly3/wiki/Modeling-using-Assembly#using-part-workbench) tutorial, I'm getting "Cyclic dependency" exception while creating the sub-shape binder: 

![cyclic-dependency](https://user-images.githubusercontent.com/6639874/44831916-3b1e0c00-ac31-11e8-89ba-79a00fc2a3d4.gif)

Here is the model I've created: [test.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2334743/test.zip)

**Comment by ceremcem** [comment]
I *think* this is because the sub-shape binder wants to go under the first `Body` part, in this case, this is `socketpart.Body` and if `Assembly.Parts` keeps everything as a feature list/history list (I might
 name this wrongly), then as the sub-shape binder is tried to be created under a previous part in the history, it may perfectly throw a cyclic dependency exception: 

![cyclic-dependency-workaround](https://user-images.githubusercontent.com/6639874/44833949-4de80f00-ac38-11e8-991f-1191c134c06c.gif)

**Comment by realthunder** [comment]
This is a bug. I'll fix it soon.

**Comment by realthunder** [comment]
New version released, please check.

**Comment by ceremcem** [comment]
Works like a charm! Thanks!
