### ISSUE TITLE
daily release is not present

### ISSUE THREAD

**Issue by snelweg** [realthunder/FreeCAD_assembly3#355]
https://github.com/realthunder/FreeCAD_assembly3/releases/tag/0.11 
There are no new release since 18 november, they did exist though.

(thanks for your efforts in making FC such a good tool!)

**Comment by realthunder** [comment]
You're welcome. The 11.28 release is pull out because I found a problem. I thought I it would be a quick fix, but not really. I have just uploaded 11.29 release.
