### ISSUE TITLE
One edge from a sketch is not highlighted after selection

### ISSUE THREAD

**Issue by Rabbit-sk** [realthunder/FreeCAD_assembly3#365]
Dear Realthunder,

There is allways one edge in a sketch, which is not higlighted after selecting it with mouse or with function "Pick geometries G, G" -> "Wire". I highlighted the particular edges in Python console:

![obrázok](https://user-images.githubusercontent.com/74265320/101018124-5643f880-356b-11eb-861b-01c00dc9cc90.png)
![obrázok](https://user-images.githubusercontent.com/74265320/101018143-5cd27000-356b-11eb-8174-47d6a945f1a9.png)

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2020.12.02.23076 +2874 (Git)
Build type: Release
Branch: LinkStage3
Hash: f45215c049a756a8d5f072535eafbb308113f2b1
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: Slovak/Slovakia (sk_SK)

Regards

**Comment by realthunder** [comment]
This problem has been fixed https://github.com/realthunder/FreeCAD/commit/55073409dea8cb380db190fe906b5c3a28c44b07

I'll make a new release soon.

**Comment by Rabbit-sk** [comment]
Later I find that also "Pick geometries G, G" -> "Wire" have the same outcome:
![obrázok](https://user-images.githubusercontent.com/74265320/101026941-cb1d2f80-3577-11eb-9ee9-519314032791.png)
![obrázok](https://user-images.githubusercontent.com/74265320/101027113-028bdc00-3578-11eb-86d1-7920d19f063f.png)

**Comment by Rabbit-sk** [comment]
> This problem has been fixed realthunder/FreeCAD@5507340
Thanks
