### ISSUE TITLE
Big Sur start fails but it worked in x.11.2020 daily releases

### ISSUE THREAD

**Issue by sigxcpu76** [realthunder/FreeCAD_assembly3#368]
I know that FreeCAD needs to be recompiled (https://forum.freecadweb.org/viewtopic.php?f=4&t=51345&start=40) for Big Sur, otherwise it doesn't start.
The funny thing is that 2 or 3 versions back (one of the November releases) FreeCAD Link was able to start. I've downloaded 2020.12.03 today and it fails to start. It eats one CPU core and doesn't show even the splash.

**Comment by realthunder** [comment]
Can you find out exactly which version can run?

**Comment by sigxcpu76** [comment]
I would've mentioned already but unfortunately I've overwritten it with 3.12 upgrade :(

**Comment by realthunder** [comment]
Maybe you can try [here](https://drive.google.com/drive/folders/19eIWuQGtKR3GMQA66xBstoQ43b_5LFGT?usp=sharing)?

**Comment by sigxcpu76** [comment]
2020.11.16 works (I lied, found the dmg in my Downloads folder). 2020.11.26 does not work. 202.11.29 does not work.

**Comment by realthunder** [comment]
Can you please try [this](https://drive.google.com/file/d/1sPt9brTvdU2MmWqCzGHCsd8O6XW62rtA/view?usp=sharing) image and see if it works?

**Comment by sigxcpu76** [comment]
Sure. I will do it tomorrow because I don't have the laptop with me atm.

**Comment by sigxcpu76** [comment]
@realthunder if there is nothing more to add you/I can close this to avoid open issues pollution.
