### ISSUE TITLE
Is it possible to use system dialogs in this fork?

### ISSUE THREAD

**Issue by akamensky** [realthunder/FreeCAD_assembly3#371]
Upstream releases use system dialogs for open/save/etc. This fork uses something else, which does not remember any previous choices/locations and makes navigation so much more difficult.

Upstream dialogs:

<img width="801" alt="Screen Shot 2020-12-06 at 1 03 33 PM" src="https://user-images.githubusercontent.com/985805/101272071-eaa89800-37c3-11eb-9fa5-bbfa55645095.png">

This fork dialogs:

<img width="663" alt="Screen Shot 2020-12-06 at 1 01 25 PM" src="https://user-images.githubusercontent.com/985805/101272085-f98f4a80-37c3-11eb-893f-872ba9af602b.png">

**Comment by akamensky** [comment]
One problem with using non-standard dialog is that I am unable to use external drive at all. "/Volumes" is not showing up at all:

<img width="660" alt="Screen Shot 2020-12-06 at 1 46 38 PM" src="https://user-images.githubusercontent.com/985805/101272694-7ec92e00-37c9-11eb-8e9b-c833c0b2daca.png">

**Comment by sigxcpu76** [comment]
Tools/Edit Parameters/Preferences/Dialog

Set `DontUseNativeDialog` to `false`. Add a boolean key if it is not there.

![image](https://user-images.githubusercontent.com/737085/101275335-84b11600-37ad-11eb-9108-d9bda741f798.png)

**Comment by Rabbit-sk** [comment]
> Set `DontUseNativeDialog` to `false`. Add a boolean key if it is not there.

Is there a reason why it is not set like this by default?

**Comment by akamensky** [comment]
@sigxcpu76 thanks, I will try it out once I am finished with current work for the day. I switched back to using upstream version due to multiple issues (a few issues I reported here today).

Agree with @Rabbit-sk. I think it should be using system one by default since the upstream version already does use that. I don't think there is any advantage to using non-system one in this instance.

**Comment by realthunder** [comment]
I have change back to default use native file dialog on Windows and MacOSX, same as upstream. The reason for using Qt file dialog is that this is the only way (that I know of) to open and save project into directory, especially save to a new directory. For existing project in an uncompressed directory, you can select the `Document.xml` file in the native file dialog.

Anyhow, I have expose the file dialog setting as below. And you can temporarily override the setting by holding SHIFT key when open or save your project.

![Screenshot from 2020-12-06 22-20-53](https://user-images.githubusercontent.com/1207888/101282737-be1b6d00-3811-11eb-9b48-b57e9520325b.png)

**Comment by akamensky** [comment]
Not sure about Windows, on macos I've seen a couple of applications doing directory based save/load from native dialog. But this may be just macos specific since it supports defining directories as "file type" (i.e. `.app` directory to which applications are bundled).

**Comment by sigxcpu76** [comment]
On Linux (at least) native file dialog does not add extensions automatically. Extensionless file name is also added to "recent files" which makes it impossible to open them from there. You need to put `.FCStd` by hand or `.stl` on exporting for 3d printing.

**Comment by Rabbit-sk** [comment]
I apologize for reopening this topic. I have a suggestion (maybe it has no sense for Linux, I don't know). In File menu, there could be two new items, one: "Open uncompressed  project" (after Open... Ctrl+O), and second: "Save uncompressed project" (maybe after Save as...). These two could use Qt file dialog, and standard ones could use native file dialogs.
![obrázok](https://user-images.githubusercontent.com/74265320/101317403-bf26bb80-385e-11eb-9e71-1123e11b315d.png)
