### ISSUE TITLE
Creating new datum plane fails

### ISSUE THREAD

**Issue by schmimat** [realthunder/FreeCAD_assembly3#375]
Hi,

thank you for the greate work you do for the freecad project.

I found a different behavior on one of my files betwen your branch (2020.12.08) and the original 23258 from git.
In your branch it is not possible to create a datum plane through the datum line _DL_Stift01_ and _XY of the Objekt_ perpenticular to the _Z_Axis_ also don' work.

With a brand new part it is possible to create this kind of datum plane.
[Lagerung Welle Ø10mm 4KuLa Halter.zip](https://github.com/realthunder/FreeCAD_assembly3/files/5670789/Lagerung.Welle.O10mm.4KuLa.Halter.zip)
![2020-12-10 07_08_03-FreeCAD Link Branch](https://user-images.githubusercontent.com/14329731/101732114-f98d9400-3abc-11eb-819e-b7519d486e32.png)
![2020-12-10 07_04_07-FreeCAD 0 19](https://user-images.githubusercontent.com/14329731/101732119-fbefee00-3abc-11eb-9a74-93604b3ec524.png)

Can you have a look at it?.

Best regards

Matthias

**Comment by realthunder** [comment]
The plane is created, but the length is too small to see. The size is auto determined by the bound box of all the objects in the body. I have added 'MinimumLength' and 'MinimumWidth' for the user to limit auto sizing. You can of course choose to use manual size.
