### ISSUE TITLE
Backward in the history ends up with duplicated objects 

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#38]
[In this model](https://github.com/realthunder/FreeCAD_assembly3/files/2339951/test2-before-grouping.zip) adding an assembly container and putting some objects in it then going back in the history causes erroneous tree.

## Reproduction 

* Add a new assembly container (`Assembly001`)
* Move the assembly container into `Assembly`
* Move `rpi` and `socket-cut` into `Assembly001`
* Press `<-` button to go back to the beginning 
* See there are two `Assembly001` containers show up. 

![history-error](https://user-images.githubusercontent.com/6639874/44912169-fb8b1900-ad31-11e8-9a8b-5f4af0a1c910.gif)

**Comment by realthunder** [comment]
Yes, this is a bug, although it is triggered by tree item move command.

**Comment by realthunder** [comment]
Fixed in LinkStage3

**Comment by ceremcem** [comment]
Works great, thanks!
