### ISSUE TITLE
MACOSX: The preferences menu can't open preferences window

### ISSUE THREAD

**Issue by domomib** [realthunder/FreeCAD_assembly3#388]
In mac OS X, freecad version 2020.12.17 when you try open preferences window trough the menu FreeCAD Link Branch -> Préférences, we do not have access to preferences window, instead we have access to Synchronization view, selection.... see snapshot
It is also present in the previous version 2020.12.13.
![Capture d’écran 2020-12-21 à 21 40 40](https://user-images.githubusercontent.com/19171320/102820361-682ff300-43d5-11eb-99b6-0a8ecb28495e.png)

**Comment by domomib** [comment]
It is present in the previous version too 2020.12.13

**Comment by realthunder** [comment]
That's a strange problem. I can't reproduce it. Can you try change language to English maybe? Can you also paste your `About` information here?

**Comment by RogerWilko85** [comment]
Hi,
I have the same problem with this version on OSX BigSur

**Comment by realthunder** [comment]
So is this a BigSur only problem? Do you have other version of OSX to confirm?

**Comment by RogerWilko85** [comment]
I have on old MBP with Osx El Capitan, and it doesn't run at all. The icon jump one time and that's all.

**Comment by RogerWilko85** [comment]
> That's a strange problem. I can't reproduce it. Can you try change language to English maybe? Can you also paste your `About` information here?
I can't change the language, because it's in preference menu.
<img width="513" alt="Capture d’écran 2020-12-22 à 14 09 19" src="https://user-images.githubusercontent.com/61159174/102891965-6d398480-445f-11eb-92d8-417bf9ffa1ea.png">

**Comment by domomib** [comment]
The problem is in my OS X High Sierra  version

**Comment by domomib** [comment]
I try remove all FreeCad preferences files, uninstall FreeCad, delete all freecad files and reinstall it again.
The problem is still present. (OS X High Sierra)

**Comment by realthunder** [comment]
It is indeed related to language setting. The French translation of menu item `Treeview action` is somehow  `Configuration de l'arborescence`. And Qt will treat any menu item starts with `Configuration', 'Setting', 'Option', etc. as preference menu item. The fix will be available in my next release.

**Comment by RogerWilko85** [comment]
@realthunder Thank you so much ^^

**Comment by VoidVolker** [comment]
Similar issue when switching to Russian language:

<img width="308" title="Settings menu item when Russian language is selected" src="https://user-images.githubusercontent.com/5086438/178116813-3bc2eab3-cf67-43ed-a4ca-e033118b7a77.png">

<img width="719" title="Settings view when Russian language is selected" src="https://user-images.githubusercontent.com/5086438/178116819-41c7c37b-3356-44e4-8fc1-7dbf6d89ef84.png">

<img width="246" title="Settings menu item when English language is selected" src="https://user-images.githubusercontent.com/5086438/178116817-761388a7-8742-4865-94f2-fb9e87776f83.png">

Installed using brew. Platform: m1.

[code]
OS: macOS 10.16
Word size of FreeCAD: 64-bit
Version: 0.20.29177 (Git)
Build type: Release
Branch: (HEAD detached at 0.20)
Hash: 68e337670e227889217652ddac593c93b5e8dc94
Python 3.9.13, Qt 5.12.9, Coin 4.0.0, Vtk 9.1.0, OCC 7.5.3
Locale: C/Default (C)
Installed mods: 
  * Behave-Dark-Colors 0.0.1
  * ProDarkThemePreferencePack 1.0.0
[/code]

**Comment by VladimirKraswov** [comment]
У меня такая же проблема если выбрать русский язык
