### ISSUE TITLE
project conflicts on OSX

### ISSUE THREAD

**Issue by RogerWilko85** [realthunder/FreeCAD_assembly3#389]
I have two opened projects and when I try to edit a sketch on the second project, the editor show me the body of the first project.

**Comment by RogerWilko85** [comment]
![Uploading Dec-22-2020 14-59-32.gif…]()

**Comment by RogerWilko85** [comment]
https://user-images.githubusercontent.com/61159174/102896626-fc966600-4466-11eb-92c5-4518041d95d5.mp4

**Comment by RogerWilko85** [comment]
https://user-images.githubusercontent.com/61159174/102897788-dd003d00-4468-11eb-9d63-05caca8581b5.mp4

**Comment by luzpaz** [comment]
@RogerWilko85 can you still recreate on latest version ?

**Comment by luzpaz** [comment]
No response from OP. Closing ticket.
