### ISSUE TITLE
problems with material editor

### ISSUE THREAD

**Issue by kervel** [realthunder/FreeCAD_assembly3#390]
Hello,

when using the latest release from assembly3 i can't use the FEM workbench because it is not possible to set youngs modulus for materials. Whatever you set, it reverts back to 0 mpa which is an invalid setting.

On the 0.19pre appimage it works, see screenshot below (youngs modulus is set correctly)
![image](https://user-images.githubusercontent.com/154455/103076679-94629400-45ce-11eb-8989-63e35408b952.png)

On the latest assembly3 appimage it reverts back to zero, and there is a warning about unknown unit in the log
![image](https://user-images.githubusercontent.com/154455/103076748-beb45180-45ce-11eb-8ffe-9fed5dd06e61.png)

09:59:02  YoungsModulus in material data seems to have no unit or a wrong unit (reset the value): Steel-Generic
09:59:02  

also the chosen material is always "_document_material" after reopening (but no idea if that's related)

Thanks,
Frank

**Comment by ceremcem** [comment]
@kervel Is this issue resolved?

**Comment by kervel** [comment]
yes i tried with todays daily and i can once again set youngs modulus!
Thanks
Frank

**Comment by ceremcem** [comment]
Would you mind closing the issue?

**Comment by kervel** [comment]
ok!
