### ISSUE TITLE
[Urgent] Happy new year!

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#398]
# Description 

This bug seems to be blocker. It might be related with upstream too, but regarding to the progress speed, it could be resolved here more quickly, so I'm opening here. 

# Reproduction: 

1. Open FreeCAD
2. Open PartDesign WB
3. Draw a rectangle
4. Create a coincident constraint on the left side to align to 2019
5. Create a coincident constraint on the right side to align to 2021

## Expected 

Width of the rectangle should be 1 year long 

## Observed 

Width of the rectangle is very small, like weeks. 

# Version 

All commits affected between https://github.com/realthunder/FreeCAD/commit/f6c174 and https://github.com/realthunder/FreeCAD/commit/b59989

**Comment by realthunder** [comment]
Haha, that's a good one! Happy new year!
