### ISSUE TITLE
Unable to install/run

### ISSUE THREAD

**Issue by R4DM4N** [realthunder/FreeCAD_assembly3#409]
When I unzip the file and run the executable I have this message left on my screen.
I have tried copying the folder to different locations --- same message.  I did try the previous release of your software and it run fine on my computer.  I must be missing something.

![Freecad19ASM](https://user-images.githubusercontent.com/47617496/104079220-a8b0bd00-526d-11eb-90a9-7f7b3c880edd.PNG)

 
FreeCAD 0.19, Libs: 2020.1230R23076 +3055 (Git)
Sheet Metal workbench loaded
[FreeCAD Console mode <Use Ctrl-Z plus Return to exit.>]
>>>

**Comment by realthunder** [comment]
Please run `FreeCADLink.exe` instead.

**Comment by R4DM4N** [comment]
Thanks for the quick reply.
