### ISSUE TITLE
Incorrect "Exception: No view"

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#41]
When GUI is in "Undocked mode", clicking some visual parts in the treeview causes this incorrect exception: 

```console
Exception (Fri Aug 31 22:37:58 2018): no view  
```

**Comment by realthunder** [comment]
But confirmed, will fix soon.

**Comment by realthunder** [comment]
Should be fixed in LinkStage3.

**Comment by ceremcem** [comment]
Seems fixed. Thanks!
