### ISSUE TITLE
OMG First Glance This Is AWESOME

### ISSUE THREAD

**Issue by R4DM4N** [realthunder/FreeCAD_assembly3#412]
Amazing work you have done. Kudos realthunder.

**Comment by luzpaz** [comment]
@ceremcem do you have permissions to pin this issue ?

**Comment by ceremcem** [comment]
Nope, unfortunately I don't.

**Comment by luzpaz** [comment]
@realthunder do you have/want any help to maintain this issue queue ? Can you give permissions?

**Comment by ceremcem** [comment]
I think @luzpaz is the absolute candidate for this :)

**Comment by luzpaz** [comment]
Have too many hats already but at least when I swing by here I can keep things tidy-er
