### ISSUE TITLE
Feature proposal: Give a name to a new body or clone based on the name of the selected body

### ISSUE THREAD

**Issue by Rabbit-sk** [realthunder/FreeCAD_assembly3#417]
Dear Realthunder,

The name of a link of a body is based on the name of the linked body:

https://user-images.githubusercontent.com/74265320/104193856-d853f680-5420-11eb-8c06-01122c312134.mp4

But the name of a clone of a body is general:

https://user-images.githubusercontent.com/74265320/104194475-aee79a80-5421-11eb-888a-d32181203663.mp4

Also the name of a new body is general:

https://user-images.githubusercontent.com/74265320/104194937-464ced80-5422-11eb-96c7-68ec50d54d29.mp4

Could clones have automatic naming like it is in case of links? 

In case of a new body, this is my main interest,  the new body could have name based on a name of an actually selected body in the tree view:
![obrázok](https://user-images.githubusercontent.com/74265320/104196122-b5771180-5423-11eb-9daf-c23bb477d503.png)
![obrázok](https://user-images.githubusercontent.com/74265320/104196292-e6574680-5423-11eb-999a-40ca85d92dbe.png)
This automatic naming behavior of a new body maybe could have an option in preferences, because I realize that maybe this is something that not everyone would like.

Regards

**Comment by Rabbit-sk** [comment]
Is this setting for something I described above?
![obrázok](https://user-images.githubusercontent.com/74265320/104811782-3c4e3480-57fe-11eb-8a02-19669bf18ac2.png)
I've tried it, but I can't figure out what effect this setting has.

**Comment by realthunder** [comment]
No, it is not. I search around the code. This seems to be a abandoned setting. I have repurpose it for this body naming option. I didn't add auto naming to clone, as this is considered as a deprecated feature in my branch and is only here for compatibility with upstream. I'll remove it when merging PartDesign changes into upstream.

**Comment by Rabbit-sk** [comment]
> I didn't add auto naming to clone, as this is considered as a deprecated feature in my branch and is only here for compatibility with upstream. I'll remove it when merging PartDesign changes into upstream.

What about projects which uses clones? Will they open correctly after clone function remove?

**Comment by realthunder** [comment]
Sure, I mean to just remove the toolbar icon to not confuse the new user.

**Comment by Rabbit-sk** [comment]
Now in version 2021.0126 a name given to a new body is based on the name of the body selected before new body creation, but only if that body is used as a base feature for a new body. 

In my workflow, I usually create objects without using the body as a base feature. But I want to give them the same name, with the addition of a sequentional number, because they have the same material. Before export I select them in tree view by name and set them the same color.

So my proposal for naming automation of the new body is:
![obrázok](https://user-images.githubusercontent.com/74265320/105837403-f1d37180-5fce-11eb-9321-6e07032f260e.png)
![obrázok](https://user-images.githubusercontent.com/74265320/105837433-fac44300-5fce-11eb-9eec-a0ee9bba50c3.png)
![obrázok](https://user-images.githubusercontent.com/74265320/105837637-45de5600-5fcf-11eb-8282-a24527fb7937.png)
If no body will be selected before new body creation, the name would be Body.
.
Do you think this behavior could be incorporated into FreeCAD? If yes, should it has an option in preferences?
