### ISSUE TITLE
Minor improvement - Keeping the Workbench list sorted

### ISSUE THREAD

**Issue by leoheck** [realthunder/FreeCAD_assembly3#418]
Hey, I was thinking that it might be good to keep the Workbench list sorted.
See here, the Assembly 3 is being added at the end of the list, it is much better to have this list sorted to find things easier.

![image](https://user-images.githubusercontent.com/1277920/104199966-daa95700-5406-11eb-91ab-d7fa9202eb73.png)

**Comment by realthunder** [comment]
I just realized that the previous `workbench sort` functionality conflicts with the workbench list customization (available in `Preferences -> Display -> 3D View -> Sort workbench list`, see realthunder/FreeCAD#109). Therefore, I decide to disable workbench list auto sorting by default. You can still turn it on manually with `Preferences -> Display -> 3d view -> Sort workbench list`.

**Comment by luzpaz** [comment]
Should we close this ticket ?
