### ISSUE TITLE
Same label can be assigned in treeview 

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#42]
In upstream, same label is not allowed in any case: 

![same-label-not-allowed-correctly](https://user-images.githubusercontent.com/6639874/44948219-96fbb700-ae22-11e8-97f0-58ea0718fda2.gif)

In LinkStage3, we can assign the same label in treeview erroneously: 

![same-label-allowed-erroneously](https://user-images.githubusercontent.com/6639874/44948224-a8dd5a00-ae22-11e8-8a5f-0cc99d226890.gif)

# Reproduction 

1. Add a part, name it "myobject"
2. Add another part, try to name it "myobject"
3. The second part will be named as "myobject001"
4. Try to rename "myobject001" as "myobject" again
5. See the second object is renamed "succesfully" as "myobject" *only* in the treeview

**Comment by realthunder** [comment]
Confirmed. Will fix soon.

**Comment by realthunder** [comment]
Fixed in LinkStage3.

**Comment by ceremcem** [comment]
Thanks!
