### ISSUE TITLE
Expression editor visibility blocked by scroll bar for long expressions (2021.0112)

### ISSUE THREAD

**Issue by DevyHeavy** [realthunder/FreeCAD_assembly3#423]
Hi, when entering long expressions into the expression editor the scroll bar gets in the way. See the below video.

https://user-images.githubusercontent.com/28787282/104857434-99251a00-58e6-11eb-8b30-b2be4f27c18b.mp4

Thanks.

OS: Ubuntu 20.04.1 LTS (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.0112.23076 +3101 (Git) AppImage
Build type: Release
Branch: (no branch, rebasing LinkMerge)
Hash: 82adb0b22d37a3be1c88c0c3cc64edf598c315a0
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by snelweg** [comment]
Same problem here. Made me switch back to the 'official'  release. And then I came straight back to yours!

> OS: Debian GNU/Linux 10 (buster) (XFCE/lightdm-xsession)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.0112.23076 +3101 (Git) AppImage
Build type: Release
Branch: (no branch, rebasing LinkMerge)
Hash: 82adb0b22d37a3be1c88c0c3cc64edf598c315a0
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)


![Screenshot_2021-01-24_21-03-08](https://user-images.githubusercontent.com/1257901/105642069-ae222000-5e87-11eb-998b-71e4dd8d6281.png)
![Screenshot_2021-01-24_21-03-32](https://user-images.githubusercontent.com/1257901/105642071-aebab680-5e87-11eb-8aeb-f89306c6ad41.png)

**Comment by DevyHeavy** [comment]
Looks like this will be resolved in the next release: https://github.com/realthunder/FreeCAD/commit/2a9dad090665e5613ebeef8cbd02c48d32a95fe5

**Comment by realthunder** [comment]
New release available.

BTW, you can also manually resize the editor.

![expr-editor](https://user-images.githubusercontent.com/1207888/105689379-a751e680-5f35-11eb-9b08-c2c53599cf84.gif)

**Comment by snelweg** [comment]
Resizing doesn't work here. I can resize the 'normal' editor, but not the expression editor. Happy to use the new release.

(Thank you for all your hard work, you make FC into what it should be. Very happy with your efforts)
![Screenshot_2021-01-25_11-11-07](https://user-images.githubusercontent.com/1257901/105692194-67234180-5efe-11eb-861c-12d03ffc1fe5.png)

**Comment by snelweg** [comment]
Looks funny. Would be nice if the dialogbox would be broader (as in more width).

![Screenshot_2021-01-25_11-18-50](https://user-images.githubusercontent.com/1257901/105692906-50311f00-5eff-11eb-91df-ef5f3c74758e.png)

**Comment by realthunder** [comment]
Release 0126 added resizing capability for platforms besides Linux. If you are using MacOSX, there is still some problem, which will be fixed in the next release. Currently it requires you to manually add an integer parameter `Preferences\Exprssion\EditDialogBGAlpha` using `Tools -> Edit parameters`, and set the value to 16 or greater. OSX behave strangely if the dialog background is too transparent. Windows works fine with a default alpha value of just 1.

Or, if you prefer normal dialogs, you can disable in-place editing completely in `Preferences -> UI -> Expression editor`.

**Comment by snelweg** [comment]
> Or, if you prefer normal dialogs, you can disable in-place editing completely in `Preferences -> UI -> Expression editor`.

This fixed it for me, the other solutions are transparent and not really useful and look odd.

But now there are many strange things happening. The measurements are gone, or very tiny. When I switch back there are no formula's in the edit box anymore, just values. 
I will make screenshots tomorrow, not enough time now.

**Comment by luzpaz** [comment]
@snelweg what's the status of this?

**Comment by snelweg** [comment]
> @snelweg what's the status of this?

Using FreeCAD-asm3-Daily-Conda-Py3-Qt5-20210717-glibc2.12-x86_64.AppImage and I notice nothing strange anymore. I will close this issue.

**Comment by DevyHeavy** [comment]
Yes, this has been addressed, closing.
