### ISSUE TITLE
Assertion error on startup with the PersistentToolbars mod

### ISSUE THREAD

**Issue by jsmaniac** [realthunder/FreeCAD_assembly3#426]
When the https://github.com/triplus/PersistentToolbars/ mod is installed, this message appears on startup:

```
Traceback (most recent call last):
  File "<string>", line 239, in onStart
  File "<string>", line 228, in onWorkbenchActivated
AssertionError: No active workbench
```

It seems due to https://github.com/triplus/PersistentToolbars/blob/06dcf6d4086d74bdd20d30fb9f62a220954c552b/InitGui.py#L236-L239 which calls https://github.com/triplus/PersistentToolbars/blob/06dcf6d4086d74bdd20d30fb9f62a220954c552b/InitGui.py#L225-L228 which calls `Gui.activeWorkbench()`, and `Gui.activeWorkbench()` raises an exception instead of returning `None`.

```
OS: Ubuntu 20.04.1 LTS (XFCE/xubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2020.1230.23076 +3055 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: c7f24fa0eb98232200ab5cae1ac3be8786a22c2c
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United Kingdom (en_GB)
```

The error does not occur with the official FreeCAD:

```
OS: Ubuntu 20.04.1 LTS (XFCE/xubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.23546 (Git) AppImage
Build type: Release
Branch: master
Hash: 6b017f9a16b15b0e628c8d874c4058442dee5548
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United Kingdom (en_GB)
```

**Comment by sigxcpu76** [comment]
Did you notice this?

```Persistent toolbars (FreeCAD 0.16)

Note: Starting with FreeCAD 0.17 persistent toolbars is part of the default FreeCAD experience.```

**Comment by jsmaniac** [comment]
> Did you notice this?
> 
> ```
> Persistent toolbars (FreeCAD 0.16)
> 
> Note: Starting with FreeCAD 0.17 persistent toolbars is part of the default FreeCAD experience.
> ```

Didn't notice that, thanks :) . Should I close this or should `Gui.activeWorkbench()` still return None instead of an exception?

**Comment by realthunder** [comment]
No, that may break newer code that expects an exception. I don't think we need to change anything, as persistent toolbar will check for FreeCAD version and only activate itself if version < 16, which means it is a deprecated workbench. My release uses date for version, and in this case it is 0112. Unfortunately persistent toolbar is doing string comparison, so '0112' is considered smaller than '16'. I'll make the version something like 112 in my next release to avoid similar problem in the future.

**Comment by jsmaniac** [comment]
Fair enough :) I'm closing this as it's a valid "wontfix" :)
