### ISSUE TITLE
Manipulator WB throws exception

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#43]
~Measurement~ Manipulator WB works correctly on my simple tests, I can not reproduce the exception on newly created drawings but here is the traceback: 

```console 
Traceback (most recent call last):
  File "/home/ceremcem/.FreeCAD/Mod/Manipulator/Caliper.py", line 382, in addSelection
    plcm, top_level_obj, bbC, pnt, orient, norm = get_placement_hierarchy (sel[0])
  File "/home/ceremcem/.FreeCAD/Mod/Manipulator/Caliper.py", line 1117, in get_placement_hierarchy
    listSorted=get_sorted_list (Obj)
  File "/home/ceremcem/.FreeCAD/Mod/Manipulator/Caliper.py", line 1026, in get_sorted_list
    if len(ap.InListRecursive) < lvl:
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'InListRecursive'
Traceback (most recent call last):
  File "/home/ceremcem/.FreeCAD/Mod/Manipulator/Caliper.py", line 382, in addSelection
    plcm, top_level_obj, bbC, pnt, orient, norm = get_placement_hierarchy (sel[0])
  File "/home/ceremcem/.FreeCAD/Mod/Manipulator/Caliper.py", line 1117, in get_placement_hierarchy
    listSorted=get_sorted_list (Obj)
  File "/home/ceremcem/.FreeCAD/Mod/Manipulator/Caliper.py", line 1026, in get_sorted_list
    if len(ap.InListRecursive) < lvl:
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'InListRecursive'
```

for the following operation: 

![measurement-exception](https://user-images.githubusercontent.com/6639874/44948623-b1855e80-ae29-11e8-8823-30863c7f9db7.gif)

In this model: [rpi3.fcstd.remove-extension.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2342576/rpi3.fcstd.remove-extension.zip)

**Comment by easyw** [comment]
Measurement WB doesn't even exist. 😝

**Comment by ceremcem** [comment]
What?! :D How come?
![peek 2018-09-01 21-15](https://user-images.githubusercontent.com/6639874/44948769-36717780-ae2c-11e8-9920-6631b96eb1a1.gif)

**Comment by easyw** [comment]
> What?! :D How come?

Who knows ... If you can find Measurement WB you are lucky... but I can only find Manipulator WB 😉

**Comment by ceremcem** [comment]
AAAAAAAAAAAAAAHhh :D

**Comment by easyw** [comment]
1) your are using MWB on A3 branch... this is not fully supported ATM... I'm slowly including the new containers that A3 is using... 
At the same time, which is your MWB release and particularly Caliper release? 
I cannot reproduce your issue witht the attached file on Caliper v1.43 and A3 0.86

**Comment by ceremcem** [comment]
When I switch to MWB, Report view says its 
```
Manipulator WB Activated(v 1.2.6)
```
When I click the "Caliper", Report view says 
```
Caliper version 1.4.3
```

I'm also using A3 0.8.6 from realthunder's releases on Debian, with Appimage.

**Comment by ceremcem** [comment]
Wow, yes, I also can not reproduce my issue with my own file when I download it separately. Weird. Let me find the cause.

**Comment by ceremcem** [comment]
Okay, here is the reproduction steps: 

1. Download [test3.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2342670/test3.zip)
2. Open `enclosure.fcstd` (not `rpi.fcstd` directly)
3. This will automatically open `rpi.fcstd`
4. Try to measure the distance between holes

**Comment by easyw** [comment]
ok, I can reproduce it
BTW the doc is complex... it is using external docs/links... 
I will have a look at...

**Comment by ceremcem** [comment]
Closing as it's already belongs to an external workbench and I can not reproduce the problem.
