### ISSUE TITLE
Parts are moving together unexpectedly 

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#44]
Here the `rpi` and `Extrude` parts are in the same hierarchy, and `Auto recompute` is disabled, so I would expect to be able to move the `Extrude` independently, but it is somehow bound to the `rpi`: 

![peek 2018-09-01 22-13](https://user-images.githubusercontent.com/6639874/44949143-4ab97280-ae34-11e8-9460-e6a0b3ed4553.gif)

Model is [here](https://github.com/realthunder/FreeCAD_assembly3/files/2342670/test3.zip)

**Comment by realthunder** [comment]
Because there are multiple levels hierarchies in-between, the part mover defaults to move parts in the first hierarchy, therefore, you are actually moving rpi-with-env. To move Extrude inside rpi-with-env, you need to add rpi-with-env as the second selection before activating mover.

**Comment by ceremcem** [comment]
Can you be more specific? What do you mean by "adding an object/container as second selection"?

**Comment by ceremcem** [comment]
I can't believe myself. Sorry for the duplicate and thank you again. (I added this into [my notes](https://github.com/ceremcem/freecad-notes/blob/master/README.md#by-task-asm3))
