### ISSUE TITLE
Why "Labels & Attrebutes" & "Description" columns in Combo View are not resizable horizontally?

### ISSUE THREAD

**Issue by FreeCADAntiBugs** [realthunder/FreeCAD_assembly3#449]
Hello realthunder,
- i can't resize "Labels & Attributes" or "Description" columns individually (both have fixed length cell) in Combo View panel.
- Freecad linkstage3 0.19 Pre Daily 2021.02.02
- Linux Mint 20.1 Desktop.
Thank you for your effort and time.

**Comment by realthunder** [comment]
You can make it resizable through 'View -> Tree view options -> Resizable columns'. I'll move the option to UI preference page later.
