### ISSUE TITLE
Tiny 3D cube on 5K display

### ISSUE THREAD

**Issue by irmantus** [realthunder/FreeCAD_assembly3#453]
That 3D cube thingamajig is very tiny on iMac 5K retina display, imposible to use.

<img width="2560" alt="Screenshot 2021-02-05 at 11 28 28" src="https://user-images.githubusercontent.com/37515045/107015878-ee49a280-67a5-11eb-9f17-5241af080a76.png">

**Comment by ceremcem** [comment]
@irmantus Can you check if that issue is resolved in https://github.com/realthunder/FreeCAD_assembly3/releases/tag/0.11?

**Comment by irmantus** [comment]
By default it was still small, but now I see size settings so I set to 256 and it looks nice.
<img width="2439" alt="Screenshot 2021-02-22 at 09 21 44" src="https://user-images.githubusercontent.com/37515045/108675454-7db5bc00-74ef-11eb-9950-d39b0f67ace1.png">
