### ISSUE TITLE
Release version number in the change log does not match the most recent

### ISSUE THREAD

**Issue by Rabbit-sk** [realthunder/FreeCAD_assembly3#456]
![obrázok](https://user-images.githubusercontent.com/74265320/107112478-375a2f00-6858-11eb-8451-a6ffb4b05a46.png)

![obrázok](https://user-images.githubusercontent.com/74265320/107112439-f8c47480-6857-11eb-994c-54b7dfb87160.png)

**Comment by realthunder** [comment]
Oops! Not my first time.

**Comment by Rabbit-sk** [comment]
![obrázok](https://user-images.githubusercontent.com/74265320/149014973-d49b9785-ce92-4b99-9f3c-9ea93a375675.png)

**Comment by luzpaz** [comment]
Closing
