### ISSUE TITLE
Position of link instances is cumulatively increased in X direction

### ISSUE THREAD

**Issue by Rabbit-sk** [realthunder/FreeCAD_assembly3#459]
Dear RealThunder, 

please look at X coordinate of these link objects, which have cumulating addition to their position:
(The y coordinate was already changed by me.)
![obrázok](https://user-images.githubusercontent.com/74265320/107234103-991ac480-6a23-11eb-8d7a-8ddb9759a7ec.png)
![obrázok](https://user-images.githubusercontent.com/74265320/107234201-b2bc0c00-6a23-11eb-9c86-f4b10524911e.png)
![obrázok](https://user-images.githubusercontent.com/74265320/107234369-e0a15080-6a23-11eb-9ead-d995ab123966.png)
![obrázok](https://user-images.githubusercontent.com/74265320/107234443-f57de400-6a23-11eb-9a03-ef5c124d1aaa.png)
![obrázok](https://user-images.githubusercontent.com/74265320/107234494-06c6f080-6a24-11eb-85df-450c1b91e5d2.png)
And so on...

These link objects are inside link object, whose Element Count is set to 8.

Also Z coordinate of Axis is set to 1 mm on every link object:
![obrázok](https://user-images.githubusercontent.com/74265320/107236144-b2bd0b80-6a25-11eb-940b-5fa45287d2fb.png)

Maybe because body itself has 1 mm added to the Z coordinate:
![obrázok](https://user-images.githubusercontent.com/74265320/107236986-8a81dc80-6a26-11eb-8a4a-c27a60d510b6.png)
After seted to 0, it is again 1 mm. Why these offsets?  

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.0205.23662 +3201 (Git)
Build type: Release
Branch: LinkStage3
Hash: 9391fcd19568d635bb290db09f9d616e6acdc4f4
Python version: 3.6.8
Qt version: 5.12.6
Coin version: 4.0.0a
OCC version: 7.4.0.beta
Locale: Slovak/Slovakia (sk_SK)

Regards

**Comment by realthunder** [comment]
The increment is on purpose, for distinguish of different array element. It is probably better to use the shape boundary for better choice of increatment.

**Comment by Rabbit-sk** [comment]
> The increment is on purpose, for distinguish of different array element.

Makes sense. If an object is not much bigger than 1 mm in any direction, then it is distinguishable:
![obrázok](https://user-images.githubusercontent.com/74265320/107477725-8960c480-6b78-11eb-86e3-2e4f7046611d.png)

But if it has at least one dimension much bigger than 1 mm, these offsets are not noticable, only after longer zooming and in the Data tab. Ofcourse one can easily change this increment in position to whathever desired value. With bigger objects, fitted to the view, it still seems that they are all in one place and undistinguishable. So for me it seemed as a bug. 

Increment of position to distinguish array elements is good idea, but 1 mm is not enough for all purposes that FreeCAD can be used. Would it be possible to obtain the size of the bounding box of linked object (body or part container) and use that value to increment array elements?
![obrázok](https://user-images.githubusercontent.com/74265320/107479004-b8783580-6b7a-11eb-8cf4-0cc1cae897d2.png)

> It is probably better to use the shape boundary for better choice of increatment.

Is this what I decribed above?

**Comment by realthunder** [comment]
> Is this what I decribed above?

Yes, that's right. And the above commit implemented just that.

**Comment by Rabbit-sk** [comment]
It works better now. There is only a weird placement pattern if bigger number of instances is entered at once:

https://user-images.githubusercontent.com/74265320/108812081-bff20280-75ae-11eb-9f60-3c9448bb8493.mp4

Verified in the build compiled from the source code after commit [9deefac](https://github.com/realthunder/FreeCAD/commit/9deefac4f2748d4af44d5d856f605c92d736c8c3).

**Comment by Rabbit-sk** [comment]
> There is only a weird placement pattern if bigger number of instances is typed (in video from 0:34 to 0:45)

Since no object overlaps with another, and instances are later placed in the desired position, this somewhat strange initial location is irrelevant. I consider this issue solved.
