### ISSUE TITLE
 extrude commant not working is  normal profile to curved surface

### ISSUE THREAD

**Issue by sedatkrn** [realthunder/FreeCAD_assembly3#463]
Freecad Linkstage did not make extrude normal sketch to cruved surface.
i made a cylinder on the frontplane and a creating a plane to top plane and offset from cylinder over de radius. for example ccylinder r=60mm h=100mm.i put the plane  top plane and giving to z offset about 80mm. create and sketc to offseting plane and create a circle r=20mm. 

i click to pad command for circle sketch. it is runing open the left pad menu. i choose to type box andi choosen up to the surface. i sellect to cylinder cruved surface but didnt make extrude. normaly freecad makes it. thanks...

**Comment by ceremcem** [comment]
Can you please clarify your intention, I found it too dispersed to understand. Please provide a set of instructions to reproduce your intention.

**Comment by sedatkrn** [comment]
Cerem bey iyi çalışmalar.  bir daire profili bir yüzeye kadar extrude yapmak istiyorum ancak yapacağım yüzey bir silindirin yan yüzeyi gibi eğri bir yüzey. Linkstage3  yalnızca düzlemsel yüzeylere kadar extrude yapıyor.  

> 
> 
> Can you please clarify your intention, I found it too dispersed to understand. Please provide a set of instructions to reproduce your intention.

**Comment by ceremcem** [comment]
So you want to extrude a non-flat surface, like this: 

![image](https://user-images.githubusercontent.com/6639874/107889835-4dd24b80-6f26-11eb-8d4b-4a96ee4bdb1e.png)

Is that correct?

**Comment by sedatkrn** [comment]
bahsetmek istediğim bu. şu daire silindir yüzeyine extrude yapamıyorum.şu anda sanırım desteklemiyor. dosyayı ekledim. çok teşekürler ilginiz için.

This is what I want to talk about. I can't extrude that circle cylinder surface. I guess it doesn't support it right now. i uloded the file. tahanks for intrest.



![Ekran görüntüsü 2021-02-15 023538](https://user-images.githubusercontent.com/79061314/107892496-8a0da800-6f36-11eb-8a75-114340878dd0.png)

https://github.com/sedatkrn/resimler/blob/main/extrude%20problem.FCStd

**Comment by ceremcem** [comment]
This can be achieved by using `Type: Two dimensions` within the extrusion menu: 

![image](https://user-images.githubusercontent.com/6639874/107893085-2e451e00-6f3a-11eb-87de-2844ffea5950.png)

Use `0 mm` as `Length` and an appropriate length (eg. 100mm) for `2nd length`: 

![image](https://user-images.githubusercontent.com/6639874/107893118-6d736f00-6f3a-11eb-8d9a-5d635a5d7715.png)

(You're welcome)

**Comment by sedatkrn** [comment]
Ben bunu böyle yapılabileceğini biliyorum fakat demek istediğim eğri yüzeylere extrude  yapamamsı, ancak normal freecad süürümü bunu yapabiliyor. acaba bu eksik ne zaman giderilir.
I know it can be done this way, but I mean it can't extrude into curved surfaces, but the normal freecad version can do it. I wonder when this missing is fixed.

**Comment by ceremcem** [comment]
> ancak normal freecad süürümü bunu yapabiliyor.

Eğri yüzeylerde böyle bir işlem yapılabildiğini bilmiyordum. (I didn't know that such a thing is even possible). 

Works as of above commit: 


https://user-images.githubusercontent.com/6639874/107939587-01275880-6f98-11eb-959a-8f85dc3f20c5.mp4

**Comment by sedatkrn** [comment]
Çok faydalı bir özellik. It is so usefully tools.
