### ISSUE TITLE
FreeCAD crashes after deletion of multiple items in a sketch

### ISSUE THREAD

**Issue by Rabbit-sk** [realthunder/FreeCAD_assembly3#464]
Dear RealThunder, 

after selecting and deleting multiple items in a sketch, nothing dissapear, and after click, FreeCAD crasches.

Another time, when I moved mouse over geometry that should be deleted
Some warnings from Report View:
![obrázok](https://user-images.githubusercontent.com/74265320/107929216-a41caa00-6f79-11eb-8d97-965b3421360a.png)

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.0205.23662 +3201 (Git)
Build type: Release
Branch: LinkStage3
Hash: 9391fcd19568d635bb290db09f9d616e6acdc4f4
Python version: 3.6.8
Qt version: 5.12.6
Coin version: 4.0.0a
OCC version: 7.4.0.beta
Locale: Slovak/Slovakia (sk_SK)

Regards

**Comment by ceremcem** [comment]
I could reproduce the crash. Note that it only crashes if you select from right-down to left-up and then press `Delete` key on the keyboard. 

I can also confirm that this crash does not happen in the recent version: 

```
OS: Debian GNU/Linux 10 (buster)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.27235 (Git)
Build type: Release
Branch: LinkStage3
Hash: 23bafae49eb9858e1dde35e58f2f0ebca76a8f0a
Python version: 3.7.3
Qt version: 5.11.3
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: English/UnitedStates (en_US)
```

**Comment by oficinerobotica** [comment]
Tested with:
```
OS: KDE neon User Edition 5.21 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.531.24301 +3702 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 4ad819f55a108b7e8bddb134d0de39218e662aa4
Python version: 3.8.10
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)
'''
and the issue isn't present anymore.
