### ISSUE TITLE
Missing objects in Wavefront OBJ file if Sub-ShapeBinder is used

### ISSUE THREAD

**Issue by Rabbit-sk** [realthunder/FreeCAD_assembly3#466]
Dear RealThunder,

I found out that some objects which are referenced to other bodies by Sub-ShapeBinder are not present in export file. 
Here is project file where it occurs:
[CubeNotExported.zip](https://github.com/realthunder/FreeCAD_assembly3/files/5987412/CubeNotExported.zip)

![obrázok](https://user-images.githubusercontent.com/74265320/108042515-2ec7dc80-7040-11eb-97ea-ef97f73c959a.png)
![obrázok](https://user-images.githubusercontent.com/74265320/108042638-5ae35d80-7040-11eb-92a1-ca613e01f4c4.png)

After detaching Sub-ShapeBinders in  Body002, cube is exported.

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.0205.23662 +3201 (Git)
Build type: Release
Branch: LinkStage3
Hash: 9391fcd19568d635bb290db09f9d616e6acdc4f4
Python version: 3.6.8
Qt version: 5.12.6
Coin version: 4.0.0a
OCC version: 7.4.0.beta
Locale: Slovak/Slovakia (sk_SK)

Regards

**Comment by realthunder** [comment]
This is not really a bug. The role of SubShapeBinder inside a body is similar to datum. They are meant to be used by other features. Currently, the body only supports to export the shape of the current tip feature, i.e. the one marked by the green square in the middle of its the tag icon. If you really want to export the shapes from other solid features or binders inside a body, you can create a Part and then add those objects through link, or relative link if you want to maintain their relative placement. If it is just a one time export, you can simply select those features individually and then export.

**Comment by Rabbit-sk** [comment]
I think there is a misunderstanding. I create object1, then object2 in which some face/s of object1 is/are referenced by SubShapeBinder/s, because I want to follow up on its shape. Then I select all objects, and some of them are not exported. I know that SubShapeBinders are for using by other features as pad, pocket, sketches... to create another solid shape. I do not want to separately export solid features in the middle of history of body, or SubShapeBinder shapes. I want to export all selected bodies Like this: 
![obrázok](https://user-images.githubusercontent.com/74265320/108053982-5de54a80-704e-11eb-811e-b0c61ae15779.png)
and their final state represented by they last solid feature marked with Tip. But this is not working in the case of that cube and some other objects, which was used by another bodies through SubShapeBinders. After detaching those SubShapeBinders it works.

BTW that cube has Tip on the right place:
![obrázok](https://user-images.githubusercontent.com/74265320/108053893-47d78a00-704e-11eb-9df4-4893697531f1.png)

**Comment by realthunder** [comment]
I get what you mean now. That's an unexpected error.

**Comment by Rabbit-sk** [comment]
I deleted FreeCAD folder, extracted it again, substitued the `ArchCommands.py` file in  `../Mod/Arch/` and also copied it to `../Mod/Draft/` (despite it seems that it should not be there), as you suggested [here](https://github.com/realthunder/FreeCAD_assembly3/issues/473#issuecomment-782958617) and exporting is still broken :(
![obrázok](https://user-images.githubusercontent.com/74265320/108692202-9c6e7f80-74fc-11eb-955b-e5f530fa710b.png)
![obrázok](https://user-images.githubusercontent.com/74265320/108692688-33d3d280-74fd-11eb-9155-598f622467a3.png)

**Comment by realthunder** [comment]
Oh, that's a typo. Sorry about that. It should be in `Mod/Arch/` overwriting the existing one.

**Comment by Rabbit-sk** [comment]
I thought. I copied it to the `../Mod/Arch/`, but export still doesn't work fully.

**Comment by ceremcem** [comment]
@Rabbit-sk Sure thing. ASAP.

**Comment by realthunder** [comment]
Ah, right, that specific change only works with some other early changes. Please search for `Part::SubShapeBinder` inside that `ArchCommands.py` file, and change it to `PartDesign::SubShapeBinder`.

I have moved SubShapeBinder implementation into `Part` module in some early commit.

**Comment by Rabbit-sk** [comment]
This change helped. Objects that have not been exported are now being exported, except for a small number of objects. I will check the export for missig objects and try to find out where the problem is. In the meantime, I left this problem open.

**Comment by Rabbit-sk** [comment]
Now I used build that I compiled from newest source code, and number of missing objects is smaller. I will look at the remaining non-exported objects and provide more information

**Comment by Rabbit-sk** [comment]
There were missing only two objects, which were elso mentioned in ReportView (before latest obj export fix, there were missing also objects that were not mentioned in the ReportView). 

- First object consists of binder of a sketch and Extrusion feature from it. Tip was not set to Extrusion feature as described in the ToolTip. Easy fix was to set Tip to that Extrusion. Why Tip is not set to Extrusion feature? BTW Extrusion feture is extremely usefull when one want to make only a surface.
- Second object consist only of a base feature made from solid shape of another body. I guess that since this BaseFeature is basically a SubShapeBinder, and they are excluded from processing while exporting, such body is not exported. This is fine, there is the Link function to make copies. This approach with BaseFeature without adding further features to it,  was choosen in a hurry... 

I think that this issue could be closed. There is only a question why not to set a Tip to Extrusion feature.

**Comment by Rabbit-sk** [comment]
> Sure thing. ASAP.

@ceremcem thank you for your willingness.
