### ISSUE TITLE
Using labels on Github issues

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#47]
@realthunder would you mind using labels for the issues because that also helps querying later for us.

**Comment by realthunder** [comment]
Sure.

**Comment by ceremcem** [comment]
I suggest `upstream` label for [this](https://github.com/realthunder/FreeCAD_assembly3/issues/69) kind of issues.

**Comment by ceremcem** [comment]
I suggest `upstream/merge` label for [these](https://github.com/realthunder/FreeCAD_assembly3/issues/69) kind of issues.

* `upstream/merge` means there is patches already in the upstream, waiting to be merged into LinkStage3
* `upstream/issue` this issue is related with upstream and should be solved in the upstream 
* `upstream/forum` this issue has nothing to do with LinkStage3 and probably a newbie question, should be found in the forum
