### ISSUE TITLE
Dock window overlay, not resizing

### ISSUE THREAD

**Issue by snelweg** [realthunder/FreeCAD_assembly3#474]
When I am in overlay mode the treeview is always to narrow. I can not adjust it until I change with **F3** to non-overlay mode.

https://user-images.githubusercontent.com/1257901/108701129-d85b1200-7507-11eb-824f-2b8f1002954f.mp4

> OS: Debian GNU/Linux 10 (buster) (XFCE/lightdm-xsession)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.0205.23662 +3201 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: 9391fcd19568d635bb290db09f9d616e6acdc4f4
Python version: 3.8.6
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
It is not really the dockable widget size that clips the tree view. It is the tree view column size. There are two options regarding this behavior. If you disable resizable tree column, then the column will auto expand to show everything (but still limited by the dock widget size of course). If you prefer resizable column, you can turn off tree view header hiding.  Note that currently, the tree column size is not remembered. You'll need to change it on every start up. I'll add column size persisting later.

![Screenshot from 2021-02-23 09-23-07](https://user-images.githubusercontent.com/1207888/108791163-65aa6f00-75b9-11eb-835c-bc67e67620b0.png)

**Comment by snelweg** [comment]
@rt Wow, so many options. I didn't think this was adjustable by the user. But you made it configurable, as always you have the user in mind. Thanks for that.
I adjusted the checkboxes and now it works as expected.

thanks!
