### ISSUE TITLE
Sketch creation error with 2012.02.24

### ISSUE THREAD

**Issue by sigxcpu76** [realthunder/FreeCAD_assembly3#477]
File>New
Part Design
Create Body
Create Sketch

error in report:
```
23:12:15  <PartDesign> CommandBody.cpp(148): Ignore selection with no solid shape: Unnamed#Body.
```

Creating a body-less sketch (which is not "the way" since FreeCAD 17, I think) is allowed though.

![image](https://user-images.githubusercontent.com/737085/109066505-d5257900-76f5-11eb-8f1a-ae0ed59f3f54.png)

**Comment by realthunder** [comment]
There is some mis-interpretation of selection when creating the sketch. As a temporary work around, simply clear the selection before creating the sketch.

**Comment by sigxcpu76** [comment]
Is the new way to attach initial sketch intentional after this fix?

Previously, creating a sketch would bring this mode (select feature).
![image](https://user-images.githubusercontent.com/737085/110224189-1da51980-7ee2-11eb-94b3-b5fe078a4df8.png)

After this fix it starts in this mode (select attachment).

![image](https://user-images.githubusercontent.com/737085/110224197-31508000-7ee2-11eb-8776-f74a03ec9748.png)

**Comment by realthunder** [comment]
Yes, it is intentional. The new behavior creates the sketch first, and opens up its attachment editing task panel, which allows you to select not only origin or plane, but also datum. In fact, you can select any object, even those outside of the body, and it will be auto imported into the body.

**Comment by sigxcpu76** [comment]
Got it. It is a bit harder to attach to standard planes. Now you need to open Origin, select a plane, then click "New Sketch". As far as I've seen in various YT videos, that is the workflow with the first sketch in a body. Subsequent sketches can/may have more complex attachment modes.

**Comment by oficinerobotica** [comment]
Tested with:
```OS: KDE neon User Edition 5.21 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.531.24301 +3702 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 4ad819f55a108b7e8bddb134d0de39218e662aa4
Python version: 3.8.10
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)
```
and the issue isn't present anymore.
