### ISSUE TITLE
Discussion: how to merge toponaming back to master branch

### ISSUE THREAD

**Issue by luzpaz** [realthunder/FreeCAD_assembly3#478]
Hi RT, just wanted to start a issue here about a roadmap to merge Toponaming in to FreeCAD master. SInce v0.19 release is immanent...what are your thoughts on how to proceed? Will you do it in a series of PRs?

**Comment by realthunder** [comment]
I prefer doing it in a single PR, but with fine splitted commits for various aspects. The reason is that without those various aspects in place, it is difficult to test. I'll try my best to include only changes relevant to topo naming.

**Comment by luzpaz** [comment]
Happening in https://github.com/FreeCAD/FreeCAD/pull/4752  
Closing ticket
