### ISSUE TITLE
"Select linked object" jumps to deepest object, not to the owner

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#48]
"Select linked object" button jumps to the deepest object, not the immediate owner/parent:

![select-linked-object](https://user-images.githubusercontent.com/6639874/44954217-0d41fd00-aea7-11e8-88d4-a252abee46d4.gif)

Instead, I would expect it to select the nut in the parent external object, `rpi-with-env` in this case: 

![image](https://user-images.githubusercontent.com/6639874/44954236-74f84800-aea7-11e8-8e76-007159b22cf0.png)

While I'm not able to reproduce, the "Select the deepest linked object" seems to jump to the owner, not the deepest.

**Comment by realthunder** [comment]
Pad is not a link per se. The little arrow on the right bottom of the icon means it is an external object brought in indirectly by some parent link. I will change the link select command to enumerate on parent link as well.

**Comment by ceremcem** [comment]
Nicely working!
