### ISSUE TITLE
Is it possible to add "Point On Line" constraint in Sketcher?

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#484]
I needed to constrain that point on the circle: 

![image](https://user-images.githubusercontent.com/6639874/109417207-ad733100-79d3-11eb-9a2b-4468749faee8.png)

Is this currently possible, directly or indirectly?

**Comment by Rabbit-sk** [comment]
Hi @ceremcem, is this what you want to achieve?

https://user-images.githubusercontent.com/74265320/109418646-d098e300-79c9-11eb-9ab8-e27154ccb3b5.mp4

**Comment by ceremcem** [comment]
Ah, yes! I don't know why I tried tangent constraint and then give up :| 

Thanks!
