### ISSUE TITLE
Center to plane constraint example

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#51]
Is it currently possible to create a constraint between the center of the object's edge with a plane? This need is raised while creating a drawing from the following blueprint:

![image](https://user-images.githubusercontent.com/6639874/44970369-0d4f0500-af5a-11e8-9777-db16f32e8f17.png)

The closest option seems `MidPoint` constraint, but I couldn't make it work this way.

**Comment by realthunder** [comment]
I just push a fix for MidPoint constraint. However, if don't need this constraint here. Is this what you want?

![midpoint](https://user-images.githubusercontent.com/1207888/44971544-91b87c80-af88-11e8-8a69-4b7d23cb3377.gif)

**Comment by ceremcem** [comment]
No, I think I totally misunderstood the `MidPoint` constraint (I didn't use it either). 

It's something like the following, only think that at the first click we could select the red point: 

![image](https://user-images.githubusercontent.com/6639874/44973480-63757580-af65-11e8-9280-e69a05fa9e99.png)

![center-to-plane-wip](https://user-images.githubusercontent.com/6639874/44973666-029a6d00-af66-11e8-9003-9658f8449cc4.gif)

**Comment by realthunder** [comment]
> No, I think I totally misunderstood the MidPoint constraint (I couldn't use it either).

Have you synced my asm3 repo?

![midpoint2](https://user-images.githubusercontent.com/1207888/44974294-caa91f00-af91-11e8-916e-2030f8291bb2.gif)

**Comment by realthunder** [comment]
Set the `Offset` property of the plane ElementLink object.

**Comment by ceremcem** [comment]
Thanks! 

Here is the overall example: 

![center-to-plane-example](https://user-images.githubusercontent.com/6639874/44976314-902d8b00-af6d-11e8-9724-ecfc21d87ce3.gif)

**Comment by ceremcem** [comment]
CenterToPlane operation is used so often that it becomes a burden to place a DraftPoint, name it, move to assembly every time. Would you consider adding a constraint for that purpose?

**Comment by realthunder** [comment]
You don't need the draft point or the MidLine constraint at all. You can directly use the edge as the 'Point' in the PointPlaneDistance constraint. Please checkout [here](../wiki/Constraints-and-Solvers#constraining-geometry-element) about various interpretations of a geometry element.

**Comment by ceremcem** [comment]
In the page you referred, an edge is considered as a point by its middle point and that would solve this particular case nicely. But I think there might be a problem, because PointPlaneDistance constraint is disabled when I click the edge:
![edge-as-pointplanedistance](https://user-images.githubusercontent.com/6639874/45101438-20b5c800-b134-11e8-9cb7-c63b8132fee4.gif)

**Comment by ceremcem** [comment]
Nicely works: 

![center-to-plane](https://user-images.githubusercontent.com/6639874/45145556-93bd4e00-b1c9-11e8-8094-44c3a11767ee.gif)
