### ISSUE TITLE
Link placement not updating

### ISSUE THREAD

**Issue by tomster** [realthunder/FreeCAD_assembly3#514]
When I create a link array and edit the individual resulting links, sometimes (not sure yet when and when not) the values are erroneously evaluated to 0 (and the link is not moved as a result) eventhough the formula is evaluated correctly inside the edit dialog
here you can see the value ``0`` next to the formula:
![image](https://user-images.githubusercontent.com/59207/111040081-cb0fb400-8431-11eb-8bdf-0cb21923b18e.png)
but when i edit the value it shows that it correctly is evaluated to 400:
![image](https://user-images.githubusercontent.com/59207/111040124-04482400-8432-11eb-8c24-ddce441b0104.png)
this also happens if i don't use a formula at all and simply use the direct value:
![image](https://user-images.githubusercontent.com/59207/111040249-5c7f2600-8432-11eb-93a6-6ced19160ed0.png)

using 2021.0311

**Comment by tomster** [comment]
update: after restarting the application i could change the ``400`` to ``200`` and it worked immediately (after hitting enter). when i then changed the value back to the formula this was updated, as well
![image](https://user-images.githubusercontent.com/59207/111040514-86851800-8433-11eb-9276-facf0358583e.png)
during all of this (and prio to the restart, as well) there weren't any errors or other log messages on the console.

**Comment by realthunder** [comment]
Can you please attach the whole file here? Are these links inside another assembly, with some constraints?. If so, then there will be some race condition there, as the expression and the assembly solver trying to compete to set the placement of the link.

**Comment by tomster** [comment]
@realthunder you are right. I had competing constraints in the assembly. my strategy is now to not manipulate the placement of the link array members but simply treat the link array feature as a "mulitiplication engine" and perform any placement using constraints. (which then in turn manipulate those placements, if i'm beginning to understand the underlying mechanics?)
