### ISSUE TITLE
Mirror feature keep losing reference plane/face.

### ISSUE THREAD

**Issue by rola22** [realthunder/FreeCAD_assembly3#516]
Hello. Sorry for poor english.

Steps to reproduce this error:
- create new document,
- go to Part Design and create new Body,
- create sketch on any plane,
- draw any shape (i used rectangle), it doesn't matter if it's fully constrained or not,
- pad a sketch,
- create mirror feature, as a reference select one of pad faces, datum plane or origin plane, click ok button,
- edit mirror feature by double clicking it -> reference plane has changed, in my case to Base XY plane.

FreeCAD version: Realthunders Daily release 2021.03.11
System: Windows 10 Pro 64bit, build 19041

This error doesn't occurs in latest daily 0.19 version, tested on Linux Mint 19.3.

**Comment by oficinerobotica** [comment]
Tested with 
```
OS: KDE neon User Edition 5.21 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.531.24301 +3702 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 4ad819f55a108b7e8bddb134d0de39218e662aa4
Python version: 3.8.10
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)
```
and the issue isn't present anymore.
