### ISSUE TITLE
Not retro-compatible with 0.19 Daily

### ISSUE THREAD

**Issue by pierbout** [realthunder/FreeCAD_assembly3#530]
If I open in Real Thunder a file created with "0.19 daily", make a modification, save the file under Real Thunder and then reopen it in 0.19, most objects are called "Unnamed" in the "Model" window and I loose the tree (all objects are at the same level.

Maybe a problem of retro-compatibility of the XML file?

Messages:
11:21:55  XML Attribute: "Ref" not found
11:21:55  XML Attribute: "Ref" not found
11:21:55  XML Attribute: "Ref" not found
11:21:55  XML Attribute: "Ref" not found
11:21:55  XML Attribute: "Ref" not found
11:21:55  XML Attribute: "Ref" not found
11:21:55  XML Attribute: "Ref" not found
11:21:55  XML Attribute: "Ref" not found
11:21:55  XML Attribute: "Ref" not found
11:21:55  XML Attribute: "Ref" not found
11:21:55  XML Attribute: "Ref" not found
11:21:55  XML Attribute: "Ref" not found
11:21:55  XML Attribute: "Ref" not found
11:21:55  Invalid Document.xml: End of document reached
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Enumeration index -1 is out of range, ignore it
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Enumeration index -1 is out of range, ignore it
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Enumeration index -1 is out of range, ignore it
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Enumeration index -1 is out of range, ignore it
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:21:55  SketchObject::onChanged(): Unmanaged change of Constraint Property results in invalid constraint indices
11:21:55  SketchObject::onChanged(): Unmanaged change of Constraint Property results in invalid constraint indices
11:21:55  SketchObject::onChanged(): Unmanaged change of Constraint Property results in invalid constraint indices
11:27:22  XML Attribute: "Ref" not found
11:27:22  XML Attribute: "Ref" not found
11:27:22  XML Attribute: "Ref" not found
11:27:22  XML Attribute: "Ref" not found
11:27:22  XML Attribute: "Ref" not found
11:27:22  XML Attribute: "Ref" not found
11:27:22  XML Attribute: "Ref" not found
11:27:22  XML Attribute: "Ref" not found
11:27:22  XML Attribute: "Ref" not found
11:27:22  XML Attribute: "Ref" not found
11:27:22  XML Attribute: "Ref" not found
11:27:22  XML Attribute: "Ref" not found
11:27:22  XML Attribute: "Ref" not found
11:27:22  Invalid Document.xml: End of document reached
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Enumeration index -1 is out of range, ignore it
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Enumeration index -1 is out of range, ignore it
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Enumeration index -1 is out of range, ignore it
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Enumeration index -1 is out of range, ignore it
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  Extension is not a python addable version: 'PartGui::ViewProviderAttachExtension'
11:27:22  SketchObject::onChanged(): Unmanaged change of Constraint Property results in invalid constraint indices
11:27:22  SketchObject::onChanged(): Unmanaged change of Constraint Property results in invalid constraint indices
11:27:22  SketchObject::onChanged(): Unmanaged change of Constraint Property results in invalid constraint indices

Note: 
- When I open the 0.19 file in real thunder, it says it must recompute. Same result when I say yes or no (if I say yes, the recompute partially fails)
- This is my first install of real thunder. So I don't know if this issue existed previously or not.

**Linux Mint 20
Real Thunder 2021/03/11
Freecad 0.19 revision 22665**

![image](https://user-images.githubusercontent.com/70711916/112133780-53c5e700-8bcc-11eb-9fc6-dc0fff90c22e.png)

**Comment by realthunder** [comment]
You 0.19 download is too old. The `Sketcher` workbench in upstream FreeCAD has a major internal changes recently. You won't be able to restore a sketch saved in the latest upstream either.

**Comment by pierbout** [comment]
I updated the daily, and guess what... it works! Thanks a lot!
