### ISSUE TITLE
opening model from 0.19.1 - recomputation fails

### ISSUE THREAD

**Issue by bob-u** [realthunder/FreeCAD_assembly3#532]
Just FYI: Attached file fails to recompute or after recompute a part of it is missing.
[test2.zip](https://github.com/realthunder/FreeCAD_assembly3/files/6189995/test2.zip)

**Comment by realthunder** [comment]
The upstream FreeCAD PartDesign does not support multiple solid inside a body yet. That's why you get the error. I intend to merge PartDesign change to upstream.
