### ISSUE TITLE
Improvement proposal: Hide all sketches used to create an additive or subtractive feature

### ISSUE THREAD

**Issue by Rabbit-sk** [realthunder/FreeCAD_assembly3#535]
Dear RealThunder,

When an additive pipe, additive loft or subtractive loft,  is created, only one sketch is hidden. I haven't tested all the additive and subtractive features, so maybe this problem also occurs with other features that use more than one sketch. It would be practical if all the sketches used to create an additive or subtractive feature were hidden so that the user did not have to manually hide them. 

![obrázok](https://user-images.githubusercontent.com/74265320/112270542-17e95b00-8c7a-11eb-8e03-efaacb758592.png)
![obrázok](https://user-images.githubusercontent.com/74265320/112272368-67308b00-8c7c-11eb-9844-9abe21f8a438.png)
![obrázok](https://user-images.githubusercontent.com/74265320/112273006-22592400-8c7d-11eb-9374-bdd2d77ad6e1.png)

Best regards

OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.311.24301 +3373 (Git)
Build type: Release
Branch: LinkStage3
Hash: 91ca94db328bf6126c4a01547b6aa2202d876ebc
Python version: 3.6.8
Qt version: 5.12.6
Coin version: 4.0.0a
OCC version: 7.5.0
Locale: Slovak/Slovakia (sk_SK)

**Comment by realthunder** [comment]
The commit [here](https://github.com/realthunder/FreeCAD/commit/1b629a8b03f05df50fbd64637304c3a4782d04b3) fixed this issue. There is a typo in the commit message, so it is not auto shown here.
