### ISSUE TITLE
Missing libraries in the AppImage

### ISSUE THREAD

**Issue by yrabbit** [realthunder/FreeCAD_assembly3#544]
It worked when I found in which packages these libraries and installed them in the main system, but without it FreeCAD AppImage just crashed.
![shot](https://user-images.githubusercontent.com/6075465/112815164-5f7d4600-90c3-11eb-962d-462dfbcfe010.png)

===
libasound.so.2
libxcb-keysyms.so.1
===

**Comment by luzpaz** [comment]
@yrabbit can you still reproduce this?  
No idea what version AppImage you're running here.
