### ISSUE TITLE
Experimental Render Cache cannot be selected

### ISSUE THREAD

**Issue by sslupsky** [realthunder/FreeCAD_assembly3#558]
I downloaded the 0328 Daily for macOS:

OS: macOS 10.16
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.328.24301 +3441 (Git)
Build type: Release
Branch: LinkStage3
Hash: 0a157a307c91d241a370cdda6d8f0471b7c48915
Python version: 3.7.10
Qt version: 5.12.1
Coin version: 4.0.1
OCC version: 7.4.0
Locale: C/Default (C)

When reviewing the release notes, I noticed the following request:
_The Daily branch introduces an experimental renderer that bypasses Coin3D and do its own rendering. It renders much faster than Coin3D for complex and deep assembly hierarchies (works for assembly STEP imports). You can enabled it in Preference -> Display -> Render cache -> Experimental. The renderer does not yet work with nodes that uses texture, e.g. text labels in Draft._

However, that option does not appear in the options for the Render Cache:
![Screen Shot 2021-04-04 at 10 42 02 AM](https://user-images.githubusercontent.com/16888734/113515556-73e19880-9532-11eb-918e-8a771ea3ceba.png)

**Comment by realthunder** [comment]
I haven't made a `Daily` release for either MacOSX or Windows yet. I'll do that soon.
