### ISSUE TITLE
draft move linked object problem

### ISSUE THREAD

**Issue by drom89** [realthunder/FreeCAD_assembly3#564]
Hello Realthunder,

when i try Draft-Move linked object from other file, it dont work is this normal ?  

I mainly using draft move to create assemblies. Now i discovered the Link function so i dont need to copy or clone objects but im stuck at this problem...

![draftmove](https://user-images.githubusercontent.com/5219063/114285043-5f326280-9a54-11eb-8df7-d0cc327ff255.gif)

**Comment by realthunder** [comment]
Can you please provide the sample file shown in the screencast?

**Comment by drom89** [comment]
So it seems that it happens only when i link complete Part, if i link only the body its working.
![draftmove2](https://user-images.githubusercontent.com/5219063/114306225-90a24100-9adb-11eb-9621-29375bddf314.gif)

**Comment by luzpaz** [comment]
@drom89 can you please post you Help > About FreeCAD > `Copy to clipboard` info

**Comment by drom89** [comment]
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.328.24301 +3441 (Git)
Build type: Release
Branch: LinkStage3
Hash: 0a157a307c91d241a370cdda6d8f0471b7c48915
Python version: 3.6.8
Qt version: 5.12.6
Coin version: 4.0.0a
OCC version: 7.5.0
Locale: Czech/Czech Republic (cs_CZ)

**Comment by luzpaz** [comment]
@drom89 Thanks + sample file?

**Comment by luzpaz** [comment]
@drom89 ping

**Comment by nadarbreicq** [comment]
Hi ! Same issue here.

**Comment by realthunder** [comment]
Should be fixed by the above commit.

Please note that, you are not supposed to use `Draft_Move` on features inside body. Select the body instead.
