### ISSUE TITLE
Move tool doesn't move

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#57]
I've downloaded a model [from FreeCAD-library](https://github.com/FreeCAD/FreeCAD-library/blob/master/Electrical%20Parts/electronic-components/headers/1x3-male-pin-header.fcstd) and started editing by adding them into Asm3 container and so on. Now the move tool doesn't seem seem to move some objects: 
![move-tool-fail](https://user-images.githubusercontent.com/6639874/45058489-87d66c80-b0a1-11e8-85fb-2113daa1a3c4.gif)

## File 
[1x3-male-pin-header](https://github.com/realthunder/FreeCAD_assembly3/files/2350268/1x3-male-pin-header.fcstd.remove-extension.zip)

**Comment by realthunder** [comment]
That file is designed using the old version PartDesign. You should migrate it to the new body based design first before adding to assembly. 

Before adding to assembly, simply double click any of the Pad/Pocket feature and choose Migrate.

Or, you can just used the simplified compound, pin-support-array and pin array, without all the modeling history.

**Comment by ceremcem** [comment]
"Migrate"ing has solved the issue.
