### ISSUE TITLE
creating thick body always fails when tapper angle is used

### ISSUE THREAD

**Issue by mwlandolsi** [realthunder/FreeCAD_assembly3#572]
hello dear programmers.
When a body/shape is created with "pad" and the option "Tapper angle is enabled, it will be impossible to make a thick body.
![Screenshot from 2021-04-17 01-20-22](https://user-images.githubusercontent.com/76944804/115095953-21817e00-9f1b-11eb-996d-fc7759b46425.png)
![Screenshot from 2021-04-17 01-21-17](https://user-images.githubusercontent.com/76944804/115095976-3d851f80-9f1b-11eb-98fd-fa1ea957ccd2.png)

**Comment by mwlandolsi** [comment]
I think that I have find a solution how to choose parameters for thin feature for this issue, but not so easy for simple users. It could be an improvement to get a better UX.


used version : 
OS: Linux Mint 19.3 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.504.24301 +3597 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 540995a6e8d5db01dfe2597439ec3131ca69b030
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)

I will show 3 use cases and what kind of parameters should be considered in every case : 
1- just a simple rectangular pad with draft angle , here nothing special to change
![Screenshot from 2021-05-05 04-20-35](https://user-images.githubusercontent.com/76944804/117093599-4d916180-ad59-11eb-8c88-885d7a1347b6.png)


2-a circular pad with tapper angle

 If we proceed like the first case we will get this result : 
![Screenshot from 2021-05-05 04-08-49](https://user-images.githubusercontent.com/76944804/117094597-17a1ac80-ad5c-11eb-88b9-081209e3452a.png)


to get a correct result with thick object, first the parameter "Use pipe for draft" should be "true" while creating pad or in "property view" panel

![Screenshot from 2021-05-05 04-25-04](https://user-images.githubusercontent.com/76944804/117094693-5e8fa200-ad5c-11eb-96ab-a5f126870231.png)
then it will be possible to get a good result
![Screenshot from 2021-05-05 04-45-33](https://user-images.githubusercontent.com/76944804/117094873-db228080-ad5c-11eb-8bcd-a93bca805d0a.png)


3- A rectangular  sketch with fillet between line : 
 first the parameter "Use pipe for draft" should be "true" while creating pad or in "property view" panel
![Screenshot from 2021-05-05 04-34-08](https://user-images.githubusercontent.com/76944804/117094433-b1b52500-ad5b-11eb-96fa-52ee81983576.png)

Here the "joint type" in thickness parameters should be set to "intersection"

![Screenshot from 2021-05-05 04-31-39](https://user-images.githubusercontent.com/76944804/117094417-a95cea00-ad5b-11eb-8962-ae6390a3914a.png)

**Comment by realthunder** [comment]
I actually tried to tackle this issue but couldn't make it work. The problem of your opening post only occurs if the second drafted pad touches the edge of the first pad. I think this might be due to some intrinsic limitation of the thickening algorithm in current OCC. There might be other cases that it will fail.
