### ISSUE TITLE
Rotation around an axis is not resolving formulas as expected

### ISSUE THREAD

**Issue by sirkha** [realthunder/FreeCAD_assembly3#575]
![image](https://user-images.githubusercontent.com/2826011/115123616-24ac5680-9f7b-11eb-89b1-7e014556529f.png)

Not sure if this is the same upstream, but I am trying to get a specific rotation, and the numbers that it actually uses aren't what is returned by formulas. (0.705,0.709,0) instead of (0.707,0.707,0).

**Comment by luzpaz** [comment]
Do you mind confirming on FC master branch as well?

**Comment by sirkha** [comment]
After rebuilding the geometry 2 or three times, it seems to have resolved itself... I am not sure I can reproduce this anywhere. Closing.
