### ISSUE TITLE
Rules Surface error in stable branch 20210412

### ISSUE THREAD

**Issue by CADrock1** [realthunder/FreeCAD_assembly3#576]
Hello Realthunder,

Hope you doing good.

I facing error while creating surface by ruled surface in part workbench. I want to create a surface which should pass though the selected lines, but the surface is being created on different plane as shown in attached image.
I have also attached the freeCAD file. 
Below is my system info.

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.412.24301 +3461 (Git)
Build type: Release
Branch: LinkStage3
Hash: 86b851cf40e8f6999c1b8eec267d5e48207cf376
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/India (en_IN)

Thanks & Regards,
CADrock1
![Ruled surface error](https://user-images.githubusercontent.com/81483384/115132561-0b5ce600-a01f-11eb-9680-aa8c547d308f.PNG)
[Ruled surface error.zip](https://github.com/realthunder/FreeCAD_assembly3/files/6330410/Ruled.surface.error.zip)

**Comment by oficinerobotica** [comment]
Tested the example file with:
```OS: KDE neon User Edition 5.21 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.531.24301 +3702 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 4ad819f55a108b7e8bddb134d0de39218e662aa4
Python version: 3.8.10
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)
```
and the issue is fixed
