### ISSUE TITLE
Scrolling 3d view accidentally when using transparent overlay for tree (combo) view

### ISSUE THREAD

**Issue by kevenwyld** [realthunder/FreeCAD_assembly3#578]
When using transparent overlay for the combo view (tree view??) pane it is possible (and for me quite common) to start scrolling with the mouse wheel in the combo view and suddenly be zooming the 3d view without any cursor movement since the cursor will eventually reach an area where there is no text.  I've included a video to demonstrate:

https://user-images.githubusercontent.com/11936535/115643678-75ed7a80-a2da-11eb-8749-165a44c4ec67.mp4

I'm not sure if it's even possible to do anything about this (I have no experience with UI development) but it seems like a good solution would be to only scroll the combo view, or any of the transparent panes, when your cursor is over the entire rectangle of the transparent pane, not just where there is text visible.

Let me know if you'd like more information.

```
OS: Arch Linux (i3/i3)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.412.22506 +5327 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: d41e78fe7f9b54eea5977df0a7344331f08445e8
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)
```

EDIT:  To include version information

**Comment by realthunder** [comment]
I have added setting to add some mouse wheel pass through delay. 

![Screenshot from 2021-04-23 09-17-38](https://user-images.githubusercontent.com/1207888/115804860-6d01c380-a416-11eb-92b8-53d5976dff61.png)

**Comment by kevenwyld** [comment]
@realthunder Thank you, this is very good.  I admit I also did not notice the `Auto mouse wheel pass through` setting which is helpful as well though the timeout is much more natural.  Thanks for your excellent work as always!

**Comment by realthunder** [comment]
You're welcome. You might also want to try to add some background to the tree items for better visibility. It's at the top of this UI setting page. Click the color selection dialog, and add some alpha (i.e. opaqueness).

![Screenshot from 2021-04-23 10-03-08](https://user-images.githubusercontent.com/1207888/115807656-a38e0d00-a41b-11eb-9874-8680f19daba9.png)

**Comment by kevenwyld** [comment]
Yes that does make things easier to read when the part is behind the tree.  Thanks
