### ISSUE TITLE
Array creation problem

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#58]
![array-problem](https://user-images.githubusercontent.com/6639874/45085107-88eeb480-b108-11e8-9779-4af892bcf6ad.gif)

File: [1x2-male-pin-header.fcstd.remove-extension.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2352176/1x2-male-pin-header.fcstd.remove-extension.zip)

I guess we should use "Create Link Array" for the parts which surrounded with Assembly Container, "Create Array" for regular parts. Is that true?

Despite the thrown exception, it seems to work anyway:

![image](https://user-images.githubusercontent.com/6639874/45086861-dec55b80-b10c-11e8-97d4-dd602794b8a2.png)

**Comment by realthunder** [comment]
This is a bug. Will fix soon. Difference between DraftArray and DraftLinkArray is that the later is more efficient, as it does not store duplicate shape to files, but re-create the array during restore.

BTW, if you don't need pattern, then you can also make array using a normal link. Right click the object in tree view, select `Link actions -> Create link`. If you have already added a part to assembly, then use `Replace with a link`. After that, change the `ElementCount` property of the link to make an array.

**Comment by ceremcem** [comment]
Array can't be recognized by Asm3 constraints: 

![array-is-not-recognized](https://user-images.githubusercontent.com/6639874/45121277-50cb8e00-b169-11e8-972e-434f3e23a7bc.gif)

What would be the reason?


[case-v3.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2354596/case-v3.zip)

**Comment by ceremcem** [comment]
I think this issue must be reopened since array links can not be recognized as described above.

**Comment by realthunder** [comment]
I just tried the attached file. The constraint buttons is activated as expected.

**Comment by ceremcem** [comment]
Am I missing something: ![array-movement-problem](https://user-images.githubusercontent.com/6639874/46063948-b2828500-c176-11e8-807b-7e7385a1795a.gif)
[array-problem-20180926T1028.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2418554/array-problem-20180926T1028.zip)
