### ISSUE TITLE
UX : Sketch constraint does not change when another constraint is choosen

### ISSUE THREAD

**Issue by mwlandolsi** [realthunder/FreeCAD_assembly3#584]
Hello everybody;
I do not know if this is a change in the way that user can pick a constraint from the menu bar. But I noticed that when I choose a constraint, for example horizontal dimension, and then I click on vertical constraint button, it still remains on horizontal, and does not change to vertical. I must click on the right button of the mouse or on "esc" key and then pick the other constraint.
This issue did not exist in older releases.

https://user-images.githubusercontent.com/76944804/115955665-d6093a00-a4ef-11eb-9863-be5a2c86cefb.mp4

**Comment by herrgerd** [comment]
Yepp, seems to be a bug. See #583

**Comment by herrgerd** [comment]
Thanks for fixing @realthunder!

**Comment by mwlandolsi** [comment]
thanks to all. the issue is solved.
