### ISSUE TITLE
puzzling display issues when assembly frozen

### ISSUE THREAD

**Issue by bambukouk** [realthunder/FreeCAD_assembly3#590]
Using:
`OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.328.24301 +3441 (Git)
Build type: Release
Branch: LinkStage3
Hash: 0a157a307c91d241a370cdda6d8f0471b7c48915
Python version: 3.6.8
Qt version: 5.12.6
Coin version: 4.0.0a
OCC version: 7.5.0
Locale: English/United Kingdom (en_GB)
`
I am having issues with displaying of frozen assembly.
Pics below (with comments) explain what I am experiencing:
![01](https://user-images.githubusercontent.com/50301871/116778342-43294c00-aa69-11eb-934b-bce975caf9d4.jpg)
![02](https://user-images.githubusercontent.com/50301871/116778345-458ba600-aa69-11eb-855d-552a76091f7d.jpg)
![03](https://user-images.githubusercontent.com/50301871/116778347-47ee0000-aa69-11eb-9bde-1f16809a3a23.jpg)
![04](https://user-images.githubusercontent.com/50301871/116778348-49b7c380-aa69-11eb-8319-785318bc0b2e.jpg)
![05](https://user-images.githubusercontent.com/50301871/116778355-50ded180-aa69-11eb-8793-8594ab3c4fe2.jpg)
![06](https://user-images.githubusercontent.com/50301871/116778356-53412b80-aa69-11eb-8764-97aa7e0ae858.jpg)
![07](https://user-images.githubusercontent.com/50301871/116778358-550aef00-aa69-11eb-9202-74d1876c733c.jpg)

**Comment by realthunder** [comment]
Can you please send me your model file?

**Comment by bambukouk** [comment]
Thank you very much!
You have an email with attachment.

**Comment by realthunder** [comment]
Just notice that you are still using 0328 release. Please update to the latest 0501 release. The color lost problem has been fixed.

**Comment by bambukouk** [comment]
I was just downloading it 👍 
and yes - it works fine in the latest:

`OS: Windows 10 Version 1909
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.501.24301 +3583 (Git)
`

Big thank you again!

**Comment by bambukouk** [comment]
Hi @realthunder 
I am afraid, the issue re-appeared again....
I have an assembly, consisting of a number of sub-assemblies.
Freezing of sub-assemblies is no problem at all, but when I try (after freezing all of the sub-assemblies) to freeze top assembly, it goes grey.
![un-frozen_result](https://user-images.githubusercontent.com/50301871/142448064-c67dcf55-645f-4a18-933a-9955367ce8c4.png)
![frozen_result](https://user-images.githubusercontent.com/50301871/142448129-2feb18a4-6847-4127-a6b5-2bb794857328.png)

I am using latest daily:
`OS: elementary OS 6 Odin (Pantheon/pantheon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.1015.24301 +4280 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 556c87868ea46796242156e9f73eae98259794b7
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)
`
I have attached original file (re-named .zip to allow inserting here)
[for_rt.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7564063/for_rt.zip)

**Comment by bambukouk** [comment]
@realthunder  
I can confirm (having tested it on other files) that freezing of assembly with frozen sub-assemblies as it's parts leads to this problem :-1: 
You can only have "one level" of freezing if this display issue is to be avoided

**Comment by bambukouk** [comment]
Thank you!!
Look forward to all these changes in the next release :+1:
