### ISSUE TITLE
Unable to select origin point

### ISSUE THREAD

**Issue by mwlandolsi** [realthunder/FreeCAD_assembly3#591]
Just create a sketch draw a circle for example and try to put the center of the circle coincident with the origin.
that's all.
![Screenshot from 2021-05-02 05-01-31](https://user-images.githubusercontent.com/76944804/116801831-3f4b0780-ab05-11eb-99d4-845b56e2039a.png)

OS: Linux Mint 19.3 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.501.24301 +3583 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 478b44886569e8934ee571e285b974a58ba5e890
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by herrgerd** [comment]
Can confirm this:
![confirm](https://user-images.githubusercontent.com/24494466/116810614-02066a00-ab45-11eb-9766-da1f684502af.gif)

OS: Windows 10 Version 2004
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.501.24301 +3583 (Git)
Build type: Release
Branch: LinkDaily
Hash: 478b44886569e8934ee571e285b974a58ba5e890
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: German/Germany (de_DE)

**Comment by dingolino** [comment]
Same here.
If you add for example 2 circles and if you select 1 centre point and move over to the other circle centre point than the origin centre point is "highlighted" but you can mark the centre point of the 2nd circle.

Best regards,

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.501.24301 +3583 (Git)
Build type: Release
Branch: LinkDaily
Hash: 478b44886569e8934ee571e285b974a58ba5e890
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: German/Germany (de_DE)

**Comment by herrgerd** [comment]
Hey @realthunder it works again. Thank you!

**Comment by mwlandolsi** [comment]
> Hey @realthunder it works again. Thank you!

Haw to get the fixed version ?

**Comment by herrgerd** [comment]
> 
> 
> > Hey @realthunder it works again. Thank you!
> 
> Haw to get the fixed version ?

here: https://github.com/realthunder/FreeCAD_assembly3/releases

**Comment by mwlandolsi** [comment]
Many thans

> > > Hey @realthunder it works again. Thank you!
> > 
> > 
> > Haw to get the fixed version ?
> 
> here: https://github.com/realthunder/FreeCAD_assembly3/releases

Many thanks

**Comment by herrgerd** [comment]
> 
> 
> Many thans
> 
> > > > Hey @realthunder it works again. Thank you!
> > > 
> > > 
> > > Haw to get the fixed version ?
> > 
> > 
> > here: https://github.com/realthunder/FreeCAD_assembly3/releases
> 
> Many thanks

You're welcome! You can close your own threads/issues by pushing the red button left to the green "Comment" button.
That way the issues counter drops by one, which is quite a rewarding thing for @realthunder I think :)

**Comment by mwlandolsi** [comment]
Nice job, 
many thanks to all and to @realthunder
