### ISSUE TITLE
Datum plane normal to spline on selected vertex not working

### ISSUE THREAD

**Issue by mwlandolsi** [realthunder/FreeCAD_assembly3#596]
Hello everybody.
Could any one help me how to create a datum plane normal to curve (spline) at a specific vertex ?
here is the result I could obtain !

https://user-images.githubusercontent.com/76944804/117097391-699a0080-ad63-11eb-9aea-2053295e16fe.mp4

[datum plane on spline.FCStd.zip](https://github.com/realthunder/FreeCAD_assembly3/files/6425089/datum.plane.on.spline.FCStd.zip)

To open the file just rename and remove the .zip extension from file name.

OS: Linux Mint 19.3 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.504.24301 +3597 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 540995a6e8d5db01dfe2597439ec3131ca69b030
Python version: 3.8.8
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
There is a bug in attacher Vertex selection which is fixed by the above commit. You should be able to achieve that by simply select attaching type `Normal to edge`, and then select the edge and vertex.

**Comment by mwlandolsi** [comment]
Many thanks,

**Comment by mwlandolsi** [comment]
Thank you, the problem is solved.
