### ISSUE TITLE
Sync placement note in wiki

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#60]
In https://github.com/realthunder/FreeCAD_assembly3/wiki/Concepts#coordinate-system the following claim is stated:

> When an object is added to an assembly with some placement, the object is seemingly jumping into a new place. 

which might need a small refactoring, since this behavior is lately changed by https://github.com/realthunder/FreeCAD_assembly3/issues/39

**Comment by realthunder** [comment]
Document updated.
