### ISSUE TITLE
Image workbench: Create a planar image in the 3D space crashes freecad

### ISSUE THREAD

**Issue by Miksu80** [realthunder/FreeCAD_assembly3#608]
Create new empty document -> go to Image -WB -> Press "Create a planar image in the 3D space" -> select .jpg -> ok -> "Illegal storage access, please save your work under a new file name and restart the application!" and FreeCAD crashes. No matter if saved in different file name etc. it just crashes.

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.504.24301 +3597 (Git)
Build type: Release
Branch: LinkDaily
Hash: 540995a6e8d5db01dfe2597439ec3131ca69b030
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/Finland (en_FI)

**Comment by bambukouk** [comment]
@Miksu80 
Don't seem to have the same problem?
See attached (below) video - is this what you are doing?
[2021-05-11 09-46-22.zip](https://github.com/realthunder/FreeCAD_assembly3/files/6457798/2021-05-11.09-46-22.zip)

`OS: Windows 10 Version 1909
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.504.24301 +3511 (Git)
Build type: Release
Branch: LinkStage3
Hash: b8cd87c34a66a8f7a8177f483cebf79e29273813
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United Kingdom (en_GB)

**Comment by realthunder** [comment]
The crash should only happen if you are using the `Experimental` render caching. Change back to `Auto` shall make it work now. I've already fixed the crash in the above referenced commit.

**Comment by Miksu80** [comment]
Fixed by realthunder. Thanks!
