### ISSUE TITLE
Experimental renderer renders parts transparently

### ISSUE THREAD

**Issue by herrgerd** [realthunder/FreeCAD_assembly3#613]
Hi @realthunder,
maybe this is a known behaviour, but I guess it should be the same between different renderers.

Experimental:
![grafik](https://user-images.githubusercontent.com/24494466/118113374-80d19180-b3e6-11eb-9384-9ef4abcf3e77.png)

"Auto":
![grafik](https://user-images.githubusercontent.com/24494466/118113441-9a72d900-b3e6-11eb-837f-c3dbae26f12b.png)

Here's the rest of the settings:
![grafik](https://user-images.githubusercontent.com/24494466/118113624-cd1cd180-b3e6-11eb-99f5-5f8aa204348d.png)

Is this a bug?

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.513.24301 +3631 (Git)
Build type: Release
Branch: LinkDaily
Hash: 8d53c82eb6383765aca63667e2a4a070a18bdd2d
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: German/Germany (de_DE)

**Comment by realthunder** [comment]
Can you please share the model file? BTW, I see you have `Use OpenGL VBO` disabled. You probably want to enable this option to see huge improvement in graphics performance for large models.

**Comment by herrgerd** [comment]
> 
> 
> Can you please share the model file? BTW, I see you have `Use OpenGL VBO` disabled. You probably want to enable this option to see huge improvement in graphics performance for large models.

I had to "re-create" the situation and found that it only happens when I re-use geometry to have two (or more) overlaying additive pipe features, see sketch attached.

Maybe this is not the nicest way to do things, but I like it because I can use one sketch without any projected external geometry or binders etc.

[addPipeTransparent.zip](https://github.com/realthunder/FreeCAD_assembly3/files/6485438/addPipeTransparent.zip)

Cheers, Jan

**Comment by herrgerd** [comment]
@realthunder does seem to be fixed in 5.19. Thank you!
