### ISSUE TITLE
(linkdaily) Property view becomes invisible when hovered over

### ISSUE THREAD

**Issue by jdblack** [realthunder/FreeCAD_assembly3#619]
Hi Guys,

I've been having some difficult using link daily over the last couple of months due to  the font colors changing whenever I hover over  the views tabs on the left.    Clicking on a view causes the  font and background to turn to white on white, which makes it touch to use.

I suspect this is happening because I use the dark theme on mac. Is there a way to disable dynamic color changing for the view menus on the left? 

![Screen Shot 2021-05-15 at 1 53 23 PM](https://user-images.githubusercontent.com/1109549/118377893-f2dfdd00-b584-11eb-8df3-2b7ffc8f6b5a.png)

OS: macOS 11.2
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.513.24301 +3631 (Git)
Build type: Release
Branch: LinkDaily
Hash: 8d53c82eb6383765aca63667e2a4a070a18bdd2d
Python version: 3.9.4
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

![Screen Shot 2021-05-15 at 1 46 27 PM](https://user-images.githubusercontent.com/1109549/118377741-0c345980-b584-11eb-90d5-f49dfee34530.png)
![Screen Shot 2021-05-15 at 1 46 39 PM](https://user-images.githubusercontent.com/1109549/118377743-0d658680-b584-11eb-8250-77805767cfc5.png)

**Comment by realthunder** [comment]
Please change the `Overlay stylesheet` to dark theme. By default, it is set to `Auto`, and will auto choose a dark theme if the application theme contains the keyword `Dark`. Maybe you are using your own theme without the keyword? Anyway, you might want to try the `Dark-Outline` theme, and change some treeview settings to make it more visually appealing as shown below.

![Screenshot from 2021-05-16 06-16-28](https://user-images.githubusercontent.com/1207888/118379839-3fbcc580-b610-11eb-89a6-81bde191d066.png)
![Screenshot from 2021-05-16 06-17-14](https://user-images.githubusercontent.com/1207888/118379841-421f1f80-b610-11eb-9ffc-7881c264c450.png)

**Comment by jdblack** [comment]
Oh thank you!  Changing overlay style sheet alone made a huge difference!
