### ISSUE TITLE
Part design: Hole thread clearance does not work directly from input dialogue.

### ISSUE THREAD

**Issue by Miksu80** [realthunder/FreeCAD_assembly3#625]
For some reason when using threads, you can't modify it's clearance as it is greyed out.

![image](https://user-images.githubusercontent.com/48354615/118965227-1c2baf00-b971-11eb-8a07-31066f3bc593.png)

When entering from parameters, it works:
![image](https://user-images.githubusercontent.com/48354615/118967243-29499d80-b973-11eb-94a8-453b9e7778cb.png)

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.519.24301 +3652 (Git)
Build type: Release
Branch: LinkDaily
Hash: 766fd735b25889fecffcebe42b9d69bd24cf4006
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/Finland (en_FI)

**Comment by bambukouk** [comment]
Checked 0.20 and can confirm that it is OK there, so definitely Link branch only.

**Comment by herrgerd** [comment]
Can confirm for:
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.519.24301 +3652 (Git)
Build type: Release
Branch: LinkDaily
Hash: 766fd735b25889fecffcebe42b9d69bd24cf4006
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: German/Germany (de_DE)

**Comment by Miksu80** [comment]
@realthunder can I just close this when you have done a commit that references this? I'm quite new on git and don't know how these work :)

**Comment by realthunder** [comment]
Sure, you can close if you think it is resolved.

**Comment by Miksu80** [comment]
Should be ok
