### ISSUE TITLE
Using external geometry constraints in Sketcher in the assembly time

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#63]
Is it possible to use external geometry to define constraints? Like https://www.freecadweb.org/wiki/Sketcher_External, but will handle the following case: 

![external-geometry-on-assembly](https://user-images.githubusercontent.com/6639874/45158649-4a7ef580-b1ed-11e8-903f-17ed828b88fd.gif)

**Comment by realthunder** [comment]
The same restriction applies, 1) the object must be in the same document, 2) the object must be in the same coordinate space as the sketch. You can use binder to achieve both.

**Comment by ceremcem** [comment]
Here is a small "Projection Constraints" tutorial:

![projection-constraints](https://user-images.githubusercontent.com/6639874/45179372-01489900-b221-11e8-94a1-2bb504a1a038.gif)
