### ISSUE TITLE
Treeview disable auto solid group does not work

### ISSUE THREAD

**Issue by Miksu80** [realthunder/FreeCAD_assembly3#646]
When activating auto solid group, solids are gathered correctly so that every solid is found under last active solid. When selecting disable auto solid group, treeview doesn't change at all.

![image](https://user-images.githubusercontent.com/48354615/120286320-c76c2a80-c2c6-11eb-8399-08eb23f8c065.png)

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.531.24301 +3702 (Git)
Build type: Release
Branch: LinkDaily
Hash: 4ad819f55a108b7e8bddb134d0de39218e662aa4
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/Finland (en_FI)

**Comment by realthunder** [comment]
This is by design. The user is free to ungroup any existing groups after enabling `Auto solid group`, so disabling this option won't affect any existing groups. It just stops auto grouping new features. You ungroup any features by right click that feature and choose `Ungroup solid features`.

**Comment by Miksu80** [comment]
Designed to work this way, user-error detected :)
