### ISSUE TITLE
sketcher export geometries copy body brocken

### ISSUE THREAD

**Issue by dulouie** [realthunder/FreeCAD_assembly3#65]
Use sketcher export geometries tool in a bigger part and make a copy.
In the copy exported sketches are brocken.

![sktechexport_copy.gif](https://github.com/dulouie/screencast/raw/master/sktechexport_copy.gif)

**Comment by realthunder** [comment]
Can you please attach the file showing this problem?

**Comment by dulouie** [comment]
This is for work, i can't share it but i can try to reproduce it with another file.

**Comment by dulouie** [comment]
I think it is this bug:
https://www.freecadweb.org/tracker/view.php?id=3149
