### ISSUE TITLE
[Experimental Render] HiddenLine draw style flips face normal shading.

### ISSUE THREAD

**Issue by oficinerobotica** [realthunder/FreeCAD_assembly3#654]
If transparency is set to 0 and override face colors is checked in Edit->Preferences->Display-Draw styles-> Hidden Lines when switching to "HiddenLine" draw style,  the model faces will be displayed black (flipped normals?) . Toggling on/off "override face color" in preferences will display the model correctly. 
If using the clipping plane, toggling "invert fill color" will have the same effect. The model will be displayed black or with the correct color. This issue isn't present if the renderer is set to auto.
![faceNormal](https://user-images.githubusercontent.com/26909793/120913592-6a8ebc80-c698-11eb-8eb2-7a62e026048a.jpeg)

```
OS: KDE neon User Edition 5.21 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.531.24301 +3702 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 4ad819f55a108b7e8bddb134d0de39218e662aa4
Python version: 3.8.10
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)
```

**Comment by herrgerd** [comment]
I had a similar problem while editing sketches and using the `section view` command in sketcher.
When selecting, everything turns into a black square.
![grafik](https://user-images.githubusercontent.com/24494466/120915358-7338c000-c6a3-11eb-97b8-9642bce9e982.png)

![blackSquare](https://user-images.githubusercontent.com/24494466/120915277-2ce36100-c6a3-11eb-83f3-df3613df7525.gif)

For me, this happens only with the Experimental renderer. Setting it to Auto there's no flaw here...

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.531.24301 +3702 (Git)
Build type: Release
Branch: LinkDaily
Hash: 4ad819f55a108b7e8bddb134d0de39218e662aa4
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: German/Germany (de_DE)

**Comment by realthunder** [comment]
@oficinerobotica I couldn't reproduce the problem. Can you show me your hidden draw style settings, and the relevant model that having this problem?

@herrgerd These are probably two separate issues. Do you always get the all black when selecting or it just happen when you flip the sketch? I did notice this problem before as well, but it only happens when the sketch is flipped, i.e. edited from the bottom view. I am having hard time to trace out the cause of this problem, though. I suspect it could some Qt OpenGL problem at play.

**Comment by oficinerobotica** [comment]
Attached the test file and link.user.cfg . Toggling "override face color" in the draw style preferences will display the model correctly .
![flipedNormals](https://user-images.githubusercontent.com/26909793/121470845-0da84480-c9bf-11eb-84f4-e900ca1e8e7c.jpeg)

[fcstd_and_config.zip](https://github.com/realthunder/FreeCAD_assembly3/files/6628624/fcstd_and_config.zip)

**Comment by oficinerobotica** [comment]
Tested with
```
OS: KDE neon User Edition 5.22 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.615.24301 +3747 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: ecbfba008c481db4cb17bf8bd514b2d12690a8e5
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)
```
and the issue isn't present any more.
