### ISSUE TITLE
PartDesign SubShapeBinder sketch attachment to external geometry error.

### ISSUE THREAD

**Issue by oficinerobotica** [realthunder/FreeCAD_assembly3#655]
I really like the way new sketches can be attached but if: 
-clear selection -> create sketch tool in PartDesign
-select geometry on a different body
-the created subshape binder will give the error "<Exception> SubShapeBinder.cpp(1271): Failed to deduce bound geometry"

It works if the SubShapeBinder is created prior to the sketch then selected in the attachment dialog.
![BoundGeometry](https://user-images.githubusercontent.com/26909793/120969385-64691080-c76a-11eb-99ff-7647be301116.jpeg)

```
OS: KDE neon User Edition 5.21 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.531.24301 +3702 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 4ad819f55a108b7e8bddb134d0de39218e662aa4
Python version: 3.8.10
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.4.0
Locale: English/United States (en_US)
```

**Comment by realthunder** [comment]
I can't reproduce the problem. Can you please send me a project just before you create the sketch, and tell me which face you want to attach.

**Comment by oficinerobotica** [comment]
In the attached file the active body is the cylinder. The selected face is on the box.
![BoundGeometry1](https://user-images.githubusercontent.com/26909793/121129674-94c5b300-c82d-11eb-8e7b-9441d375e5b4.jpeg)


[boundGeometry.zip](https://github.com/realthunder/FreeCAD_assembly3/files/6613707/boundGeometry.zip)

**Comment by oficinerobotica** [comment]
Fixed in 
```
OS: KDE neon User Edition 5.22 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.615.24301 +3747 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: ecbfba008c481db4cb17bf8bd514b2d12690a8e5
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)
```

![sketch](https://user-images.githubusercontent.com/26909793/122332967-b0b90b00-cf37-11eb-9595-5a21520d47d7.jpeg)
