### ISSUE TITLE
sketcher export geometries dosen't work with KiCad StepUp

### ISSUE THREAD

**Issue by dulouie** [realthunder/FreeCAD_assembly3#66]
I want to use sketcher export geometries for pcb-edges in kicad. Is the issue related to the sketcher export tool or to stepUp from easyw?

Select the exported sketch from sketcher and use "push & pull pcb edges"

**Comment by realthunder** [comment]
@easyw Could you please look at this? I think maybe you can relax the type of Part::Part2DObject? Instead of relying on `TypeId`, you can check using `obj.isDerivedFrom('Part::Part2DObject')`

**Comment by easyw** [comment]
May I have an example file and a screencast to understand the @dulouie issue better?

**Comment by easyw** [comment]
ok, I see what an exported sketch is... it is not a Sketch 😄 
You can simply use the kSU button to convert it to a sketch, then Pull it to kicad 😸 
![convert-exported-sketch-to-sketch](https://user-images.githubusercontent.com/3032347/45222915-10c5f180-b2b6-11e8-8ee2-201dd9855755.png)

**Comment by dulouie** [comment]
Ah okay..thank you that works for me:)

Another question to realthunder: Is it possible to export external reference?
Because https://github.com/FreeCAD/FreeCAD/pull/1421 is not been merged yet.

**Comment by dulouie** [comment]
Nice, in my memories it dosen't work with external references, but okay now it works.
This drive me to the next bug related with shapebinder and external ref, i create a new issue for that.
