### ISSUE TITLE
sketcher export geometries selection menu brocken

### ISSUE THREAD

**Issue by dulouie** [realthunder/FreeCAD_assembly3#67]
Using 3D view for selection to export works but not the menu.

![sketchexport](https://github.com/dulouie/screencast/raw/master/skechexport_brocken.gif)

https://github.com/dulouie/screencast/raw/master/sketchexport_brocken.fcstd

**Comment by realthunder** [comment]
Are you referring the not update problem? I have just pushed some commit to fix an update problem. If you are building my LinkStage3 branch, you can sync and try.

**Comment by dulouie** [comment]
This had been fixed.
