### ISSUE TITLE
shape does not change when sketch is changed in groove

### ISSUE THREAD

**Issue by mwlandolsi** [realthunder/FreeCAD_assembly3#673]
Hello,
When I create a groove function with a sketch, the operation is done ok. but when I change the sketch and even click on rebuild, the shape does not change.
this example shows the change of the sketch support surface offset
![deepin-screen-recorder_nemo_20210616112558](https://user-images.githubusercontent.com/76944804/122206123-eeb32200-ce98-11eb-81f1-027c7ea7878a.gif)
this example shows the change of the sketch from ellipse to circle :
![deepin-screen-recorder_FreeCADLink_20210616115123](https://user-images.githubusercontent.com/76944804/122207435-0c34bb80-ce9a-11eb-88c4-6c1f4526d914.gif)

tested on many versions of freecad and on : 

OS: Linux Mint 20.1 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.615.24301 +3747 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: ecbfba008c481db4cb17bf8bd514b2d12690a8e5
Python version: 3.9.4
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)

**Comment by mwlandolsi** [comment]
could anyone confirm this  bug?

**Comment by kevenwyld** [comment]
can you provide an example file?

**Comment by realthunder** [comment]
Yes, this is a bug. Thanks for reporting. It's been fixed in realthunder/FreeCAD@a3452b43191411e89deadf6bfb4a7f89a2a86590.

**Comment by mwlandolsi** [comment]
Thanks for your emprovement. Have a nice day.
