### ISSUE TITLE
To change selection method to default in Linkbranch 14-06-21 (Stable and daily)

### ISSUE THREAD

**Issue by CADrock1** [realthunder/FreeCAD_assembly3#679]
Hello realthunder,

Thanks for the making FreeCAD very useful.

I want to know how to change selection method to default so that all bodies get highlighted on selection. Please see attached screenshots.
![Selection issue pic 1](https://user-images.githubusercontent.com/81483384/122557726-cd019880-d05a-11eb-9202-d0345f993bba.PNG)
![Selection issue pic 2](https://user-images.githubusercontent.com/81483384/122557730-cecb5c00-d05a-11eb-94e7-b81e31fa1600.PNG)

Here is system infos:

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.614.24301 +3584 (Git)
Build type: Release
Branch: LinkStage3
Hash: d1e4d1c5abdedda669e54d1a41b5c08077f7e561
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/India (en_IN)

Thanks & regards,
CADrock1

**Comment by realthunder** [comment]
I think you accidentally turned on `Show selection bounding box` option as shown below. There many other selection style options grouped in that toolbutton.

![Screenshot from 2021-06-18 20-20-13](https://user-images.githubusercontent.com/1207888/122560085-ba935900-d072-11eb-804d-91bc04a3d298.png)

**Comment by CADrock1** [comment]
Yes you right, Thanks for quick reply.
