### ISSUE TITLE
Sketcher/dimension formulas created in Link do not work in 0.20

### ISSUE THREAD

**Issue by bambukouk** [realthunder/FreeCAD_assembly3#680]
There is a difference when creating a formulas for dimension in a sketch between Link branch and Main branch, that causes problems when moving between branches.
Is there any particular reason for it? or is it simply an accidental difference?

`OS: Windows 10 Version 2004
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.614.24301 +3747 (Git)
Build type: Release
Branch: LinkDaily
Hash: ecbfba008c481db4cb17bf8bd514b2d12690a8e5
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United Kingdom (en_GB)
`

**Comment by realthunder** [comment]
It depends on the content of the expression. The Link branch support extended expression syntax which may not be supported in upstream. Can you post a file which has trouble loading in upstream?

**Comment by bambukouk** [comment]
Thank you @realthunder 
I have stripped down the file to leave just the sketch with problematic formulas.

Here is what it looks like in Link branch:

![formula1](https://user-images.githubusercontent.com/50301871/122671699-db1cf980-d1bf-11eb-9b79-48190c9b3ed0.jpg)

and the same sketch when opened in FreeCAD 0.20:

![formula2](https://user-images.githubusercontent.com/50301871/122671726-f38d1400-d1bf-11eb-924b-74fe77ce5009.jpg)

and the file (renamed .zip to permit attaching):

[formula_problem.zip](https://github.com/realthunder/FreeCAD_assembly3/files/6682161/formula_problem.zip)

**Comment by bambukouk** [comment]
Thank you @realthunder
