### ISSUE TITLE
Question: Using subshape binder as additive or subtractive feature

### ISSUE THREAD

**Issue by ngocminhdao88** [realthunder/FreeCAD_assembly3#686]
How i can use subshapebinder as additive or subtractive feature in PartDesign?

Small example here. I want to use subshapebinder of Pad 1 to cut a hole or create a pad into or onto Pad 2.

![image](https://user-images.githubusercontent.com/16566961/122808199-da25be00-d2cc-11eb-8c7d-fd4f9379a06a.png)

Here is the use case in big, complex pattern creation, software used -> PTC ProEngineer
https://www.youtube.com/watch?v=6d2eIY6CLY4

**Comment by realthunder** [comment]
You can use the PartDesign Boolean feature for that.

**Comment by bgamari** [comment]
As @realthunder says, I usually just create a simple Boolean Fuse feature for this.

**Comment by ngocminhdao88** [comment]
Thank you both for the answer.
