### ISSUE TITLE
Modeled threads break after changing properties

### ISSUE THREAD

**Issue by herrgerd** [realthunder/FreeCAD_assembly3#705]
Hi @realthunder,
Threaded holes lose all their properties, when you re-open the properties and change any field there.

![threads](https://user-images.githubusercontent.com/24494466/124391795-849cd880-dcf2-11eb-8379-328f0c6987a4.gif)

The dialog looks like this afterwards:
![grafik](https://user-images.githubusercontent.com/24494466/124391841-b9109480-dcf2-11eb-8915-48585647974a.png)

While you're at it, it would be super sweet if you could stop the re-calculation till the dialog closes. Threads can take a long time to calculate, especially if you need to change a few fields (which you always need to : ) )

**Hint:** I guess I found the bug: When re-opening the properties, the `Profile` is always reset to `none`.

**Workaround:**
It works from the Data/Properties Tab:
![grafik](https://user-images.githubusercontent.com/24494466/124396526-6e027b80-dd0a-11eb-9e78-d570533ebe77.png)

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.614.24301 +3747 (Git)
Build type: Release
Branch: LinkDaily
Hash: ecbfba008c481db4cb17bf8bd514b2d12690a8e5
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: German/Germany (de_DE)

**Comment by realthunder** [comment]
Thanks for the detailed report. The problem is fixed. To stop view update while editing, simply uncheck the `Update view` option. Check again to see the result.

**Comment by herrgerd** [comment]
@realthunder works like expected now. THANK YOU!
