### ISSUE TITLE
Unable to create external constraint for radius only

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#72]
**Urgency:** Low 

# Description 

I think this is not my fault: 

![unable-to-create-radius-external-constraint](https://user-images.githubusercontent.com/6639874/45222197-7ae19500-b2bc-11e8-8883-2709c8d420ea.gif)

**Comment by realthunder** [comment]
The message means as it is, the geometry is not supported yet. It looks like an arc, but may in fact be a bspline.

**Comment by ceremcem** [comment]
Currently (as of `56a7e743`) I can not reproduce this problem.
