### ISSUE TITLE
Unable to disable "Draft tray" Toolbar

### ISSUE THREAD

**Issue by StudioPetrikas** [realthunder/FreeCAD_assembly3#725]
"Draft tray" Toolbar keeps appearing when whether Arch or Draft Workbenches get activated. 
Even if it's disabled in Parameters or via View -> Toolbars menu, it reappears when the Arch or Draft workbenches get activated.

**Comment by realthunder** [comment]
Can you please send me your `link.user.cfg` file here? On Windows, it is in `c:\users\<username>\AppData\Roaming\FreeCAD`. On Linux, it is in `~\.FreeCAD`.

**Comment by StudioPetrikas** [comment]
I can reproduce this on a clean setup (don't have my computer on hand)

To reproduce:
- Activate Arch or Draft workbench
- Disable "Draft tray" toolbar through View -> Toolbars
- Activate any other workbench
- Activate Arch or Draft workbench
- "Draft tray" should reappear. 

I think in Vanilla FreeCAD we don't even have the ability to disable it through View -> Toolbars. I think you added that functionality. Thank you for that!

**Comment by StudioPetrikas** [comment]
This is closed! Thank you so much, I can now continue with my UI project :)
