### ISSUE TITLE
Issues with pad function

### ISSUE THREAD

**Issue by mwlandolsi** [realthunder/FreeCAD_assembly3#748]
Hello Every body.

1- infinte pad : 

I got "infinite" pad when the type of limit is set to "to first" (selected limit face is circular) or "to first".

![Screenshot from 2021-07-24 10-51-19](https://user-images.githubusercontent.com/76944804/126864994-cfd94be2-6b87-448e-affd-760712eca7b2.png)

2- Choice of limit is not obvious

![Screenshot from 2021-07-24 11-00-38](https://user-images.githubusercontent.com/76944804/126865043-d0c54e87-b346-4613-9904-51b7c95b0b1d.png)

----------------------------------
OS: Linux Mint 20.1 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.717.24301 +3627 (Git) AppImage
Build type: Release
Branch: LinkStage3
Hash: f63a5ea7b459872a3798027df0ff25e776524859
Python version: 3.9.6
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)
[pad issues 07-2021.zip](https://github.com/realthunder/FreeCAD_assembly3/files/6872234/pad.issues.07-2021.zip)

**Comment by realthunder** [comment]
I have added a new option to make this work. You can uncheck the option if you want to pad/pocket up to some concave face(s).

![Screenshot from 2021-07-25 20-37-14](https://user-images.githubusercontent.com/1207888/126899260-99c494b0-cf17-48b6-bfc0-36ed195167ed.png)

**Comment by mwlandolsi** [comment]
Yes! Great! Thanks for your work. I will test it when a new release is published. Many thanks. I hope that I could help in coding!

**Comment by mwlandolsi** [comment]
Yes many thanks, this will solve many design problems and make FreeCAD  Link stage more competitive especially with plastic part design. this is very useful.
Many thanks Solved with 11.09.2021 release.

**Comment by mwlandolsi** [comment]
Looks like this feature is not any more available in 11012022 daily
