### ISSUE TITLE
Uncompressed XML per object save files for version control

### ISSUE THREAD

**Issue by OJFord** [realthunder/FreeCAD_assembly3#749]
I saw your comment here that this is implemented 'on my branch':
https://forum.freecadweb.org/viewtopic.php?f=10&t=38353&sid=e62deeb802ddee3c47460a2b4f7c4a93&start=40#p498411

Does that refer to the 'stable' releases here? Thanks.

**Comment by realthunder** [comment]
It's available in both the `Stable` and `Daily` release. There is a `Save as Directory` action in the `File` menu.

**Comment by OJFord** [comment]
Cracking, thank you!
