### ISSUE TITLE
[Bug] Unable to update some sketcher colours

### ISSUE THREAD

**Issue by bennvan** [realthunder/FreeCAD_assembly3#759]
Unable to change sketcher colours from default for:

- Frozen external geometry
- Detached external geometry
- Missing external geometry

OS: Ubuntu 20.04.2 LTS (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.717.24301 +3842 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 44be6d539871be4083e83f428e8fcfbcf38408ef
Python version: 3.9.6
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/Australia (en_AU)

**Comment by luzpaz** [comment]
@bennvan please retest on latest release
