### ISSUE TITLE
Sketcher looses constraints

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#76]
Sketcher may loose all of its constraints, possibly after recovering from a crashed session. All constraints including external geometry might be lost. 

I'm not sure it's an upstream bug or not, I thought it would be a good idea to indicate the issue here for the rest of the users in order to let them prepare themselves for such a case. I'll add reproduction steps as soon as I find one.

# Version 

```
OS: Debian GNU/Linux 9.5 (stretch)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.14991 (Git)
Build type: Unknown
Branch: LinkStage3
Hash: ca6a60371470490c74b8d7bd967bf301b4253247
Python version: 2.7.13
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: English/UnitedStates (en_US)
```

**Comment by ceremcem** [comment]
Possibly related with https://github.com/realthunder/FreeCAD_assembly3/issues/64 

There is no crash needed, 

1. Create a part with PartDesign workbench 
2. Add a sub-shape binder under the Body 
3. Create some external geometry constraints 
4. Save and close the document, 
5. Open the document 
6. External geometry constraints are lost.

**Comment by ceremcem** [comment]
I can not reproduce the problem by described steps. A crash is also happened with `56a7e74336c7f7eefc540a1d13168709b5d32a09` while investigating your request and there is still no external geometry constraint loss happened.

**Comment by realthunder** [comment]
Can I have the stack trace?

**Comment by ceremcem** [comment]
Yes and no. I'm preparing a separate issue, will be ready in minutes.

**Comment by ceremcem** [comment]
This issue is currently not reproducable but still happens. This issue is a serious one for large models. Could you please put a `help wanted` label on this?

**Comment by ceremcem** [comment]
FYI and Note to myself: Last incident is caused after: 

1. I replaced an object with another object in a model (document A)
2. `A` was linked in document `B` (`B` is the main document)
3. The replaced part affected a `Cut` in `B` where the `Cut` uses `A.somepart` as a Tool and this `A.somepart` was teleported into `B` via subshape binder (`B.binder`)
4. After returning to main model (B) some subshape binders were shifted 

After fixing some subshape binders, this issue has happened.

**Comment by realthunder** [comment]
Are the lost ones external constraints?

**Comment by ceremcem** [comment]
*Probably*. I can only notice this case when I double click a sketch to edit where there is [a popup appears](https://user-images.githubusercontent.com/6639874/46140450-d23ea980-c259-11e8-9beb-702421616333.png)
 saying "This sketch is invalid and can not be edited". Then I open the validation tool, remove all external geometries, then sketch is opened in edit mode.

**Comment by realthunder** [comment]
External geometry lost due to model change is indeed a problem stemming from upstream. I will improve this later by auto converting the lost external geometries to construction ones.

**Comment by lilphil** [comment]
I've had this quite a lot, if I go back to edit a previous sketch I will find it might have lost all constraints (not just external geometry) without warning. I've noticed that if one sketch loses constraints, often other sketches near by will also lose them. The problem is, you can't tell its happened until you go back to edit something. I do not get the invalid sketch popup. I have not used links anywhere, I've not replaced an object and I don't think I've had crashes at the right time for them to be related to this.
