### ISSUE TITLE
[Bug] Pocket from face works in preview but not when applied

### ISSUE THREAD

**Issue by Miksu80** [realthunder/FreeCAD_assembly3#760]
Pocket from face, preview OK:
![image](https://user-images.githubusercontent.com/48354615/127642356-ccf6f5a5-cbe2-4972-8b80-d6fa858a00ba.png)

Formed shape something weird:
![image](https://user-images.githubusercontent.com/48354615/127642419-a9b9ae77-6a56-4d44-8aa2-d406aed6b148.png)

File:
[pocket_from_face_bug.zip](https://github.com/realthunder/FreeCAD_assembly3/files/6907013/pocket_from_face_bug.zip)

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.717.24301 +3842 (Git)
Build type: Release
Branch: LinkDaily
Hash: 44be6d539871be4083e83f428e8fcfbcf38408ef
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/Finland (en_FI)

**Comment by realthunder** [comment]
Not sure about the cause, but if you manually recompute `Sketch035` (right click -> Recompute object), and then do a document recompute can fix the problem. Probably some obscured bug hidden somewhere.

**Comment by Miksu80** [comment]
Thank you. Hard to tell where the problem is -> I'll close this
