### ISSUE TITLE
Color rendering issue

### ISSUE THREAD

**Issue by kenjesse** [realthunder/FreeCAD_assembly3#771]
Having an odd issue with how bodies and other items color are being rendered on my laptop.  Program functionality is not affected beyond visual problem.  I have attached two images showing what is happening (colored wire frame around body or lines rather than applying the color).  I have tried resetting the render cache to all available setting, restarting the program after each change, with no impact.
![Freecad_Capture](https://user-images.githubusercontent.com/88468305/128278843-bbec48ec-1016-4ece-b757-8e9f359a225a.JPG)
![Freecad_Capture1](https://user-images.githubusercontent.com/88468305/128278846-7aca5390-e7d2-477e-904b-7e81dcb2ddb1.JPG)

Lenovo Ideapad, AMD A9-9400 Radeon R5 (2-cores), 8GB RAM
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.717.24301 +3842 (Git)
Build type: Release
Branch: LinkDaily
Hash: 44be6d539871be4083e83f428e8fcfbcf38408ef
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)

**Comment by thomasgi1** [comment]
It's not a bug. It's a feature. Just disable the bounding box for the selection:

View / Selection Options / Bounding Box => disable

BR Tom

**Comment by kenjesse** [comment]
Very new to not just Freecad but CAD in general.  Had no success searching for info and posted here.  Thanks for the help, kind of embarrassed I missed it while searching through the setting.
