### ISSUE TITLE
Compiling errors in Path workbench, Daily branch

### ISSUE THREAD

**Issue by snelweg** [realthunder/FreeCAD_assembly3#779]
Still getting Path workbench errors in the Daily branch, the LinkStage3 branch compiles allright.
I got a fresh git clone for both the Daily and the LinkStage3 branches. 

> [ 96%] Building CXX object src/Mod/Path/Gui/CMakeFiles/PathGui.dir/TaskDlgPathCompound.cpp.o
> /home/ton/FREECAD/daily/freecad-source/src/Mod/Path/Gui/DlgSettingsPathColor.cpp:101:10: fatal error: moc_DlgSettingsPathColor.cpp: No such file or directory
>  #include "moc_DlgSettingsPathColor.cpp"
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [src/Mod/Path/Gui/CMakeFiles/PathGui.dir/build.make:320: src/Mod/Path/Gui/CMakeFiles/PathGui.dir/DlgSettingsPathColor.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> [ 96%] Building CXX object src/Mod/Sketcher/Gui/CMakeFiles/SketcherGui.dir/TaskDlgEditSketch.cpp.o
> [ 96%] Building CXX object src/Mod/TechDraw/Gui/CMakeFiles/TechDrawGui.dir/QGIViewImage.cpp.o
> [ 96%] Building CXX object src/Mod/Sketcher/Gui/CMakeFiles/SketcherGui.dir/ViewProviderPython.cpp.o
> /home/ton/FREECAD/daily/freecad-source/src/Mod/Path/Gui/TaskDlgPathCompound.cpp:160:10: fatal error: moc_TaskDlgPathCompound.cpp: No such file or directory
>  #include "moc_TaskDlgPathCompound.cpp"
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [src/Mod/Path/Gui/CMakeFiles/PathGui.dir/build.make:333: src/Mod/Path/Gui/CMakeFiles/PathGui.dir/TaskDlgPathCompound.cpp.o] Error 1
> 

When I remove the src/Mod/Path directory and then do a `git checkout LinkDaily Path` and start compiling again gives just one error:
```
Building CXX object src/Mod/Path/Gui/CMakeFiles/PathGui.dir/DlgSettingsPathColor.cpp.o

[ 98%] Linking CXX shared library ../../../../../Mod/Path/PathSimulator.so
/home/ton/FREECAD/daily/freecad-source/src/Mod/Path/Gui/DlgSettingsPathColor.cpp:101:10: fatal error: moc_DlgSettingsPathColor.cpp: No such file or directory
 #include "moc_DlgSettingsPathColor.cpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/Mod/Path/Gui/CMakeFiles/PathGui.dir/build.make:320: src/Mod/Path/Gui/CMakeFiles/PathGui.dir/DlgSettingsPathColor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 98%] Generating moc_TaskPipeParameters.cpp
```
Got it working by copying the Path directory from the LinkStage3 files.
Are the Path files not up-to-date in the Daily branch?

**Comment by luzpaz** [comment]
@realthunder I've added ` waiting next release` label since most likely this will be solved when you merge master changes, right?
