### ISSUE TITLE
Sketcher Navigation: Tool disappears on two button mouse move

### ISSUE THREAD

**Issue by wohltat** [realthunder/FreeCAD_assembly3#783]
When moving in Sketcher with Blender Navigation style the selected tool disappears.
This is probably because the right mouse button click is interpreted as single right click that is supposed to deselect the tool. 

![tool_disappears_on_move](https://user-images.githubusercontent.com/4751351/129704094-6fb6806a-ef8f-42ce-8e05-2cc42f03e71a.gif)

**Comment by luzpaz** [comment]
Please always add [About](https://wiki.freecadweb.org/About). Thanks

**Comment by wohltat** [comment]
```
OS: Linux Mint 20.1 (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.717.24301 +3842 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 44be6d539871be4083e83f428e8fcfbcf38408ef
Python version: 3.9.6
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)

```

**Comment by luzpaz** [comment]
@wohltat is this still an issue?

**Comment by wohltat** [comment]
The tool does not deselect anymore, but now it triggers unintentional single mouse button click while two mouse button move.
![unintentional_click_while_two_button_move](https://user-images.githubusercontent.com/4751351/159123405-bdaa6577-55d7-4573-85ef-edd414a1f04e.gif)

**Comment by luzpaz** [comment]
@realthunder issue still persists apparently

**Comment by wohltat** [comment]
Thanks, works nicely in [2022.04.30](https://github.com/realthunder/FreeCAD/releases/tag/2022.04.30-edge).
