### ISSUE TITLE
[Part Design] Pad up to face (curved) does not seem to work between multiple bodies

### ISSUE THREAD

**Issue by klasrocket** [realthunder/FreeCAD_assembly3#792]
I seem to have a problem while trying to pad a sketch up to a curved surface that's belonging to a different body, that seems a bit weird.
![pad up to face 2 bodies fail](https://user-images.githubusercontent.com/455912/130612944-9a63eb36-9887-48c6-accb-57ce83443c89.png)

![pad up to face  1 body](https://user-images.githubusercontent.com/455912/130612956-2b627a5b-4d11-4d7b-87d9-acddb6ba0ac9.png)

I also tried with a flat surface instead and got another odd result, worked correctly when I added a -1mm offset to face:

![pad up to flat surface negative offset](https://user-images.githubusercontent.com/455912/130613682-e990da7f-2a89-479c-9d7a-b1ce0e3a0f20.png)

but when I didn't use any offset I ended up with an offset in the model:

![pad up to flat surface no offset](https://user-images.githubusercontent.com/455912/130613741-4c43314a-3f68-42cd-94c6-09a496e13932.png)

Hope these hints can be helpful, or maybe give me a hint if I missed something obvious.

[padtoface.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7038976/padtoface.zip)

I get the following error which does not tell me too much really:
14:17:15  <App> GeoFeatureGroupExtension.cpp(577): padtofacebodies#Pad001.UpToFace(links to padtofacebodies#Pad) is out of scope:padtofacebodies#Body vs. padtofacebodies#Body001

I also tried the pad up to curved face with shapebinders but does not get it to work and get similar errors.

OS: Ubuntu Impish Indri (development branch) (ubuntu:GNOME/ubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.717.24301 +3842 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 44be6d539871be4083e83f428e8fcfbcf38408ef
Python version: 3.9.6
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)

**Comment by wohltat** [comment]
Your sketch plane (Sketch 002) is the wrong way around. The pad goes to infinity and returns on the other side :smile: 

Either rotate the line in Sketch001 that gives the direction or change "Map reversed" in Sketch002 (profile sketch for the pad)

**Comment by klasrocket** [comment]
Thanks, that worked fine! Maybe not obvious but sort of makes sense.
I guess this could be communicated in a clearer way but not sure how. Guess I'll close this for now anyhow. Thanks for the help!

**Comment by wohltat** [comment]
> I guess this could be communicated in a clearer way but not sure how.

That's true. I also just found this by accident.
Maybe it's still a bug and it shouldn't even be possible to pad / extrude in the opposite direction. From a real life point of view this would be reasonable.

**Comment by klasrocket** [comment]
I agree, it would make more sense that it does not draw anything if the face is on the other side. I just noticed that the reverse option in the pad tools is inactivated when choosing up to face, but will still take effect if set to reverse when in dimensional pad, then change to up to face mode. This actually also makes my example work without flipping the sketch.

**Comment by wohltat** [comment]
This indicates that is was meant to be used just in one direction by the author. Only all the checks haven't been implemented yet.

**Comment by klasrocket** [comment]
Did some more testing and things actually behave as expected within a body but not when trying to pad in one body but using a reference surface in another. I guess this is not whats intended?

![freecad link branch pad to face multiple bodies](https://user-images.githubusercontent.com/455912/131676262-35acd93b-5f6b-48fc-b88b-3de0c5e52935.gif)
