### ISSUE TITLE
sub-shapebinder not compatible with thick solid tool

### ISSUE THREAD

**Issue by wohltat** [realthunder/FreeCAD_assembly3#793]
I wanted to use the workflow from a @oficinerobotica video (https://www.youtube.com/watch?v=N7b2LBgREmE). 
There the object is split apart by a surface and the splits are referenced via sub-shape binder. So both parts have the same origin but can be processed separately.
Now i want to create a shell with the thick solid tool. This works for the split but not for the reference of the split. The split is needed because the thickness tool needs a face of the inside, i.e. 

![thick_subshapebinder_bug](https://user-images.githubusercontent.com/4751351/130532474-1c37d4e1-d74a-4271-aef5-f092f107e539.gif)
In the video i use a Loft but its the same with a simple cube.

I also tried shapebinder and Links but nothing works. I don't know how to reference the base object so that the thickness tool can be used. Also referencing before the split doesn't work either. 

To be able to use references for the thickness tool / splits would be very usefull for more organic shapes where the thickness tool would be easier than to model the shell manually.

-------
```
OS: Linux Mint 20.1 (XFCE/xfce)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.717.24301 +3842 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 44be6d539871be4083e83f428e8fcfbcf38408ef
Python version: 3.9.6
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)
```

**Comment by realthunder** [comment]
The `SubShapeBinder` is intended to be used just like a `Datum` object. Although it has shape, it is not considered as part of the body shape.  And yes, using a `Boolean` feature can make it part of the body shape. You can also use various `Pattern` features on binder directly.

**Comment by wohltat** [comment]
@dreetie Thanky, its works great. It seems to work also with more complex geometry with round / smooth surfaces. It is still limited to the pickiness / sensitivity of the thickness tool though. 
For some reason thickness outwards is more robust then inwards. I don't know why but it often fails on the object / on the split which has a seam. 

![image](https://user-images.githubusercontent.com/4751351/131829560-60d8cd8f-1378-40e0-bdd2-922edc2f31b0.png)

First i thought, its quite un-intuitive to fuse a an object with itself to achieve this. But with  @realthunder s explaination it makes more sense now. The reference is not part of the body shape and you are fusing it to the empty body shape.
Although still works and has an understandable reason, a new user would not come up with this solution by hirm self.

What about the thickness tool automatically fusing the shapebinder since it is clear from the selected faces which object is meant  to be modified which is not the tip of the body?
