### ISSUE TITLE
highlight the need to install a solver more in the README?

### ISSUE THREAD

**Issue by 3nt3** [realthunder/FreeCAD_assembly3#795]
I may just be lazy and didn't completely read the README's installation instructions but the part on having to install `py_slvs` could be a bit more prominent since the workspace will not work without it.

**Comment by luzpaz** [comment]
Would you like to make a proposal PR?

**Comment by 3nt3** [comment]
yeah sure

**Comment by realthunder** [comment]
Technically, the `Lock` and `Attachment` constraint works without a solver, but yeah, I guess the most asm3 user expects a working solver.
