### ISSUE TITLE
Elements should be ordered by name

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#80]
If we have lots of element definitions like

* foo-middle-point
* foo-bottom-surface
* foo-front-face
* foo-bar-top-surface
* foo-baz-top-surface
* ...

it becomes hard to inspect/refactor and deduplicate* the elements if all elements are listed according to their creation sequence. If they can be ordered by their names, related elements will be listed as if they are grouped. 

> Elements may become duplicated if we create an element for a complex shape from its early stage (which is a good and solid behavior as suggested before) but if we forget that we created an element for an edge of an object and we just click that edge along with some geometry of another object and create a constraint, then the "same element" (same intention) for the same object is created from a "newer state".[[see this]](https://user-images.githubusercontent.com/6639874/45262920-e47eb200-b428-11e8-8a79-a991f98843f9.gif) These type of duplications should be refactored by human interaction at the moment.

**Comment by realthunder** [comment]
I can certainly add a sorting button for this. But I think there is a misunderstanding here. The `ElementGroup` is meant to contain the interface of its owner assembly used as a `Part` for other higher level assembly.  If you strictly follow the `Element` concept described in the wiki document, then an `Element` will never be linked to the constraining `ElementLink` of the same assembly. Instead, it will always be used by some higher level assembly. Therefore, it does not make very much sense to prefix the `Element` name with the name of its associated child part. It is suppose to abstract the child part details for higher assembly.

**Comment by realthunder** [comment]
Sorting function is exposed through context menu of ElementGroup.
