### ISSUE TITLE
Daily (LinkDaily) -> Sporadic ?

### ISSUE THREAD

**Issue by parnasist3** [realthunder/FreeCAD_assembly3#800]
How about renaming "Daily (LinkDaily)" to Sporadic ?

Or are there any obstacles preventing "Daily" from becoming just that, daily?
If there are insurmountable obstacles, then  maybe a name change could be considered?

**Comment by NothanUmber** [comment]
Think it's better the way it is - to release curated versions as pre-built binary, so people know that a pre-release is at least worth testing - no need to spend time with a build where the developers already know that it will crash.
