### ISSUE TITLE
tree view indentation setting

### ISSUE THREAD

**Issue by bambukouk** [realthunder/FreeCAD_assembly3#802]
How do i set value for tree view items indentation, please?

I have been able to do it before but whatever I try now doesn't seem to work (I guess I am just having senior moment...)
Help, please

**Comment by bambukouk** [comment]
Took me two days, but eventually remembered... 👍 
Tools>edit parameters
Would have (should have) asked this question on FreeCAD forum, but the they do not want to talk to me unless I use "master" branch 👎

**Comment by realthunder** [comment]
Sorry for not responding earlier. Do you use discord? Someone has set up a new [channel](https://discord.gg/NpMefpXWFT) for my branch. You can ask there next time.

**Comment by bambukouk** [comment]
Don't apologise 😉
It was my stupidity and bad memory...
You have enough work dealing with real FreeCAD issues
Thank you for all your work!
