### ISSUE TITLE
cyclic dependency for sub-shape binder

### ISSUE THREAD

**Issue by bambukouk** [realthunder/FreeCAD_assembly3#803]
I am having issues creating sub-shapebinder for bodies inside assemblies.
Yet there are no problem creating shape binders using the same bodies?
Also there are no problems creating sub-shapebinders for the same bodies if outside assembly
Do not understand this? - can someone, please explain/iluminate?
file in question:
https://drive.google.com/file/d/1RDNJsc70C-V0dp6lG6y-Q5ZSE0oHPkgf/view?usp=sharing
and what I am trying to do:
![Screenshot from 2021-09-10 10 28 19](https://user-images.githubusercontent.com/50301871/132849095-5a31ef5b-b432-4ce8-a248-2b6648088a50.png)

i.e. sub-shape link inside active "exhaust_body" using "cylinder_body_LH"

I have asked this question on FreeCAD forum, but have been told:
"If this depends on Assembly3, then you should ask this in the Assembly forum, or I can move the topic there. If not, please reproduce it in master. Please note that realthunder is distributing a different program; it is not FreeCAD."

Is it because  "Ass_exhaust_tee" (which contains "exhaust_body") and "Ass_cylinder_LH" (which contains "cylinder_body_LH") are both parts of top level assembly?

**Comment by bambukouk** [comment]
Later edit:
Found a solution!
In order to be able to create sub-shape binder in "exhaust_body" I temporarily removed "Ass_exhaust_tee" from the top level assembly - no longer cyclic dependency !!!
Having created sub-shape binder I have put "Ass_exhaust_tee" back as a part of top level assembly and there it is, with sub-shape binder added:
![Screenshot from 2021-09-10 13 17 14](https://user-images.githubusercontent.com/50301871/132852133-feab57d1-ab40-45e0-965c-b68a46fc1f58.png)

I remain puzzled :-)

**Comment by realthunder** [comment]
There is indeed a related bug that's has been fixed recently. Can you please try using the latest release?

**Comment by bambukouk** [comment]
Thank you!
Traveling back home tomorrow.
Will install latest release and test asap.

**Comment by bambukouk** [comment]
Yes!
Tested and all is working as it should :+1: 
Problem solved.
Thank you very much indeed, yet again!
