### ISSUE TITLE
TechDraw WB is unusable [blocker]

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#81]
# Description 

In TechDraw WB, clicking on a 2D object immediately opens its corresponding 3D view, which makes it impossible to edit/manipulate a 2D drawing: 

![techdraw-not-working](https://user-images.githubusercontent.com/6639874/45266206-f0d23180-b45f-11e8-934b-cfd0bfb5c09f.gif)

### Version 
```
OS: Debian GNU/Linux 9.5 (stretch)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.14996 (Git)
Build type: Unknown
Branch: LinkStage3
Hash: b8d9e29e9a7505708b1a09d616ef01c095756dae
Python version: 2.7.13
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: English/UnitedStates (en_US)
```

### Priority 

Blocker

# Working Version 

In 0.8.6, same steps produces correct results: 

![techdraw-working](https://user-images.githubusercontent.com/6639874/45266214-21b26680-b460-11e8-85ba-33cdd9bef104.gif)

**Comment by realthunder** [comment]
Fixed. 

BTW, there is tree view option called `Sync view` which controls this single-click-view-jumping behavior in tree view.

**Comment by ceremcem** [comment]
`Sync view` option is also nice trick, which I have it enabled (I saw the suggestion one of your wiki documents). Thanks!
