### ISSUE TITLE
[Suggestion] Change Autocomplete's results order

### ISSUE THREAD

**Issue by YosypC** [realthunder/FreeCAD_assembly3#817]
In relation to #815 

![Cattura](https://user-images.githubusercontent.com/50027752/133250689-931d816d-0fb9-4b89-a6c0-78385dde9a25.PNG)
```
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.911.24301 +4130 (Git)
Build type: Release
Branch: LinkDaily
Hash: cdcdcfc78188218bd5eab1cfd9f911acd666f734
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: Italian/Italy (it_IT)
```

![Cattura2](https://user-images.githubusercontent.com/50027752/133250734-f0ccffe0-1470-45ba-9e9e-5fc044d5a222.PNG)
```
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.717.24301 +3842 (Git)
Build type: Release
Branch: LinkDaily
Hash: 44be6d539871be4083e83f428e8fcfbcf38408ef
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: Italian/Italy (it_IT)
```

**Comment by realthunder** [comment]
The auto complete feature has been changed a bit. You need to type some character to trigger the search. The auto complete now returns match keyword contained in any position, instead of just match from the beginning.

**Comment by YosypC** [comment]
Would it be possible to order the results based of types, just like it was before?
