### ISSUE TITLE
[Question] How to use the latest branch 9/11?

### ISSUE THREAD

**Issue by jamestansx** [realthunder/FreeCAD_assembly3#819]
Hi, I would like to ask how to use the latest release on 9/11? There is no `FreeCADLink.exe` like previous release. Thank you in advance.

**Comment by realthunder** [comment]
You mean the download link right? There is some serious problem in the 09.11 release. I'll make a new release very soon.

**Comment by Prutzz** [comment]
Have no experience with compiling.... Any quick answer to do it yourself? Or is it too difficult :)

**Comment by jamestansx** [comment]
> You mean the download link right?

Yes, indeed. 

Noted. Thanks!

**Comment by jamestansx** [comment]
The new [release](https://github.com/realthunder/FreeCAD_assembly3/releases/tag/0.11) is here! Closing this.
