### ISSUE TITLE
[BUG 2021.9.16] Sketcher: picking priority issues when doing constraints

### ISSUE THREAD

**Issue by Miksu80** [realthunder/FreeCAD_assembly3#824]
When doing for example point-symmetry, the symmetry icon prevents clicking on vertex. It'd be good to disable constraint selection when constraint is being added. Basically, if you start to do constraints by clicking the constraint-button 1st, then it wouldnt try to select constraints at all but just vertices, lines, arcs, construction geometry, axis etc.) This is a new issue that has not existed on few months back version.

Here trying to select the point with coincident -tool and it just tries to select the constraint:
![image](https://user-images.githubusercontent.com/48354615/133602218-ac835dca-66dc-4a84-a169-01fec4af0701.png)

It does this some times on center point but if the sketch plane is on XY,YZ, XZ plane, the center-point is ontop but if you do a sketch in a surface which is ontop of sketch center, center-point goes behind constraint. Even with "GG" it doesn't work:
![image](https://user-images.githubusercontent.com/48354615/133603192-75e612d1-a2ca-4177-8360-769a281e7405.png)
with just selecting the vertex 1st or 2nd, it only highlights it, it doesnt really select it:
![image](https://user-images.githubusercontent.com/48354615/133603221-6627ef67-77bf-4632-8635-ce50da1c6cb3.png)
When using ctrl, it highlights both but just dont work:
![image](https://user-images.githubusercontent.com/48354615/133603441-8b36337c-ce97-4404-99ec-92b6c0a69908.png)

Version:
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.916.24301 +4152 (Git)
Build type: Release
Branch: LinkDaily
Hash: 7fd36f96f4db17db4f8d058eab22588cca8f9d5c
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/Finland (en_FI)

**Comment by herrgerd** [comment]
I'm 100% with you here. The `GG` command (which could be super super useful) is - in its recent form - totally useless. The other "bug", namely selecting constraints, has been mentioned many many times before, too.

I hope both will get some attention soon. Sketching, _which is the start of every part or assembly_, can still be a pain because of that...

**Comment by realthunder** [comment]
I have fixed the symmetric constraint z order problem. But I don't quite get it what you mean by it just doesn't work when using ctrl + `G, G`?  Can you please elaborate?

**Comment by Miksu80** [comment]
When trying to select the "hidden" vertex with G, G it doesn't really select it. With constraint tool clicked, it didn't select the vertex using G, G and selecting the vertex from the list.

**Comment by Miksu80** [comment]
The dimension texts are in front of geometry when doing symmetry (or other constraints) -this is not a biggie but noticed with small diameter circles (had to zoom in to be able to select center point, didn't test "G, G").
![image](https://user-images.githubusercontent.com/48354615/135208225-a98b1897-82a3-48ee-bdca-2786a1491b3e.png)

**Comment by realthunder** [comment]
The constraints having datum label are giving higher priority because you can move them around, while other constraints cannot. So, why not just drag it away?

**Comment by Miksu80** [comment]
> The constraints having datum label are giving higher priority because you can move them around, while other constraints cannot. So, why not just drag it away?

That works also, just didn't notice to move the number prior to selecting tool. When tool already selected, you probably don't select anything other than geometry so basically anything but geometry can be filtered out when tool is already selected. Anyways it's not a biggie and can be dealt with your suggestion or by zooming in 👍
