### ISSUE TITLE
Recursive calling of recompute for document

### ISSUE THREAD

**Issue by mwlandolsi** [realthunder/FreeCAD_assembly3#832]
when trying to move body using Draft WB I got this error : Recursive calling of recompute for document

https://user-images.githubusercontent.com/76944804/133738558-e1089416-ee22-4e9f-a591-7bf4c9e2cc7f.mp4

**Comment by realthunder** [comment]
This is not considered a fatal error for user. It servers as a reminder for the developer to tidy up their recomputation calls.
