### ISSUE TITLE
DXF import does not work

### ISSUE THREAD

**Issue by ceremcem** [realthunder/FreeCAD_assembly3#85]
Importing DXF does not work in `63dd5552a55f2dc3ba59f1c90aa94df93f5a7c9f`:

![dxf-import-not-work](https://user-images.githubusercontent.com/6639874/45364540-12a7f180-b5e3-11e8-9b3a-207701a2ba77.gif)

However it works in 0.8.6: 

![dxf-import-works](https://user-images.githubusercontent.com/6639874/45364552-1b002c80-b5e3-11e8-9a6b-3e3095a46a2d.gif)

# Priority 

~Blocker~ High (has workarounds)

# Attachments 

[sgw-logo.dxf.remove-extension.zip](https://github.com/realthunder/FreeCAD_assembly3/files/2371230/sgw-logo.dxf.remove-extension.zip)

**Comment by realthunder** [comment]
I just did a merge with the upstream, and cannot reproduce this problem now. Please sync and try again.

**Comment by ceremcem** [comment]
As of current build, problem still persists: 
```
OS: Debian GNU/Linux 9.5 (stretch)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.18.15497 (Git)
Build type: Unknown
Branch: LinkStage3
Hash: 5a4bb159157040e593e847a8b16f240eb80f954e
Python version: 2.7.13
Qt version: 4.8.7
Coin version: 4.0.0a
OCC version: 7.1.0
Locale: English/UnitedStates (en_US)
```

**Comment by ceremcem** [comment]
That settings solved the problem: 

![image](https://user-images.githubusercontent.com/6639874/45435285-eced1c00-b6b8-11e8-9fae-ffa9255040e2.png)

**Comment by ceremcem** [comment]
Do you think this is a bug because they are somehow expected as enabled in a fresh install?
