### ISSUE TITLE
Cannot constrain assembly of assemblies to another one

### ISSUE THREAD

**Issue by not-a-number-dot-org** [realthunder/FreeCAD_assembly3#853]
Hi

So I have in one file this table which is made of something like 125 parts (but maybe only 20/25 differents one) which are assemblies containing only bodies. They are assembled using 99% of Plane Alignment constraints.

And on another file I have the drawers which is an assembly of 6 assemblies (stored in various files) that I'am trying to assemble with the table.

But I cant because I have an error on the first constraint that I try to set (see last image below) (I tried with different elements (faces))

Not sure if I was supposed to post this on FCAD forum instead.
btw is there an option to have more verbose error messages ?

OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.922.24301 +4188 (Git)
Build type: Release
Branch: LinkDaily
Hash: 3de879c7a2ba7111cc769d98636eb6d43189459d
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: French/France (fr_FR)

![table](https://user-images.githubusercontent.com/16313259/134786282-18eacd85-8856-48d2-b027-c9dc67fe6daa.png)
![drawer](https://user-images.githubusercontent.com/16313259/134786286-b78b8768-8e78-489b-808c-9382a0caa73c.png)
![bug](https://user-images.githubusercontent.com/16313259/134786290-f30f6a6b-5be9-43bc-ab3b-50fe03ea71ad.png)

**Comment by realthunder** [comment]
According to the error, your assembly is too big. The solver has a hard coded limit of maximum 1024 parameters to solve for a single assembly. Each part has six unknowns corresponding to its six DOF. I'll probably raise that limit in future release. But still, it is recommended to break large assembly into smaller sub-assemblies. Just like doing real assembling, it's good to modularize things.

**Comment by not-a-number-dot-org** [comment]
Hello.

Any chance to have an update with a dynamic parameter limit soon ?
My table frame is just missing 24 constraints to be finished.

Thanks in advance.
