### ISSUE TITLE
PartDesign "Null Shape" error when using FitTolerance parameter.

### ISSUE THREAD

**Issue by oficinerobotica** [realthunder/FreeCAD_assembly3#854]
Steps to reproduce:
-on a PartDesign body select a face then Pad
-enter a negative "Fit Tolerance" value
-the preview works but the operation will give a "Null Shape" error

![NullShape](https://user-images.githubusercontent.com/26909793/134799732-63a0bb96-e379-46c2-b591-54ac7a190149.jpeg)

OS: KDE neon User Edition 5.22 (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.922.24301 +4188 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 3de879c7a2ba7111cc769d98636eb6d43189459d
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
It is a subtle problem that can be traced to a possible bug in OCC. This could be the cause of a few wired `fit` related bug reported here. The above commit is a work around of the bug.
