### ISSUE TITLE
clicking subtractive loft defaults to additive operation

### ISSUE THREAD

**Issue by kevenwyld** [realthunder/FreeCAD_assembly3#856]
Clicking the subtractive loft button in part design defaults to additive operation.

Video:

https://user-images.githubusercontent.com/11936535/134842094-d7d2046a-0914-4ad2-9400-437569133633.mp4

```
OS: Arch Linux (i3/i3)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.922.24301 +4188 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 3de879c7a2ba7111cc769d98636eb6d43189459d
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)
```

**Comment by snelweg** [comment]
Maybe related:

https://www.patreon.com/posts/56457476

**Comment by kevenwyld** [comment]
@snelweg thanks, though the screen capture above was in a new document for the purpose of demonstrating this bug, and I'm on the 9/22 release.

I didn't initially upload a file because you have to actually click loft to recreate the bug, but here's the base setup I used for the screen capture.  Select Sketch001 followed by Sketch002 and click `Subtractive Loft` from the toolbar.  For me the dialogue opens a loft where the operation is Additive.

File:
[additive_subtractive_loft_bug.FCStd.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7237432/additive_subtractive_loft_bug.FCStd.zip)
