### ISSUE TITLE
[Preset configurations] "Merge" utility will change the name of the preset.

### ISSUE THREAD

**Issue by oficinerobotica** [realthunder/FreeCAD_assembly3#864]
Merging of a preset .FCParam file will change the name of the original preset to the name of the merged file upon restarting FC. In my opinion this shouldn't happen as I "Merge"  see as a tool to add to a current preset.

Steps to reproduce on a clean config.
-using this repo https://github.com/oficinerobotica/FreeCAD-Preferences-Presets add the SplitDark preset present in the FreeCAD-Preferences-Presets/ folder 
-in the SplitDark preset merge the PieMenus.FCParam file present in the "Mods" folder 
-if FC isn't restarted the PieMenus won't show even if the params are present in the "Parameter Editor"
-after restarting FC, the preset is renamed as PieMenus instead of keeping the SplitDark name
-also the PieMenus won't work until the "Customise Toolbar" window is brought up. After that the Pie's will work 

![PiePresets](https://user-images.githubusercontent.com/26909793/135765784-acff3a85-7724-4bc5-be12-87fcca9d7256.jpeg)

**Comment by snelweg** [comment]
When a preset file is removed from within the Parameter Editor it still exists in the .FreeCAD/settings folder. So when I try to install a new version it still gets renamed with a (1). 

Shouldn't the file be deleted from /settings if I do a 'remove'?
