### ISSUE TITLE
Cannot compile, 2 errors and no gui

### ISSUE THREAD

**Issue by LouiseTGUK** [realthunder/FreeCAD_assembly3#870]
Because the GUI and fonts are all microscopic in the appimage on manjaro I decided to try compiling it myself to see if that will help, keep in mind last time I compiled anything was 68000 assembly language back on the Amiga 500!!!

It finishes with 2 errors and running the binary launches but there is no GUI..

Any chance of some assistance?

**Comment by realthunder** [comment]
You only captured standard output. The standard error is more important. Please try the following command

```
make 2>&1 | tee makeout.txt
```

**Comment by LouiseTGUK** [comment]
Ok, is this better.. I used make -j$(nproc --ignore=2) 2>&1 | tee makeout.tx
[makeout.txt](https://github.com/realthunder/FreeCAD_assembly3/files/7340055/makeout.txt)
t

**Comment by realthunder** [comment]
Looks like you CMake command have some problem. You have not enabled c++11 (`BUILD_ENABLE_CXX11`) on compilation. Below is more or less what I am using just for reference. If you want to try, please clear your current build directory first.

```
cmake \
    -DOCCT_CMAKE_FALLBACK=1 \
    -DCMAKE_BUILD_TYPE=Release \
    -DFREECAD_USE_OCC_VARIANT="Official Version" \
    -DBUILD_QT5:BOOL=ON \
    -DUSE_BOOST_PYTHON:BOOL=OFF \
    -DBUILD_ENABLE_CXX11:BOOL=ON \
    -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 \
    -DBUILD_PLOT:BOOL=OFF \
    -DBUILD_SHIP:BOOL=OFF \
    -DBoost_NO_BOOST_CMAKE:BOOL=ON \
    -DUSE_BOOST_PYTHON:BOOL=OFF \
    -DFREECAD_USE_PYBIND11:BOOL=ON \
    -DBUILD_FLAT_MESH:BOOL=ON \
    ..
```

**Comment by LouiseTGUK** [comment]
Nope, pretty much the same outcome :( I will accept defeat and hope you can address the QT fonts and GUI element scaling issue in the app-image :(

Thanks for your assistance, it was very much appreciated.
