### ISSUE TITLE
Basic tutorial distorted after recompute

### ISSUE THREAD

**Issue by sslupsky** [realthunder/FreeCAD_assembly3#875]
If you load the "Basic_Part_Design_Tutorial_017" (from the FreeCAD website), LS3 asked to recompute.  After the recompute, the object is distorted.  See the before and after screenshots below.

Before
![Screen Shot 2021-10-13 at 11 23 16 AM](https://user-images.githubusercontent.com/16888734/137183436-3aaa2342-082e-4e41-b56f-a6211192705b.png)

After
![Screen Shot 2021-10-13 at 11 23 22 AM](https://user-images.githubusercontent.com/16888734/137183471-151261b0-444b-44d8-b826-9c8dfad19834.png)

[Basic_Part_Design_Tutorial_017.fcstd.zip](https://github.com/FreeCAD/FreeCAD-Bundle/files/7340234/Basic_Part_Design_Tutorial_017.fcstd.zip)

Version:
OS: macOS 10.16
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.922.24301 +4188 (Git)
Build type: Release
Branch: LinkDaily
Hash: 3de879c7a2ba7111cc769d98636eb6d43189459d
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: C/Default (C)

**Comment by kevenwyld** [comment]
I think this is an issue with the tutorial file.  I get a similar distortion in v0.19.  Turning off `Refine` fixes it.

In the newest version of LinkDaily (with the patch for refine per [this commit](https://github.com/realthunder/FreeCAD/commit/7a5a07601c8b4e4e54d779a524e547862180d19a) I do not experience missing faces with this tutorial file on initial recompute or even after forcing a recompute of everything.

**Comment by sslupsky** [comment]
Yes, the Oct 15 build has fixed this problem.  The demo file opens properly now.
