### ISSUE TITLE
.step file parts/sub assemblies need to be kept separated

### ISSUE THREAD

**Issue by meprakarsa** [realthunder/FreeCAD_assembly3#878]
Greetings and regards from Batam, Indonesia,

I've been using FreeCAD 0.16, 0.18, 0.19 daily, 0.19 stable, and 0.20 daily (all are main branch).
Just recently been interested to use the "shadow view" /lighttracing provided in this awesome Realthunder branch.

Unfortunately every time I open any .STEP file which contains a lot of parts or sub assemblies, the "body" is only shown one in this branch, can not be expanded. 
Of course i need them to be kept separated since I need to do moving/rotating simulation, animation etc from each part with certain assembly constraints.

Please see following snapshot from one example file:
<img width="635" alt="realth vs main STEP" src="https://user-images.githubusercontent.com/92571561/137456504-426adb31-4cb8-4a27-808c-f11a54f9acc0.png">

OS: macOS 10.15
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.922.24301 +4188 (Git)
Build type: Release
Branch: LinkDaily
Hash: 3de879c7a2ba7111cc769d98636eb6d43189459d
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: C/Default (C)

**Comment by herrgerd** [comment]
> 
> 
> thanks a lot, it works! <img alt="Screen Shot 2021-10-26 at 8 14 22 am" width="391" src="https://user-images.githubusercontent.com/92571561/138792127-84270ebb-2baa-4cf5-8290-192d584d05b7.png">

Hey, if it worked for you, please close your issue soon afterwards, so the bug tracker is emptied a bit :)

**Comment by meprakarsa** [comment]
please forgive this newbie who didn't know that issue shall be closed in tracking wise.
