### ISSUE TITLE
Constrain point and Constrain Tangent  is not Working

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#911]
https://user-images.githubusercontent.com/92737149/141115264-c51d0328-ea46-42f4-bf44-e52ef471fd54.mp4

**Comment by Rabbit-sk** [comment]
#729

**Comment by hamza00789** [comment]
> 
> 
> BTW similar shape could be easily done with arcs with tangent constraint between them. ![obrázok](https://user-images.githubusercontent.com/74265320/141134478-b6d01681-7dba-458a-b773-e67415f1088b.png)
