### ISSUE TITLE
visibility problem

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#912]
Looking at the tree but not looking at the screen

https://user-images.githubusercontent.com/92737149/141123565-cc6bc52c-9700-49fa-9e04-fc7b45e7a2db.mp4

**Comment by Rabbit-sk** [comment]
It is because of this:
![obrázok](https://user-images.githubusercontent.com/74265320/141130154-f0eb200f-9111-448a-8f57-35acb678c493.png)

**Comment by hamza00789** [comment]
thanks
