### ISSUE TITLE
[FR] guide curve blend Surface

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#916]
Free Cad blend blend Surface

https://user-images.githubusercontent.com/92737149/141329516-f9e5f468-8362-4932-b29a-f089d4976b71.mp4

guide curve blend Surface 

https://user-images.githubusercontent.com/92737149/141329633-cc8a3080-4b23-4e75-aa31-7ce3a6035680.mp4

**Comment by Rabbit-sk** [comment]
[Curves Workbench – FreeCAD Documentation](https://wiki.freecadweb.org/Curves_Workbench)

[FreeCAD Curves and Surfaces WorkBench](https://github.com/tomate44/CurvesWB#freecad-curves-and-surfaces-workbench)

[Issues · tomate44/CurvesWB](https://github.com/tomate44/CurvesWB/issues)

**Comment by Rabbit-sk** [comment]
It seems that your model is not solid, but only consists of surfaces. It is possible to model this in PartDesign, but it works better with solids. 

If this part is to be made of sheet metal, there is a workbench for this type of item: [https://wiki.freecadweb.org/SheetMetal_Workbench](https://wiki.freecadweb.org/SheetMetal_Workbench)

**Comment by Rabbit-sk** [comment]
![obrázok](https://user-images.githubusercontent.com/74265320/141344490-3c2c0905-ceec-439b-89c6-ea90f91970cf.png)
![obrázok](https://user-images.githubusercontent.com/74265320/141343328-8179b9d3-0d62-4fc7-b3d0-d9539e614443.png)
![obrázok](https://user-images.githubusercontent.com/74265320/141343356-75875742-9223-445d-811b-4d0911c13337.png)
![obrázok](https://user-images.githubusercontent.com/74265320/141344634-91862aa8-eddd-4fdf-af40-2f881e52159b.png)
![obrázok](https://user-images.githubusercontent.com/74265320/141343390-b6e7618c-03dc-4a72-88c6-81342ebe0935.png)
![obrázok](https://user-images.githubusercontent.com/74265320/141343607-0382f9ca-0bb0-47ad-a000-954d7f976f1d.png)
![obrázok](https://user-images.githubusercontent.com/74265320/141343638-1e3a2020-852b-47e0-9f02-82f4d9db39d0.png)
![obrázok](https://user-images.githubusercontent.com/74265320/141343799-0bec8a2f-ccc0-4199-9cdb-0bd53f54e1b5.png)
![obrázok](https://user-images.githubusercontent.com/74265320/141343988-694e3537-1299-4a1a-b826-b6c5d4ecb2a2.png)
![obrázok](https://user-images.githubusercontent.com/74265320/141344025-3826fbae-3ae5-4d7f-b6e3-4b6f5cad42b4.png)
![obrázok](https://user-images.githubusercontent.com/74265320/141344259-5cce3a28-d5e8-466e-8412-0965a51e422a.png)
![obrázok](https://user-images.githubusercontent.com/74265320/141344348-a7248f37-cf11-4c68-9fa6-d9a7d9896be7.png)
![obrázok](https://user-images.githubusercontent.com/74265320/141344380-7646c59d-c875-42ea-a682-4dc73ccd13c5.png)
![obrázok](https://user-images.githubusercontent.com/74265320/141344444-ae3248ba-485d-412e-9e95-21a0146024e3.png)

**Comment by Rabbit-sk** [comment]
Was it helpful?

**Comment by hamza00789** [comment]
> 
> 
> Was it helpful?

Sorry Couldn't talk due to busy schedule. I gave a simple example so that I can understand what I want. In this example this work can be done in part design and partworkbanch as you did. And I don't have to do anything like sheet metal. I have to work on the surface. My work is being stopped because of this. I try to give a good example of this. 

https://user-images.githubusercontent.com/92737149/141363148-3130eb7d-c048-4d87-9d56-8a68125fcd20.mp4

**Comment by mwlandolsi** [comment]
Sorry to  comment out of the subject, but I was interested by the way that the annotations are displayed
Could you please tell me @hamza00789  which workbench you used to create them.
![141329633-cc8a3080-4b23-4e75-aa31-7ce3a6035680](https://user-images.githubusercontent.com/76944804/141825773-64cfe2f5-9f26-41b3-8526-1d5b10232285.jpg)

**Comment by hamza00789** [comment]
> 
> 
> Sorry to comment out of the subject, but I was interested by the way that the annotations are displayed Could you please tell me @hamza00789 which command and workbench you used to create them. ![141329633-cc8a3080-4b23-4e75-aa31-7ce3a6035680](https://user-images.githubusercontent.com/76944804/141825773-64cfe2f5-9f26-41b3-8526-1d5b10232285.jpg)

Why do you want to know this? It will not solve my problem

**Comment by hamza00789** [comment]
> Sorry to comment out of the subject, but I was interested by the way that the annotations are displayed Could you please tell me @hamza00789 which command and workbench you used to create them. ![141329633-cc8a3080-4b23-4e75-aa31-7ce3a6035680](https://user-images.githubusercontent.com/76944804/141825773-64cfe2f5-9f26-41b3-8526-1d5b10232285.jpg)

https://youtu.be/PwUYf0B5rSE?t=201
