### ISSUE TITLE
[FR] use 3D-element from FEM-wb for clipping plane

### ISSUE THREAD

**Issue by HoWilgh** [realthunder/FreeCAD_assembly3#920]
In FEM wb an element is used to clip results/parts called 'Clipping plane on face' (https://wiki.freecadweb.org/FEM_ClippingPlaneAdd).
It would be very nice to have this sort of Element to clip the bodies instead of the window with buttons to move the clipping-plane.
Furthermore it would be really helpful if one could store several clipping-planes inside the model to reuse it later.

Currently, the clipping plane could only be used for one file/window. One has to close it and reopen it after changing into the window where a clipping is needed next.

**Comment by realthunder** [comment]
Yes, it is proposed by other people as well. I'll definite add this in the future.
