### ISSUE TITLE
Some small UI issues.

### ISSUE THREAD

**Issue by oficinerobotica** [realthunder/FreeCAD_assembly3#921]
As thees are paper cut small issues I compiled them in to one post to not pollute the tracker. If you prefer one issue per post please let me know and i'll break them in to multiple entries. 

1- the TreeView icon size setting isn't respected upon reopening FC. Even if the dimension is changed they are always displayed at default size after a restart of the app. 

2- Pie menus trigger on hoover doesn't work when buttons with a state(enabled/disabled) are involved. In the vid bellow, the pie is correctly dismissed after a hoover/trigger but for buttons that have a enabled/disabled state the pie stays on the screen.

https://user-images.githubusercontent.com/26909793/141606679-c598de52-bf26-417e-91d9-3aa4733dadf8.mp4
 

  
  
3- If I'm not mistaken the NaviCube position is defined as an offset from the 3d view edge. If it is in it's default position will be covered when the overlay interface is enabled. If a offset is defined it will change position on the screen based on the state of the interface (overlay or classic). One solution could be defining the offset as a percentage from the edge of the app window. I'm aware that there are more important things to code now but it is just an idea. https://github.com/oficinerobotica/FreeCAD-Preferences-Presets/issues/4

![NaviCube](https://user-images.githubusercontent.com/26909793/141606995-7f97add6-4be2-407c-bea0-a914fd489dde.png)

```
OS: KDE neon User - Plasma 25th Anniversary Edition (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.1015.24301 +4280 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 556c87868ea46796242156e9f73eae98259794b7
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)
```

**Comment by realthunder** [comment]
The navigation cube offset is defined relative to its corner.  If I understand you correctly, the relevant option you want is shown below. Note, currently it only leave space for navigation cube at the corner without offset.

![Screenshot from 2021-11-27 08-45-24](https://user-images.githubusercontent.com/1207888/143662883-ff4ff67f-fc70-4b6f-9534-ef65438125dc.png)

**Comment by oficinerobotica** [comment]
Thx :)
