### ISSUE TITLE
In linux mint tara 19 missing the three UI bottons

### ISSUE THREAD

**Issue by mttr402** [realthunder/FreeCAD_assembly3#937]
In the last number of updates when starting Freecad, it opens in full screen mode and the min/restore/close buttons are missing. In version .20 all is ok. Can on exit program with the exit in menu.

**Comment by bambukouk** [comment]
View>Fullscreen toggles on and off so you can exit full screen no problem?

**Comment by mttr402** [comment]
Thank you that does work, however It seems to not save that view on exit as every time you start Freecad you have to toggle (Alt-F11) the Fullscreen off.
