### ISSUE TITLE
Questions related to attachment constraint

### ISSUE THREAD

**Issue by GinTonic99** [realthunder/FreeCAD_assembly3#941]
Good day,

OS: Debian GNU/Linux 11 (bullseye) (KDE/plasma)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.1015.24301 +4280 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 556c87868ea46796242156e9f73eae98259794b7
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: German/Austria (de_AT)

in an effort to use the attachment constraint as much as possible, I started investigating the beahaviour of the attachment constraint used with edges. Attached is a simple model comprising a grey pad to be connected to a blue bar with triangular cross section.

 I move the bar closed to the desired position with the correct orientation using the transformation tool and select the two edges to be connected.
![Screenshot_1](https://user-images.githubusercontent.com/34986229/143210357-9a27369c-ac92-4234-b471-b735df8611ef.png)

After applying the attachment constraint this is the result.
![Screenshot_2](https://user-images.githubusercontent.com/34986229/143210540-141b9edf-bf63-48e9-aae3-976df69680be.png)

As shown the bar has been rotated by 90°. In order to correct this I try to apply a 90° rotation around the z-axis for either one of the concerned elements. However this does not bring any change. Rotations around the x or y axis are observed but around the z-axis for either of the two elements not. Same when trying the offset element tool. However the flip element tool works but does not lead to the intended result in this case.

Question 1: How can I apply such a rotation around the z-axis for the elements?

During playing around I noticed that any input for the offset in of the two representations of an element in the tree (under the respective constraint and under Elements) is not reflected in the other representation. E.g. when I enter an offset of 10 mm in z direction in the element under the constraint, the offset of the element under Elements is still zero and when I enter another offset in the element under Elements this offset is applied in addition. My understanding has been that these two representations should be identical, like when I change the label in one it is reflected in the other representation.

Question 2: Is this the intended behaviour?

Further experiments show, that a rotation applied directly in the linked part would lead to the desired result.
![Screenshot_3](https://user-images.githubusercontent.com/34986229/143213944-e9cbae45-b4df-47d0-ab96-1d7622fa8a7c.png)
I noticed however that it is not possible to enter the values directly, they have to entered in the expression field in order to be observed.

Question 3: is this the intended behaviour?

The enclosed file reflects that status after application of the rotation in the linked part.

Thank you for reading.

best regards
[Attachment.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7594553/Attachment.zip)

**Comment by bambukouk** [comment]
You are complicating things :-)
I took your file, renamed things (to make it easier to follow things).
I also changed the triangle shape to easier follow which way round things are.
You don't need to rotate, transform or introduce placement formulas (yes, I have deleted them as well)
Then as you did, I "locked" and "attached" (without even getting things close together) - worked first time, and...
if I didn't as it sometimes happens - use "flip element" "flip part" "offset part" to get things orientated the way you desire
[Attachment(bambuko).zip](https://github.com/realthunder/FreeCAD_assembly3/files/7603899/Attachment.bambuko.zip)
![attach](https://user-images.githubusercontent.com/50301871/143466600-6478546d-6e57-4db1-b194-f63a70be2f7d.png)

Same model with element flipped:
![flipped](https://user-images.githubusercontent.com/50301871/143466854-6e7cf72a-deb8-4dc2-a40f-7d54fa7a2ed9.png)

or you could combine above with using scale=-1 (mirror)
![scale](https://user-images.githubusercontent.com/50301871/143467592-aa1bbf02-17d2-49cc-91d5-0cb25067032a.png)
![scale_flipped](https://user-images.githubusercontent.com/50301871/143467609-adfef8ba-53af-4f9a-b0c7-cd194fc2f59c.png)

I love assembly 3 :+1: :1st_place_medal:

**Comment by GinTonic99** [comment]
Hi Bambukouk,

thank you for your effort.

What I was missing was exctly this:

> or you could combine above with using scale=-1 (mirror) !

thanks again
gintonic99

**Comment by bambukouk** [comment]
You are welcome :+1:  @GinTonic99
