### ISSUE TITLE
white space expected - fatal error

### ISSUE THREAD

**Issue by bambukouk** [realthunder/FreeCAD_assembly3#947]
Luckily for me I save everything in a new version before attempting anything...
so it is not a total disaster - just go back to previous version...
but, I am totally puzzled by this error.
help please, pretty please :+1: 

![whitespace01](https://user-images.githubusercontent.com/50301871/143775145-788bc478-efd0-44d0-82ff-cf827e4128aa.png)
![withespace02](https://user-images.githubusercontent.com/50301871/143775146-c8865772-14ab-469b-b49e-4eebff3f97c0.png)

**LATER EDIT:**
_unable to recreate it in a much simplified file ...
yet always able to cause the same problem in the original file - even more puzzled

**BUT**
_managed to simplify original files, so that I can attach them here:
This is my assembly. I have three components (red arrowed) that need to be attached to each other._
![white_space(before)](https://user-images.githubusercontent.com/50301871/143785188-1a23feeb-fbf8-4f13-a382-feca6b56c3fe.png)
_This is the folder and files before constraints are added:_
[white_space_v23(before_constraints).zip](https://github.com/realthunder/FreeCAD_assembly3/files/7614326/white_space_v23.before_constraints.zip)

_After I add constraints it all looks fine._
![white_space_after](https://user-images.githubusercontent.com/50301871/143785274-b67187c4-3f5b-484c-a413-7b3052cca244.png)
_but... after saving it an re-openning the folder and files end up like so:_
[white_space_v23(after_constraints).zip](https://github.com/realthunder/FreeCAD_assembly3/files/7614328/white_space_v23.after_constraints.zip)

_With the following:_
![after01](https://user-images.githubusercontent.com/50301871/143785336-5359eae1-9966-4b86-a5af-00d4632272e3.png)

![error_message](https://user-images.githubusercontent.com/50301871/143785341-c3b6ef0f-f32b-4d62-8e51-1374ed553f04.png)

_Hopefully @realthunder you can make some sense of it, please because I have tried everything I can think of..._

**Comment by realthunder** [comment]
Looks like illegal characters in XML file. If so the problem has been fixed. Until the next release, please do not use the following  characters for element name. 

```
<
>
&
'
"
```

**Comment by bambukouk** [comment]
Yes, indeed 
I have used " to indicate imperial sized nipple 
Thank you
and I thought it was another one of my mistakes...
BTW google search came up with one page about XML, but I couldn't make sense of it 🤪
