### ISSUE TITLE
External Geometry issue

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#956]
The external geometry error of the sketch is outside the group.  But putting the sketch into a group does not make the mistake of external geometry.  

https://user-images.githubusercontent.com/92737149/144589585-885b0c83-e170-4124-a7b4-6c9b27710e45.mp4 

![2](https://user-images.githubusercontent.com/92737149/144590302-96eb202a-3d93-4f5a-9bc5-6714b3d17b03.jpg) 

![3](https://user-images.githubusercontent.com/92737149/144590321-da6ab0a8-11cd-4907-b609-bad1ad90b717.jpg) 

But sometimes the sketch is within the group, yet the external geometry error. You can see in the video  
The sketch is inside the group but an error occurs when I use external geometry But when I leave the sketch and edit sketching again, there is no mistake for external geometry.

https://user-images.githubusercontent.com/92737149/144727784-d7f978a3-2a15-4415-86e4-38be7cf374de.mp4    

 That means to keep trying two or three times and then it will work

**Comment by realthunder** [comment]
I can't reproduce the problem. Please post a file showing the problem.

**Comment by hamza00789** [comment]
> I can't reproduce the problem. Please post a file showing the problem.

![123](https://user-images.githubusercontent.com/92737149/145077384-fb321dee-3f65-4aa8-aea3-25f411a0f3c4.jpg) 

[13.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7670409/13.zip)

**Comment by hamza00789** [comment]
> I can't reproduce the problem. Please post a file showing the problem.

There is another similar problem, look at it. When I select a circle, the result is a dot, and when I select another circle, the result is the opposite. 

![1](https://user-images.githubusercontent.com/92737149/146380016-35041635-7b08-44cd-810b-1d83191b4559.jpg) 
![2](https://user-images.githubusercontent.com/92737149/146380088-d1671801-320e-4a68-9ec8-9f4bf6349f48.jpg) 
![3](https://user-images.githubusercontent.com/92737149/146380109-c140e51b-0ba0-49a0-91a2-3d41ff311cea.jpg) 
![4](https://user-images.githubusercontent.com/92737149/146380131-1afe1751-7b9a-4a2a-9bb0-93489f283b35.jpg) 
 
[1.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7727615/1.zip)
