### ISSUE TITLE
visibility problem

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#960]
OS: Windows 10 Version 2009
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.1015.24301 +4280 (Git)
Build type: Release
Branch: LinkDaily
Hash: 556c87868ea46796242156e9f73eae98259794b7
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/United States (en_US)
 
If you look, the group is hidden but the Solid in it is visible.  Although Solid is inside the group, it should not be visible when the group is hidden.  
 
![1](https://user-images.githubusercontent.com/92737149/144714236-8c72453e-6ad6-44fc-8f85-786b5359bde6.jpg) 

 You can see in the video below that all the items in the group are visible when I order the group to be visible.However, what was already visible in the group should have been visible. Not all items in the group should be visible. 

https://user-images.githubusercontent.com/92737149/144714313-08ccd694-874c-4409-987d-aaa7a0cc6f70.mp4        

It works fine by ordering two or three times to hide and see, but it is an unforgettable problem.      

https://user-images.githubusercontent.com/92737149/144714673-2056ebc0-baf9-4bf1-9abc-523eee663208.mp4    

 #956

**Comment by realthunder** [comment]
This behavior is inherited from upstream, and it is a designed behavior. The visibility of the `Plain` group is used as a shortcut to toggle all its children's visibility together, while at the same time, each individual object can toggle its own visibility without affecting the parent group's visibility.

This behavior has its pros and cons. What you prefered is implemented in the `App::Part` container.

**Comment by hamza00789** [comment]
Looks like you didn't understand me.  Or I could not understand you. If it
is designed behavior So how will it be determined that the group now has to
show all its children in this bar and in this bar show the child that is
already visible. Can you explain how it works?

**Comment by realthunder** [comment]
When you hide the group, it will make a snapshot to remember what objects are visible at the time. Next time the group is made visible, it will show those objects. If you toggle individual object in the group while the group is hidden, it will adjust the snapshot for that object.

To toggle all children visibility of the group,  right click the object and select `Visibility -> Toggle group visibility`. I have just added code in the above referenced commit to support toggle children visibility by `Ctrl + Click` the eye icon of the group. There is also a fix of a bug in group visibility snapshot.
