### ISSUE TITLE
Problem with the display of the toolbar view

### ISSUE THREAD

**Issue by lebearnais64** [realthunder/FreeCAD_assembly3#961]
Hello.
I move the toolbar  view and I put it on the edge of the screen. I use the mac os version.
Now it is impossible to move the toolbar.
![image](https://user-images.githubusercontent.com/17858470/144727367-58ba3216-684b-476a-9c56-736cd49167a3.png)

I uninstall freecad and install il again. Still have the problem.

Thanks for your help

**Comment by hamza00789** [comment]
> Hello. I move the toolbar view and I put it on the edge of the screen. I use the mac os version. Now it is impossible to move the toolbar. ![image](https://user-images.githubusercontent.com/17858470/144727367-58ba3216-684b-476a-9c56-736cd49167a3.png)
> 
> I uninstall freecad and install il again. Still have the problem.
> 
> Thanks for your help      
 
toolbar moving in only four sides. 
top bottom and left right  

https://user-images.githubusercontent.com/92737149/144728273-6b67a8a0-52d8-46f1-8e5d-8ba891a715c0.mp4

**Comment by lebearnais64** [comment]
In fact I moved the toolbar but the toolbar did not plug on the left side as you show. I have two screen so the toolbar is limit to the 2 screens and I cannot have the cross to move it. 
![image](https://user-images.githubusercontent.com/17858470/144756855-f33b48dd-59d1-482b-ae90-596f54ce800a.png)

**Comment by lebearnais64** [comment]
https://user-images.githubusercontent.com/17858470/144758399-4e599c2f-be1e-420d-bd62-07bbc90dc895.mov

**Comment by lebearnais64** [comment]
the left side is my second screen. I can move the freecad window as shown in the movie but impossible to move the toolbar.
Any idea?

**Comment by hamza00789** [comment]
> the left side is my second screen. I can move the freecad window as shown in the movie but impossible to move the toolbar. Any idea?

Once you've removed the freecad setting, the toolbar will return to its original location

**Comment by lebearnais64** [comment]
thanks a lot. Everything is ok now. Just to redo the settings ;-)
