### ISSUE TITLE
The array tool (draft WB) gives an unexpected (wrong) result when "Expand array" parameter is set to "True"

### ISSUE THREAD

**Issue by mwlandolsi** [realthunder/FreeCAD_assembly3#965]
Hello
Just create a circular array (Draft WB) of a cylinder (from Part wb) then set the "Expand array" parameter is set to "True". 

![Screenshot from 2021-12-13 11-11-59](https://user-images.githubusercontent.com/76944804/145800000-8ed7d03d-2cba-472c-83ac-7b9a7d4838e4.png)

Now modify the "Radial Distance" for example (also the same problem with "Tangential Distance"). The result is an incorrect display of the array.

![Screenshot from 2021-12-13 11-14-16](https://user-images.githubusercontent.com/76944804/145799580-69a8a9f2-2bc8-4a65-b4a8-9c058b2e523c.png)
![Screenshot from 2021-12-13 11-14-00](https://user-images.githubusercontent.com/76944804/145799575-fc9c1765-9846-41b1-b8c2-8637970b3d86.png)

![Screenshot from 2021-12-13 11-41-56](https://user-images.githubusercontent.com/76944804/145799585-d3369a0d-0344-40db-84f6-8f43d13c0616.png)

The good thing is that  The result of the boolean operation issued from the pattern is correct.

![Screenshot from 2021-12-13 12-01-10](https://user-images.githubusercontent.com/76944804/145801263-07d270e2-29c2-449c-a8e9-4aaf90446590.png)
here is the file :
[cylinder patern and cut.FCStd.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7703212/cylinder.patern.and.cut.FCStd.zip)

OS: Linux Mint 20.1 (X-Cinnamon/cinnamon)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.1015.24301 +4280 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 556c87868ea46796242156e9f73eae98259794b7
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: English/United States (en_US)

**Comment by realthunder** [comment]
One of the purpose to provide the option to expand the array is so that the user can manually move some of the array instances. So, the placement syncing is disabled by default if the array is expanded. If you still need placement sync while expanded, you can turn on property `AlwaysSyncPlacement`.

**Comment by mwlandolsi** [comment]
Many thanks
