### ISSUE TITLE
[FR] sketcher replace geometry

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#976]
FreeCad sketcher should have the option to replace geometry  

                   
This error will not come from replace geometry     

https://user-images.githubusercontent.com/92737149/146834664-97aef050-92d8-4012-a0d0-c610b7432a3c.mp4    

![FR](https://user-images.githubusercontent.com/92737149/146835847-d16be38b-d8b3-4b6c-8564-4d6654a2e5e2.jpg)

**Comment by realthunder** [comment]
It's already there. But it's not working in the latest release. I've already fixed it. Just select the two geometry you want to exchange and click the following command.

![swap](https://user-images.githubusercontent.com/1207888/147012543-2506f0bb-edce-4de8-9ab2-016a422008bb.jpg)

**Comment by hamza00789** [comment]
> It's already there. But it's not working in the latest release. I've already fixed it. Just select the two geometry you want to exchange and click the following command.
> 
> ![swap](https://user-images.githubusercontent.com/1207888/147012543-2506f0bb-edce-4de8-9ab2-016a422008bb.jpg)

But it is not working properly, it will work properly in the upcoming release

**Comment by hamza00789** [comment]
thanks to solve
