### ISSUE TITLE
Nested assemblies with exported elements from link arrays can cause FreeCAD to create invalid XML due to unescaped <

### ISSUE THREAD

**Issue by ToniTen** [realthunder/FreeCAD_assembly3#982]
When working with a hierarchy of assembly3 containers and using link arrays, it is possible to have FreeCAD create invalid XML that it can't then open later due to unescaped < symbols in XML. These symbols are created automatically when referencing elements from a link array from at least 2 levels up in the hierarchy. The issue presents itself when loading the file, so the user will save his files normally and only notice when opening them later. 

This happened in a real life situation, and was replicated with dummy geometry  in the [attached files.](https://github.com/realthunder/FreeCAD_assembly3/files/7768949/unescaped.lt.zip)

FreeCAD reports this on stderr
```
/tmp/.mount_FreeCAc7rFuc
FreeCAD 0.19, Libs: 2021.1015R24301 +4280 (Git)
Fatal Error at file /tmp/unescaped lt/cylinder+2cubes+2cones.FCStd, line 937, char 75
<App> PropertyContainer.cpp(479): '<' character cannot be used in attribute value 'sub'; use &lt; instead
In context: |cylinder_2cubes_2cones|_Element001|LinkedObject while parsing cylinder_2cubes_2cones#_Element001.LinkedObject
6.1e-07 <App> Document.cpp(2377): Exception while restoring cylinder_2cubes_2cones._Element001
```

Unzipping the file and checking Document.xml, the offending line is
`<XLink file="" stamp="" name="Link" sub="1.$Face2@CubeAS3<0>."/>`
As you can see, it has unescaped < and > characters that break the XML file.

The problem file, cylinder+2cubes+2cones.FCStd, is present in the zip, but since the file causes issues when loading it, I'm presenting you with a way to re-create it

### Steps to reproduce

1. Create a new file with a new assembly, we shall name it NewAssembly
2. Open cylinder+2cubes.FCStd
3. Open cone.FCStd
4. Link these two assemblies to NewAssembly
5. Select Face2@CubeAS3<0> in Cylinder+2CubesAS3 and create a new element in NewAssembly. This element will automatically have the name Face2@Cylinder+2CubesAS3
6. Select face1 in ConeAS3 and create a new element in NewAssembly. This element will automatically have the name face1@ConeAS3
7. Create a constraint between these two elements
8. Save the file and reopen it

### Workaround
It is possible to workaround the issue by removing the < and > symbols from the elements in assembly Cylinder+2CubesAS3 from file cylinder+2cubes.FCStd. The affected elements would be: Face1@CubeAS3<0>, Face1@CubeAS3<1>, Face2@CubeAS3<0>, and Face2@CubeAS3<1>

### FreeCAD version information
```

OS: Ubuntu 18.04.6 LTS (XFCE/xubuntu)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 2021.1015.24301 +4280 (Git) AppImage
Build type: Release
Branch: LinkDaily
Hash: 556c87868ea46796242156e9f73eae98259794b7
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.1
OCC version: 7.5.2
Locale: Spanish/Spain (es_ES)
```

**Comment by realthunder** [comment]
Thanks for the detailed report. This issue has been reported by others (#928), and is fixed already. I'll make new release soon. You can reopened the issue if you still have problem by then.
