### ISSUE TITLE
[FR] Replace Face 

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#986]
Replace face can make a specific face equal to a specific face or many faces can be made equal to a specific face. It works well in solid.   
As you can see in the picture.      

![1](https://user-images.githubusercontent.com/92737149/147296534-ff6c828f-1b61-4404-964b-7b3db25e6873.jpg) 

![2](https://user-images.githubusercontent.com/92737149/147296541-19858c2c-e479-4103-a52c-71db3028979f.jpg)  
 
Result
 
![3](https://user-images.githubusercontent.com/92737149/147296552-834ea421-ed31-40cc-b9ca-ad9a81c296d5.jpg) 

![4](https://user-images.githubusercontent.com/92737149/147296561-9a9d2c1c-e2a6-4ef6-9905-adc570668d95.jpg) 

![5](https://user-images.githubusercontent.com/92737149/147296567-7b96a40c-3afa-43f6-81b6-bbe14ae3f67d.jpg) 

https://user-images.githubusercontent.com/92737149/147296961-9f020a61-c700-44f4-bdc9-f05a4f2dacad.mp4 

https://user-images.githubusercontent.com/92737149/147297325-16adb3d1-69fc-4ead-8337-bfde19b1640b.mp4

**Comment by herrgerd** [comment]
Hey @hamza00789 I don't know if _you_ know, but @realthunder coding this branch of FreeCAD is a one-man-show!
When the bug-tracker is growing we should at least pause our feature-requests for a while.

He's doing all of this alone...

**Comment by hamza00789** [comment]
Okay, now I won't be requesting any feature for a year. If a feature request is unbearable, turn it off

**Comment by ceremcem** [comment]
I can't talk *on* behalf of @realthunder but my own opinion about the feature requests as follows: 

* Rationale must be clearly explained. What is the benefit of that feature? How is it useful for a wide range of users?
* Usage (steps to perform that operation) must be clearly explained. 

Rest is all about triage (time, energy, motivation), which is all in @realthunder's jurisdiction. 

I guess the point @herrgerd underlines is that this project hasn't got enough resources (man power) and too many feature request won't find the chance to be implemented, thereby may demotivate the developers (@realthunder in this case).

**Comment by hamza00789** [comment]
> I can't talk _on_ behalf of @realthunder but my own opinion about the feature requests is as follows:
> 
>     * Rationale must be clearly explained. What is the benefit of that feature? How is it useful for a wide range of users?
> 
>     * Usage (steps to perform that operation) must be clearly explained.
> 
> 
> Rest is all about triage (time, energy, motivation), which is all in @realthunder's jurisdiction.
> 
> I guess the point @herrgerd underlines is that this project hasn't got enough resources (manpower) and too many feature request won't find the chance to be implemented, thereby may demotivate the developers (@realthunder in this case). 

Wouldn't have requested it if it hadn't been useful.  Its benefit. If this is done with a Link this saves time. The work I have shown in advertisements can easily be done in any other way. Sometimes parts of the design are complicated. This can be very helpful if you want to get things done quickly in solid. Otherwise, the complex parts of the design just have to be converted into a surface then work on them, and then have to be converted back to solid. This can take a long time and can be difficult. I think it would be an exaggeration to say difficult but it takes more time. I wish I could give you an example. But for that, I have to do a lot of work and then I have to show you why it is necessary. These must be important. Just understand that. I will try to explain with a simple example (step file) why this is necessary. I used software called CATIA. When you are designing advanced level. So sometimes it feels necessary. At first glance, this may seem like a simple command, but when it is needed, its value is realized.
