### ISSUE TITLE
Bevel macro not working

### ISSUE THREAD

**Issue by hamza00789** [realthunder/FreeCAD_assembly3#988]
They do not work properly in Link Daily. 

![1](https://user-images.githubusercontent.com/92737149/147401593-e58a7ed3-64e4-495e-98e7-1bbfa2c37775.jpg) 

Works well in 0.20 Version 

![2](https://user-images.githubusercontent.com/92737149/147401602-e06b8866-97ec-4035-b5d3-9bde547a07a3.jpg)

**Comment by bambukouk** [comment]
> They do not work properly in Link Daily.

You could try to be a bit more descriptive?
I have plenty of macros that work perfectly fine in latest Daily version :+1: 

so, `NOT "Macros not working"`

I guess **`your issue is with Bevel macro specifically?`**

error message:
```
File "/home/owner/.FreeCAD/Macro/bevel.py", line 129, in execute
    FreeCAD/Console.PrintError("Error making boolean\n")
<class 'NameError'>: name 'Console' is not defined
```

**Comment by hamza00789** [comment]
> > They do not work properly in Link Daily.
> 
> You could try to be a bit more descriptive? I have plenty of macros that work perfectly fine in latest Daily version 👍
> 
> so, `NOT "Macros not working"`
> 
> I guess **`your issue is with Bevel macro specifically?`**
> 
> error message:
> 
> ```
> File "/home/owner/.FreeCAD/Macro/bevel.py", line 129, in execute
>     FreeCAD/Console.PrintError("Error making boolean\n")
> <class 'NameError'>: name 'Console' is not defined
> ```

The first parametric defeaturing was also not working. But now it is working. But Bevel is still not working. Can you tell me why it is not working?

**Comment by luzpaz** [comment]
Please retest on latest Daily and report back. Thank you!

**Comment by hamza00789** [comment]
> Please retest on latest Daily and report back. Thank you!

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.111.30764 (Git)
Build type: Release
Branch: LinkDaily
Hash: ef3092bcbca5475eff4eb7ff7933eb3e9bbbe4b9
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: English/United States (en_US)  

It's still not working (bevel)

![1](https://user-images.githubusercontent.com/92737149/149217906-2155637e-98d0-4616-9360-f7467007450b.jpg)

**Comment by luzpaz** [comment]
x-posted https://forum.freecadweb.org/viewtopic.php?style=10&p=563017#p563017

**Comment by mwganson** [comment]
There is a typo in the source code.  It should be FreeCAD.Console and not FreeCAD/Console.  I will fix it.

**Comment by hamza00789** [comment]
> There is a typo in the source code. It should be FreeCAD.Console and not FreeCAD/Console. I will fix it.

The bevel macro is not working in the new release either.                   

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 2022.402.26244 +4679 (Git)
Build type: Release
Branch: LinkDaily
Hash: 2ed36c0a234b3871a790ac8437f496f29e025ded
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.6.0
Locale: English/United States (en_US)

**Comment by mwganson** [comment]
I don't have LinkDaily installed for testing.  Do you get any error message?  What are the steps to reproduce?  "It's not working," isn't much to go on.  Exactly how is it failing?

**Comment by hamza00789** [comment]
https://user-images.githubusercontent.com/92737149/162018223-c55f2740-b7fd-46ea-ba30-1261441911e5.mp4     

[New Text Document.txt](https://github.com/realthunder/FreeCAD_assembly3/files/8428627/New.Text.Document.txt)

**Comment by mwganson** [comment]
new version: 0.2022.04.06

Please test and report back.  You will need to restart FreeCAD after updating.

**Comment by hamza00789** [comment]
> 

it still doesn't work. The error message is something like this.   

[Mp4.zip](https://github.com/realthunder/FreeCAD_assembly3/files/8438930/Mp4.zip) 

[New Text Document.txt](https://github.com/realthunder/FreeCAD_assembly3/files/8438935/New.Text.Document.txt)

**Comment by mwganson** [comment]
new version 0.2022.04.06b

**Comment by hamza00789** [comment]
> 
Is working fine now.
