### ISSUE TITLE
'Part.Shape' object has no attribute 'countSubElements'

### ISSUE THREAD

**Issue by xiaomingneo** [realthunder/FreeCAD_assembly3#992]
I'm trying the simple example with just a Cube and a Cylinder,

while press the \<Place Coincidence\> button, the problem below occurs:

```python
10:42:30  Traceback (most recent call last):
  File "/home/neo/.FreeCAD/Mod/FreeCAD_assembly3/freecad/asm3/assembly.py", line 802, in execute
    fcount = shape.countSubElements('Face')
<class 'AttributeError'>: 'Part.Shape' object has no attribute 'countSubElements'
```

I'm using the  realthunder fork of FreeCAD:
FreeCAD-asm3-Daily-Conda-Py3-Qt5-20211015-glibc2.12-x86_64.AppImage

**Comment by realthunder** [comment]
Fixed in the above commit. Please update you local clone of asm3 repository.

**Comment by xiaomingneo** [comment]
it works.

thank you very much!

> Fixed in the above commit. Please update you local clone of asm3 repository.
