### ISSUE TITLE
chamfer crash

### ISSUE THREAD

**Issue by apper002** [realthunder/FreeCAD_assembly3#996]
select edge and chamfer then crash. constant pattern. see log file

[](url)

[FreeCAD.log](https://github.com/realthunder/FreeCAD_assembly3/files/7796284/FreeCAD.log)

**Comment by apper002** [comment]
another edge same result
[FreeCAD.log](https://github.com/realthunder/FreeCAD_assembly3/files/7796359/FreeCAD.log)

**Comment by bambukouk** [comment]
How about sharing the model as well?
That might help ...

**Comment by apper002** [comment]
You have the log file.................

**Comment by realthunder** [comment]
The log shows a known bug in OCC 7.5, which is fixed in 7.6. Conda already has 7.6 build available. I'll make the next release with OCC 7.6.

**Comment by apper002** [comment]
ThX RT.
