### ISSUE TITLE
A Happy and Healthy New Year 2022 to YOU!

### ISSUE THREAD

**Issue by herrgerd** [realthunder/FreeCAD_assembly3#997]
Hey Lei,
THANK YOU for doing so much work on the FreeCAD project.
Really appeciate it, as FreeCAD is the only 100% free and open-source 3D parametric CAD-software out there.

I hope you stay healthy and have a wonderful year 2022! 😀

Cheers, Jan
P.S.: Of course I will close this "issue" in 1 or 2 days 😉

**Comment by okkof2000** [comment]
Hey Lei,
Happy new year to you and your family! I wish you all the blessings and success you truly deserve.

**Comment by luzpaz** [comment]
Happy New Year RT and the rest of the LS3/Link Daily crew!

**Comment by ceremcem** [comment]
Wish you all a happy and healthy new year!
