### ISSUE TITLE
Arch Wall and Window does not move correctly along with Arch Floor

### ISSUE THREAD

**Issue by cadmarx** [realthunder/FreeCAD_assembly3#998]
I am using FreeCAD_assembly 3 version 2021.10.15. It seems Arch Wall and Window does not move correctly according to Arch Floor coordinates; the problem is even more apparent when a change in coordinate of Arch Floor is UNDONE. I have attached a GIF of the operations for clarity.
![Wall inside Arch  Floor](https://user-images.githubusercontent.com/92646037/147835320-4c2e4df2-e1dd-4d83-ac67-32fb1aa79bce.gif)

**Comment by luzpaz** [comment]
Can you reproduce in upstream master v0.20dev?

**Comment by cadmarx** [comment]
Will do soon..

**Comment by cadmarx** [comment]
Hi luzpaz,

I checked with FreeCAD_0.20.26858. It has the very same problem.

**Comment by luzpaz** [comment]
Close....please open a ticket on the forum. Lets let realthunder continue fixing assmebly3 and porting his changes upstream. There are other arch devs that can tackle this.
