### ISSUE TITLE
SubtractiveHelix creates weird shell

### ISSUE THREAD

**Issue by marthinwurer** [realthunder/FreeCAD_assembly3#999]
![image](https://user-images.githubusercontent.com/13510049/147865134-5aae9b8d-e9eb-4f7b-8a03-10198b964669.png)

[Helix_tube.zip](https://github.com/realthunder/FreeCAD_assembly3/files/7798496/Helix_tube.zip)

I attempted to make threads around the end of a pipe, and FreeCAD threw a blob in there that clogged the pipe.

**Comment by bambukouk** [comment]
Try the attached file
(I just renamed it.zip rather than compress already compressed file - to open in FreeCAD just rename it to .FCStd)
[Helix_tube(BAMBUKO).zip](https://github.com/realthunder/FreeCAD_assembly3/files/7799039/Helix_tube.BAMBUKO.zip)

![thread](https://user-images.githubusercontent.com/50301871/147875292-0ada0d5e-ef77-4c4f-b2bc-577c59743997.png)

**Comment by marthinwurer** [comment]
hmm, that has the bottom edge flat but I wanted it to be chamfered. I guess I could try chamfering it after the fact.

**Comment by bambukouk** [comment]
Simply because it was quicker :-)
The point I was making - there were problems with your sketch.
I am sure it can be chamfered both ends - just need to get the sketch right
I leave it to you ;-)

**Comment by luzpaz** [comment]
Is this ticket then PEBKAC ?

**Comment by bambukouk** [comment]
translate please - what is PEBKAC?

**Comment by luzpaz** [comment]
PEBKAC (an acronym for "problem exists between keyboard and chair") :wink:

**Comment by bambukouk** [comment]
That's new one to me 🙂
People need some place to ask for help...
Here in "issues" is  possibly not the best place?
but they don't want us on FreeCAD forum either...🥸
unless it is in assembly section?

**Comment by luzpaz** [comment]
Yea, it's an issue since RT made his own branch. Probably a room on Discord or something? I'm closing this ticket

**Comment by bambukouk** [comment]
I joined Discord to see what's it like .... 
not for me (maybe I am just old 🤣)

**Comment by luzpaz** [comment]
There is also https://gitter.im/FreeCAD/FreeCAD

**Comment by bambukouk** [comment]
To me it's like another Discord 😬
Personally I like forum with all the functionality it offers
Pity they can't create section dedicated to Link branch....
